Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lparser.c File Reference
lparser.c File Reference
#include <string.h>
#include "lua.h"
#include "lcode.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "llex.h"
#include "lmem.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
Classes
struct BlockCnt
struct ConsControl
struct LHS_assign
Macros
#define lparser_c
#define LUA_CORE
#define MAXVARS 200
#define hasmultret(k) ((k) == VCALL || (k) == VVARARG)
#define check_condition(ls, c, msg) { if (!(c)) luaX_syntaxerror(ls, msg); }
#define new_localvarliteral(ls, v) new_localvarliteral_(ls, "" v, (sizeof(v)/sizeof(char))-1)
#define leavelevel(ls) ((ls)->L->nCcalls--)
#define UNARY_PRIORITY 8 /* priority for unary operators */
Typedefs
typedef struct BlockCnt BlockCnt
Functions
static void statement (LexState *ls)
static void expr (LexState *ls, expdesc *v)
static void anchor_token (LexState *ls)
static l_noret semerror (LexState *ls, const char *msg)
static l_noret error_expected (LexState *ls, int token)
static l_noret errorlimit (FuncState *fs, int limit, const char *what)
static void checklimit (FuncState *fs, int v, int l, const char *what)
static int testnext (LexState *ls, int c)
static void check (LexState *ls, int c)
static void checknext (LexState *ls, int c)
static void check_match (LexState *ls, int what, int who, int where)
static TString * str_checkname (LexState *ls)
static void init_exp (expdesc *e, expkind k, int i)
static void codestring (LexState *ls, expdesc *e, TString *s)
static void checkname (LexState *ls, expdesc *e)
static int registerlocalvar (LexState *ls, TString *varname)
static void new_localvar (LexState *ls, TString *name)
static void new_localvarliteral_ (LexState *ls, const char *name, size_t sz)
static LocVar * getlocvar (FuncState *fs, int i)
static void adjustlocalvars (LexState *ls, int nvars)
static void removevars (FuncState *fs, int tolevel)
static int searchupvalue (FuncState *fs, TString *name)
static int newupvalue (FuncState *fs, TString *name, expdesc *v)
static int searchvar (FuncState *fs, TString *n)
static void markupval (FuncState *fs, int level)
static int singlevaraux (FuncState *fs, TString *n, expdesc *var, int base)
static void singlevar (LexState *ls, expdesc *var)
static void adjust_assign (LexState *ls, int nvars, int nexps, expdesc *e)
static void enterlevel (LexState *ls)
static void closegoto (LexState *ls, int g, Labeldesc *label)
static int findlabel (LexState *ls, int g)
static int newlabelentry (LexState *ls, Labellist *l, TString *name, int line, int pc)
static void findgotos (LexState *ls, Labeldesc *lb)
static void movegotosout (FuncState *fs, BlockCnt *bl)
static void enterblock (FuncState *fs, BlockCnt *bl, lu_byte isloop)
static void breaklabel (LexState *ls)
static l_noret undefgoto (LexState *ls, Labeldesc *gt)
static void leaveblock (FuncState *fs)
static Proto * addprototype (LexState *ls)
static void codeclosure (LexState *ls, expdesc *v)
static void open_func (LexState *ls, FuncState *fs, BlockCnt *bl)
static void close_func (LexState *ls)
static int block_follow (LexState *ls, int withuntil)
static void statlist (LexState *ls)
static void fieldsel (LexState *ls, expdesc *v)
static void yindex (LexState *ls, expdesc *v)
static void recfield (LexState *ls, struct ConsControl *cc)
static void closelistfield (FuncState *fs, struct ConsControl *cc)
static void lastlistfield (FuncState *fs, struct ConsControl *cc)
static void listfield (LexState *ls, struct ConsControl *cc)
static void field (LexState *ls, struct ConsControl *cc)
static void constructor (LexState *ls, expdesc *t)
static void parlist (LexState *ls)
static void body (LexState *ls, expdesc *e, int ismethod, int line)
static int explist (LexState *ls, expdesc *v)
static void funcargs (LexState *ls, expdesc *f, int line)
static void primaryexp (LexState *ls, expdesc *v)
static void suffixedexp (LexState *ls, expdesc *v)
static void simpleexp (LexState *ls, expdesc *v)
static UnOpr getunopr (int op)
static BinOpr getbinopr (int op)
static BinOpr subexpr (LexState *ls, expdesc *v, int limit)
static void block (LexState *ls)
static void check_conflict (LexState *ls, struct LHS_assign *lh, expdesc *v)
static void assignment (LexState *ls, struct LHS_assign *lh, int nvars)
static int cond (LexState *ls)
static void gotostat (LexState *ls, int pc)
static void checkrepeated (FuncState *fs, Labellist *ll, TString *label)
static void skipnoopstat (LexState *ls)
static void labelstat (LexState *ls, TString *label, int line)
static void whilestat (LexState *ls, int line)
static void repeatstat (LexState *ls, int line)
static int exp1 (LexState *ls)
static void forbody (LexState *ls, int base, int line, int nvars, int isnum)
static void fornum (LexState *ls, TString *varname, int line)
static void forlist (LexState *ls, TString *indexname)
static void forstat (LexState *ls, int line)
static void test_then_block (LexState *ls, int *escapelist)
static void ifstat (LexState *ls, int line)
static void localfunc (LexState *ls)
static void localstat (LexState *ls)
static int funcname (LexState *ls, expdesc *v)
static void funcstat (LexState *ls, int line)
static void exprstat (LexState *ls)
static void retstat (LexState *ls)
static void mainfunc (LexState *ls, FuncState *fs)
Closure * luaY_parser (lua_State *L, ZIO *z, Mbuffer *buff, Dyndata *dyd, const char *name, int firstchar)
Variables
struct {
lu_byte left
lu_byte right
} priority []
Macro Definition Documentation
#define check_condition (ls, c, msg) { if (!(c)) luaX_syntaxerror(ls, msg); }
Definition at line 122 of file lparser.c.
Referenced by assignment(), exprstat(), and simpleexp().
#define hasmultret (k) ((k) == VCALL || (k) == VVARARG)
Definition at line 35 of file lparser.c.
Referenced by adjust_assign(), funcargs(), lastlistfield(), and retstat().
#define leavelevel (ls) ((ls)->L->nCcalls--)
Definition at line 337 of file lparser.c.
Referenced by statement(), and subexpr().
#define lparser_c
Definition at line 10 of file lparser.c.
#define LUA_CORE
Definition at line 11 of file lparser.c.
#define MAXVARS 200
Definition at line 32 of file lparser.c.
Referenced by new_localvar().
#define new_localvarliteral (ls, v) new_localvarliteral_(ls, "" v, (sizeof(v)/sizeof(char))-1)
Definition at line 194 of file lparser.c.
Referenced by body(), forlist(), and fornum().
#define UNARY_PRIORITY 8 /* priority for unary operators */
Definition at line 1030 of file lparser.c.
Referenced by subexpr().
Typedef Documentation
typedef struct BlockCnt BlockCnt
Function Documentation
static Proto* addprototype (LexState * ls) static
Definition at line 498 of file lparser.c.
References FuncState::f, LexState::fs, LexState::L, luaC_objbarrier, luaF_newproto(), luaM_growvector, MAXARG_Bx, FuncState::np, Proto::p, and Proto::sizep.
Referenced by body().
static void adjust_assign (LexState * ls, int nvars, int nexps, expdesc * e) static
Definition at line 310 of file lparser.c.
References FuncState::freereg, LexState::fs, hasmultret, expdesc::k, luaK_exp2nextreg(), luaK_nil(), luaK_reserveregs(), luaK_setreturns(), and VVOID.
Referenced by assignment(), forlist(), and localstat().
static void adjustlocalvars (LexState * ls, int nvars) static
Definition at line 205 of file lparser.c.
References cast_byte, LexState::fs, getlocvar(), FuncState::nactvar, FuncState::pc, and LocVar::startpc.
Referenced by body(), forbody(), localfunc(), localstat(), and parlist().
static void anchor_token (LexState * ls) static
Definition at line 60 of file lparser.c.
References LexState::fs, getstr, TString::len, lua_assert, luaX_newstring(), Token::seminfo, LexState::t, TK_EOS, TK_NAME, TK_STRING, Token::token, SemInfo::ts, and TString::tsv.
Referenced by close_func().
static void assignment (LexState * ls, struct LHS_assign * lh, int nvars) static
Definition at line 1136 of file lparser.c.
References adjust_assign(), check_condition, check_conflict(), checklimit(), checknext(), explist(), FuncState::freereg, LexState::fs, init_exp(), expdesc::k, LexState::L, LUAI_MAXCCALLS, luaK_setoneret(), luaK_storevar(), lua_State::nCcalls, LHS_assign::prev, suffixedexp(), testnext(), LHS_assign::v, VINDEXED, vkisvar, and VNONRELOC.
Referenced by exprstat().
static void block (LexState * ls) static
Definition at line 1082 of file lparser.c.
References enterblock(), LexState::fs, leaveblock(), and statlist().
Referenced by forbody(), ifstat(), luaM_realloc_(), statement(), and whilestat().
static int block_follow (LexState * ls, int withuntil) static
Definition at line 593 of file lparser.c.
References LexState::t, TK_ELSE, TK_ELSEIF, TK_END, TK_EOS, TK_UNTIL, and Token::token.
Referenced by labelstat(), retstat(), statlist(), and test_then_block().
static void body (LexState * ls, expdesc * e, int ismethod, int line) static
Definition at line 788 of file lparser.c.
References addprototype(), adjustlocalvars(), check_match(), checknext(), close_func(), codeclosure(), FuncState::f, Proto::lastlinedefined, Proto::linedefined, LexState::linenumber, new_localvarliteral, open_func(), parlist(), statlist(), TK_END, and TK_FUNCTION.
Referenced by funcstat(), localfunc(), and simpleexp().
static void breaklabel (LexState * ls) static
Definition at line 453 of file lparser.c.
References Labellist::arr, LexState::dyd, findgotos(), LexState::fs, LexState::L, Dyndata::label, luaS_new(), newlabelentry(), and FuncState::pc.
Referenced by leaveblock().
static void check (LexState * ls, int c) static
Definition at line 110 of file lparser.c.
References error_expected(), LexState::t, and Token::token.
Referenced by checknext(), mainfunc(), and str_checkname().
static void check_conflict (LexState * ls, struct LHS_assign * lh, expdesc * v) static
Definition at line 1108 of file lparser.c.
References FuncState::freereg, LexState::fs, expdesc::ind, expdesc::info, expdesc::k, luaK_codeABC(), luaK_reserveregs(), OP_GETUPVAL, OP_MOVE, LHS_assign::prev, expdesc::u, LHS_assign::v, VINDEXED, and VLOCAL.
Referenced by assignment().
static void check_match (LexState * ls, int what, int who, int where) static
Definition at line 126 of file lparser.c.
References error_expected(), LexState::L, LexState::linenumber, luaO_pushfstring(), luaX_syntaxerror(), luaX_token2str(), and testnext().
Referenced by body(), constructor(), forstat(), funcargs(), ifstat(), primaryexp(), repeatstat(), statement(), and whilestat().
static void checklimit (FuncState * fs, int v, int l, const char * what) static
Definition at line 96 of file lparser.c.
References errorlimit().
Referenced by assignment(), enterlevel(), listfield(), new_localvar(), newupvalue(), and recfield().
static void checkname (LexState * ls, expdesc * e) static
Definition at line 160 of file lparser.c.
References codestring(), and str_checkname().
Referenced by fieldsel(), recfield(), and suffixedexp().
static void checknext (LexState * ls, int c) static
Definition at line 116 of file lparser.c.
References check(), and luaX_next().
Referenced by assignment(), body(), constructor(), forbody(), forlist(), fornum(), labelstat(), recfield(), test_then_block(), whilestat(), and yindex().
static void checkrepeated (FuncState * fs, Labellist * ll, TString * label) static
Definition at line 1195 of file lparser.c.
References Labellist::arr, FuncState::bl, BlockCnt::firstlabel, getstr, LexState::L, Labeldesc::line, FuncState::ls, LUA_QS, luaO_pushfstring(), luaS_eqstr(), Labeldesc::name, and semerror().
Referenced by labelstat().
static void close_func (LexState * ls) static
Definition at line 555 of file lparser.c.
References anchor_token(), FuncState::bl, Proto::code, FuncState::f, LexState::fs, Proto::k, LexState::L, leaveblock(), Proto::lineinfo, Proto::locvars, lua_assert, luaC_checkGC, luaK_ret(), luaM_reallocvector, FuncState::nk, FuncState::nlocvars, FuncState::np, FuncState::nups, Proto::p, FuncState::pc, FuncState::prev, Proto::sizecode, Proto::sizek, Proto::sizelineinfo, Proto::sizelocvars, Proto::sizep, Proto::sizeupvalues, lua_State::top, and Proto::upvalues.
Referenced by body(), and mainfunc().
static void closegoto (LexState * ls, int g, Labeldesc * label) static
Definition at line 340 of file lparser.c.
References Labellist::arr, LexState::dyd, LexState::fs, getlocvar(), getstr, Dyndata::gt, LexState::L, Labeldesc::line, lua_assert, LUA_QS, luaK_patchlist(), luaO_pushfstring(), luaS_eqstr(), Labellist::n, Labeldesc::nactvar, Labeldesc::name, Labeldesc::pc, semerror(), and LocVar::varname.
Referenced by findgotos(), and findlabel().
static void closelistfield (FuncState * fs, struct ConsControl * cc) static
Definition at line 673 of file lparser.c.
References expdesc::info, expdesc::k, LFIELDS_PER_FLUSH, luaK_exp2nextreg(), luaK_setlist(), ConsControl::na, ConsControl::t, ConsControl::tostore, expdesc::u, ConsControl::v, and VVOID.
Referenced by constructor().
static void codeclosure (LexState * ls, expdesc * v) static
Definition at line 520 of file lparser.c.
References LexState::fs, init_exp(), luaK_codeABx(), luaK_exp2nextreg(), FuncState::np, OP_CLOSURE, FuncState::prev, and VRELOCABLE.
Referenced by body().
static void codestring (LexState * ls, expdesc * e, TString * s) static
Definition at line 155 of file lparser.c.
References LexState::fs, init_exp(), luaK_stringK(), and VK.
Referenced by checkname(), funcargs(), simpleexp(), and singlevar().
static int cond (LexState * ls) static
Definition at line 1169 of file lparser.c.
References expr(), expdesc::f, LexState::fs, expdesc::k, luaK_goiftrue(), LHS_assign::v, VFALSE, and VNIL.
Referenced by repeatstat(), and whilestat().
static void constructor (LexState * ls, expdesc * t) static
Definition at line 730 of file lparser.c.
References check_match(), checknext(), closelistfield(), Proto::code, FuncState::f, field(), LexState::fs, init_exp(), expdesc::k, lastlistfield(), LexState::linenumber, lua_assert, luaK_codeABC(), luaK_exp2nextreg(), luaO_int2fb(), ConsControl::na, ConsControl::nh, OP_NEWTABLE, SETARG_B, SETARG_C, LexState::t, ConsControl::t, testnext(), Token::token, ConsControl::tostore, ConsControl::v, VRELOCABLE, and VVOID.
Referenced by funcargs(), and simpleexp().
static void enterblock (FuncState * fs, BlockCnt * bl, lu_byte isloop) static
Definition at line 438 of file lparser.c.
References FuncState::bl, LexState::dyd, BlockCnt::firstgoto, BlockCnt::firstlabel, FuncState::freereg, Dyndata::gt, BlockCnt::isloop, Dyndata::label, FuncState::ls, lua_assert, Labellist::n, BlockCnt::nactvar, FuncState::nactvar, BlockCnt::previous, and BlockCnt::upval.
Referenced by block(), forbody(), forstat(), open_func(), repeatstat(), test_then_block(), and whilestat().
static void enterlevel (LexState * ls) static
Definition at line 330 of file lparser.c.
References checklimit(), LexState::fs, LexState::L, LUAI_MAXCCALLS, and lua_State::nCcalls.
Referenced by statement(), and subexpr().
static l_noret error_expected (LexState * ls, int token) static
Definition at line 77 of file lparser.c.
References LexState::L, luaO_pushfstring(), luaX_syntaxerror(), and luaX_token2str().
Referenced by check(), and check_match().
static l_noret errorlimit (FuncState * fs, int limit, const char * what) static
Definition at line 83 of file lparser.c.
References FuncState::f, LexState::L, Proto::linedefined, FuncState::ls, luaO_pushfstring(), and luaX_syntaxerror().
Referenced by checklimit().
static int exp1 (LexState * ls) static
Definition at line 1272 of file lparser.c.
References expr(), LexState::fs, expdesc::info, expdesc::k, lua_assert, luaK_exp2nextreg(), expdesc::u, and VNONRELOC.
Referenced by fornum(), and lua_strx2number().
static int explist (LexState * ls, expdesc * v) static
Definition at line 810 of file lparser.c.
References expr(), LexState::fs, luaK_exp2nextreg(), and testnext().
Referenced by assignment(), forlist(), funcargs(), localstat(), and retstat().
static void expr (LexState * ls, expdesc * v) static
Definition at line 1067 of file lparser.c.
References subexpr().
Referenced by cond(), exp1(), explist(), listfield(), primaryexp(), recfield(), test_then_block(), and yindex().
static void exprstat (LexState * ls) static
Definition at line 1480 of file lparser.c.
References assignment(), check_condition, LexState::fs, getcode, expdesc::k, LHS_assign::prev, SETARG_C, suffixedexp(), LexState::t, Token::token, LHS_assign::v, and VCALL.
Referenced by statement().
static void field (LexState * ls, struct ConsControl * cc) static
Definition at line 708 of file lparser.c.
References listfield(), luaX_lookahead(), recfield(), LexState::t, TK_NAME, and Token::token.
Referenced by constructor().
static void fieldsel (LexState * ls, expdesc * v) static
Definition at line 616 of file lparser.c.
References checkname(), LexState::fs, luaK_exp2anyregup(), luaK_indexed(), and luaX_next().
Referenced by funcname(), and suffixedexp().
static void findgotos (LexState * ls, Labeldesc * lb) static
Definition at line 402 of file lparser.c.
References Labellist::arr, FuncState::bl, closegoto(), LexState::dyd, BlockCnt::firstgoto, LexState::fs, Dyndata::gt, luaS_eqstr(), and Labeldesc::name.
Referenced by breaklabel(), and labelstat().
static int findlabel (LexState * ls, int g) static
Definition at line 364 of file lparser.c.
References Labellist::arr, FuncState::bl, closegoto(), LexState::dyd, BlockCnt::firstlabel, LexState::fs, Dyndata::gt, Dyndata::label, luaK_patchclose(), luaS_eqstr(), Labellist::n, Labeldesc::nactvar, Labeldesc::name, Labeldesc::pc, and BlockCnt::upval.
Referenced by gotostat(), and movegotosout().
static void forbody (LexState * ls, int base, int line, int nvars, int isnum) static
Definition at line 1283 of file lparser.c.
References adjustlocalvars(), block(), checknext(), enterblock(), LexState::fs, leaveblock(), luaK_codeABC(), luaK_codeAsBx, luaK_fixline(), luaK_jump(), luaK_patchlist(), luaK_patchtohere(), luaK_reserveregs(), NO_JUMP, OP_FORLOOP, OP_FORPREP, OP_TFORCALL, OP_TFORLOOP, and TK_DO.
Referenced by forlist(), and fornum().
static void forlist (LexState * ls, TString * indexname) static
Definition at line 1331 of file lparser.c.
References adjust_assign(), checknext(), explist(), forbody(), FuncState::freereg, LexState::fs, LexState::linenumber, luaK_checkstack(), new_localvar(), new_localvarliteral, str_checkname(), testnext(), and TK_IN.
Referenced by forstat().
static void fornum (LexState * ls, TString * varname, int line) static
Definition at line 1309 of file lparser.c.
References checknext(), exp1(), forbody(), FuncState::freereg, LexState::fs, luaK_codek(), luaK_numberK(), luaK_reserveregs(), new_localvar(), new_localvarliteral, and testnext().
Referenced by forstat().
static void forstat (LexState * ls, int line) static
Definition at line 1356 of file lparser.c.
References check_match(), enterblock(), forlist(), fornum(), LexState::fs, leaveblock(), LUA_QL, luaX_next(), luaX_syntaxerror(), str_checkname(), LexState::t, TK_END, TK_FOR, TK_IN, and Token::token.
Referenced by statement().
static void funcargs (LexState * ls, expdesc * f, int line) static
Definition at line 823 of file lparser.c.
References check_match(), codestring(), constructor(), explist(), FuncState::freereg, LexState::fs, hasmultret, expdesc::info, init_exp(), expdesc::k, lua_assert, LUA_MULTRET, luaK_codeABC(), luaK_exp2nextreg(), luaK_fixline(), luaK_setmultret, luaX_next(), luaX_syntaxerror(), OP_CALL, Token::seminfo, LexState::t, TK_STRING, Token::token, SemInfo::ts, expdesc::u, VCALL, VNONRELOC, and VVOID.
Referenced by suffixedexp().
static int funcname (LexState * ls, expdesc * v) static
Definition at line 1454 of file lparser.c.
References fieldsel(), singlevar(), LexState::t, and Token::token.
Referenced by funcstat(), and loadfunc().
static void funcstat (LexState * ls, int line) static
Definition at line 1468 of file lparser.c.
References body(), LexState::fs, funcname(), luaK_fixline(), luaK_storevar(), luaX_next(), and LHS_assign::v.
Referenced by statement().
static BinOpr getbinopr (int op) static
Definition at line 997 of file lparser.c.
References OPR_ADD, OPR_AND, OPR_CONCAT, OPR_DIV, OPR_EQ, OPR_GE, OPR_GT, OPR_LE, OPR_LT, OPR_MOD, OPR_MUL, OPR_NE, OPR_NOBINOPR, OPR_OR, OPR_POW, OPR_SUB, TK_AND, TK_CONCAT, TK_EQ, TK_GE, TK_LE, TK_NE, and TK_OR.
Referenced by subexpr().
static LocVar* getlocvar (FuncState * fs, int i) static
Definition at line 198 of file lparser.c.
References Dyndata::actvar, Dyndata::arr, LexState::dyd, FuncState::f, FuncState::firstlocal, Vardesc::idx, Proto::locvars, FuncState::ls, and lua_assert.
Referenced by adjustlocalvars(), closegoto(), localfunc(), removevars(), and searchvar().
static UnOpr getunopr (int op) static
Definition at line 987 of file lparser.c.
References OPR_LEN, OPR_MINUS, OPR_NOT, OPR_NOUNOPR, and TK_NOT.
Referenced by subexpr().
static void gotostat (LexState * ls, int pc) static
Definition at line 1179 of file lparser.c.
References LexState::dyd, findlabel(), Dyndata::gt, LexState::L, LexState::linenumber, luaS_new(), luaX_next(), newlabelentry(), str_checkname(), testnext(), and TK_GOTO.
Referenced by statement(), and test_then_block().
static void ifstat (LexState * ls, int line) static
Definition at line 1409 of file lparser.c.
References block(), check_match(), LexState::fs, luaK_patchtohere(), NO_JUMP, LexState::t, test_then_block(), testnext(), TK_ELSE, TK_ELSEIF, TK_END, TK_IF, and Token::token.
Referenced by statement().
static void init_exp (expdesc * e, expkind k, int i) static
Definition at line 148 of file lparser.c.
References expdesc::f, expdesc::info, expdesc::k, NO_JUMP, expdesc::t, and expdesc::u.
Referenced by assignment(), codeclosure(), codestring(), constructor(), funcargs(), mainfunc(), simpleexp(), and singlevaraux().
static void labelstat (LexState * ls, TString * label, int line) static
Definition at line 1215 of file lparser.c.
References Labellist::arr, FuncState::bl, block_follow(), checknext(), checkrepeated(), LexState::dyd, findgotos(), LexState::fs, Dyndata::label, BlockCnt::nactvar, Labeldesc::nactvar, newlabelentry(), FuncState::pc, skipnoopstat(), and TK_DBCOLON.
Referenced by statement().
static void lastlistfield (FuncState * fs, struct ConsControl * cc) static
Definition at line 684 of file lparser.c.
References hasmultret, expdesc::info, expdesc::k, LUA_MULTRET, luaK_exp2nextreg(), luaK_setlist(), luaK_setmultret, ConsControl::na, ConsControl::t, ConsControl::tostore, expdesc::u, ConsControl::v, and VVOID.
Referenced by constructor().
static void leaveblock (FuncState * fs) static
Definition at line 472 of file lparser.c.
References Labellist::arr, FuncState::bl, breaklabel(), LexState::dyd, BlockCnt::firstgoto, BlockCnt::firstlabel, FuncState::freereg, Dyndata::gt, BlockCnt::isloop, Dyndata::label, FuncState::ls, lua_assert, luaK_jump(), luaK_patchclose(), luaK_patchtohere(), movegotosout(), Labellist::n, BlockCnt::nactvar, FuncState::nactvar, BlockCnt::previous, removevars(), undefgoto(), and BlockCnt::upval.
Referenced by block(), close_func(), forbody(), forstat(), repeatstat(), test_then_block(), and whilestat().
static void listfield (LexState * ls, struct ConsControl * cc) static
Definition at line 699 of file lparser.c.
References checklimit(), expr(), LexState::fs, MAX_INT, ConsControl::na, ConsControl::tostore, and ConsControl::v.
Referenced by field().
static void localfunc (LexState * ls) static
Definition at line 1423 of file lparser.c.
References adjustlocalvars(), body(), LexState::fs, getlocvar(), expdesc::info, LexState::linenumber, new_localvar(), FuncState::pc, LocVar::startpc, str_checkname(), and expdesc::u.
Referenced by statement().
static void localstat (LexState * ls) static
Definition at line 1434 of file lparser.c.
References adjust_assign(), adjustlocalvars(), explist(), expdesc::k, new_localvar(), str_checkname(), testnext(), and VVOID.
Referenced by statement().
Closure* luaY_parser (lua_State * L, ZIO * z, Mbuffer * buff, Dyndata * dyd, const char * name, int firstchar)
Definition at line 1618 of file lparser.c.
References Dyndata::actvar, LexState::buff, LexState::dyd, FuncState::f, LexState::fs, Dyndata::gt, incr_top, Closure::l, Dyndata::label, lua_assert, luaF_newLclosure(), luaF_newproto(), luaS_new(), luaX_setinput(), mainfunc(), Labellist::n, Dyndata::n, FuncState::nups, LClosure::p, FuncState::prev, setclLvalue, Proto::source, and lua_State::top.
Referenced by f_parser().
static void mainfunc (LexState * ls, FuncState * fs) static
Definition at line 1604 of file lparser.c.
References check(), close_func(), LexState::envn, FuncState::f, init_exp(), Proto::is_vararg, luaX_next(), newupvalue(), open_func(), statlist(), TK_EOS, LHS_assign::v, and VLOCAL.
Referenced by luaY_parser().
static void markupval (FuncState * fs, int level) static
Definition at line 260 of file lparser.c.
References FuncState::bl, BlockCnt::nactvar, BlockCnt::previous, and BlockCnt::upval.
Referenced by singlevaraux().
static void movegotosout (FuncState * fs, BlockCnt * bl) static
Definition at line 420 of file lparser.c.
References Labellist::arr, LexState::dyd, findlabel(), BlockCnt::firstgoto, Dyndata::gt, FuncState::ls, luaK_patchclose(), BlockCnt::nactvar, Labeldesc::nactvar, Labeldesc::pc, and BlockCnt::upval.
Referenced by leaveblock().
static void new_localvar (LexState * ls, TString * name) static
Definition at line 178 of file lparser.c.
References Dyndata::actvar, Dyndata::arr, cast, checklimit(), LexState::dyd, FuncState::firstlocal, LexState::fs, Vardesc::idx, LexState::L, luaM_growvector, MAX_INT, MAXVARS, Dyndata::n, registerlocalvar(), and Dyndata::size.
Referenced by forlist(), fornum(), localfunc(), localstat(), new_localvarliteral_(), and parlist().
static void new_localvarliteral_ (LexState * ls, const char * name, size_t sz) static
Definition at line 190 of file lparser.c.
References luaX_newstring(), and new_localvar().
static int newlabelentry (LexState * ls, Labellist * l, TString * name, int line, int pc) static
Definition at line 384 of file lparser.c.
References Labellist::arr, LexState::fs, LexState::L, Labeldesc::line, luaM_growvector, Labellist::n, Labeldesc::nactvar, FuncState::nactvar, Labeldesc::name, Labeldesc::pc, and Labellist::size.
Referenced by breaklabel(), gotostat(), and labelstat().
static int newupvalue (FuncState * fs, TString * name, expdesc * v) static
Definition at line 231 of file lparser.c.
References cast_byte, checklimit(), FuncState::f, Upvaldesc::idx, expdesc::info, Upvaldesc::instack, expdesc::k, LexState::L, FuncState::ls, luaC_objbarrier, luaM_growvector, MAXUPVAL, Upvaldesc::name, FuncState::nups, Proto::sizeupvalues, expdesc::u, Proto::upvalues, and VLOCAL.
Referenced by mainfunc(), and singlevaraux().
static void open_func (LexState * ls, FuncState * fs, BlockCnt * bl) static
Definition at line 527 of file lparser.c.
References Dyndata::actvar, FuncState::bl, LexState::dyd, enterblock(), FuncState::f, FuncState::firstlocal, FuncState::freereg, LexState::fs, FuncState::h, incr_top, FuncState::jpc, LexState::L, FuncState::lasttarget, FuncState::ls, luaH_new(), Proto::maxstacksize, Dyndata::n, FuncState::nactvar, FuncState::nk, FuncState::nlocvars, NO_JUMP, FuncState::np, FuncState::nups, FuncState::pc, FuncState::prev, sethvalue2s, LexState::source, Proto::source, and lua_State::top.
Referenced by body(), and mainfunc().
static void parlist (LexState * ls) static
Definition at line 759 of file lparser.c.
References adjustlocalvars(), cast_byte, FuncState::f, LexState::fs, Proto::is_vararg, LUA_QL, luaK_reserveregs(), luaX_next(), luaX_syntaxerror(), FuncState::nactvar, new_localvar(), Proto::numparams, str_checkname(), LexState::t, testnext(), TK_DOTS, TK_NAME, and Token::token.
Referenced by body().
static void primaryexp (LexState * ls, expdesc * v) static
Definition at line 877 of file lparser.c.
References check_match(), expr(), LexState::fs, LexState::linenumber, luaK_dischargevars(), luaX_next(), luaX_syntaxerror(), singlevar(), LexState::t, TK_NAME, and Token::token.
Referenced by suffixedexp().
static void recfield (LexState * ls, struct ConsControl * cc) static
Definition at line 652 of file lparser.c.
References checklimit(), checkname(), checknext(), expr(), FuncState::freereg, LexState::fs, expdesc::info, luaK_codeABC(), luaK_exp2RK(), MAX_INT, ConsControl::nh, OP_SETTABLE, LexState::t, ConsControl::t, TK_NAME, Token::token, expdesc::u, and yindex().
Referenced by field().
static int registerlocalvar (LexState * ls, TString * varname) static
Definition at line 165 of file lparser.c.
References FuncState::f, LexState::fs, LexState::L, Proto::locvars, luaC_objbarrier, luaM_growvector, FuncState::nlocvars, Proto::sizelocvars, and LocVar::varname.
Referenced by new_localvar().
static void removevars (FuncState * fs, int tolevel) static
Definition at line 214 of file lparser.c.
References Dyndata::actvar, LexState::dyd, LocVar::endpc, getlocvar(), FuncState::ls, Dyndata::n, FuncState::nactvar, and FuncState::pc.
Referenced by leaveblock().
static void repeatstat (LexState * ls, int line) static
Definition at line 1252 of file lparser.c.
References check_match(), cond(), enterblock(), LexState::fs, leaveblock(), luaK_getlabel(), luaK_patchclose(), luaK_patchlist(), luaX_next(), BlockCnt::nactvar, statlist(), TK_REPEAT, TK_UNTIL, and BlockCnt::upval.
Referenced by statement().
static void retstat (LexState * ls) static
Definition at line 1496 of file lparser.c.
References block_follow(), explist(), FuncState::freereg, LexState::fs, GETARG_A, getcode, hasmultret, expdesc::k, lua_assert, LUA_MULTRET, luaK_exp2anyreg(), luaK_exp2nextreg(), luaK_ret(), luaK_setmultret, FuncState::nactvar, OP_TAILCALL, SET_OPCODE, LexState::t, testnext(), Token::token, and VCALL.
Referenced by statement().
static int searchupvalue (FuncState * fs, TString * name) static
Definition at line 221 of file lparser.c.
References FuncState::f, luaS_eqstr(), FuncState::nups, and Proto::upvalues.
Referenced by singlevaraux().
static int searchvar (FuncState * fs, TString * n) static
Definition at line 246 of file lparser.c.
References cast_int, getlocvar(), luaS_eqstr(), and FuncState::nactvar.
Referenced by singlevaraux().
static l_noret semerror (LexState * ls, const char * msg) static
Definition at line 71 of file lparser.c.
References luaX_syntaxerror(), LexState::t, and Token::token.
Referenced by checkrepeated(), closegoto(), and undefgoto().
static void simpleexp (LexState * ls, expdesc * v) static
Definition at line 937 of file lparser.c.
References body(), check_condition, codestring(), constructor(), FuncState::f, LexState::fs, init_exp(), Proto::is_vararg, LexState::linenumber, LUA_QL, luaK_codeABC(), luaX_next(), expdesc::nval, OP_VARARG, SemInfo::r, Token::seminfo, suffixedexp(), LexState::t, TK_DOTS, TK_FALSE, TK_FUNCTION, TK_NIL, TK_NUMBER, TK_STRING, TK_TRUE, Token::token, SemInfo::ts, expdesc::u, VFALSE, VKNUM, VNIL, VTRUE, and VVARARG.
Referenced by subexpr().
static void singlevar (LexState * ls, expdesc * var) static
Definition at line 297 of file lparser.c.
References codestring(), LexState::envn, LexState::fs, expdesc::k, lua_assert, luaK_indexed(), singlevaraux(), str_checkname(), VLOCAL, VUPVAL, and VVOID.
Referenced by funcname(), and primaryexp().
static int singlevaraux (FuncState * fs, TString * n, expdesc * var, int base) static
Definition at line 271 of file lparser.c.
References init_exp(), markupval(), newupvalue(), FuncState::prev, searchupvalue(), searchvar(), VLOCAL, VUPVAL, and VVOID.
Referenced by singlevar().
static void skipnoopstat (LexState * ls) static
Definition at line 1209 of file lparser.c.
References statement(), LexState::t, TK_DBCOLON, and Token::token.
Referenced by labelstat(), and test_then_block().
static void statement (LexState * ls) static
Definition at line 1529 of file lparser.c.
References block(), check_match(), enterlevel(), exprstat(), FuncState::f, forstat(), FuncState::freereg, LexState::fs, funcstat(), gotostat(), ifstat(), labelstat(), leavelevel, LexState::linenumber, localfunc(), localstat(), lua_assert, luaK_jump(), luaX_next(), Proto::maxstacksize, FuncState::nactvar, repeatstat(), retstat(), str_checkname(), LexState::t, testnext(), TK_BREAK, TK_DBCOLON, TK_DO, TK_END, TK_FOR, TK_FUNCTION, TK_GOTO, TK_IF, TK_LOCAL, TK_REPEAT, TK_RETURN, TK_WHILE, Token::token, and whilestat().
Referenced by skipnoopstat(), and statlist().
static void statlist (LexState * ls) static
Definition at line 604 of file lparser.c.
References block_follow(), statement(), LexState::t, TK_RETURN, and Token::token.
Referenced by block(), body(), mainfunc(), repeatstat(), and test_then_block().
static TString* str_checkname (LexState * ls) static
Definition at line 139 of file lparser.c.
References check(), luaX_next(), Token::seminfo, LexState::t, TK_NAME, and SemInfo::ts.
Referenced by checkname(), forlist(), forstat(), gotostat(), localfunc(), localstat(), parlist(), singlevar(), and statement().
static BinOpr subexpr (LexState * ls, expdesc * v, int limit) static
Definition at line 1037 of file lparser.c.
References enterlevel(), LexState::fs, getbinopr(), getunopr(), leavelevel, left, LexState::linenumber, luaK_infix(), luaK_posfix(), luaK_prefix(), luaX_next(), OPR_NOBINOPR, OPR_NOUNOPR, priority, right, simpleexp(), LexState::t, Token::token, and UNARY_PRIORITY.
Referenced by expr().
static void suffixedexp (LexState * ls, expdesc * v) static
Definition at line 899 of file lparser.c.
References checkname(), fieldsel(), LexState::fs, funcargs(), LexState::linenumber, luaK_exp2anyregup(), luaK_exp2nextreg(), luaK_indexed(), luaK_self(), luaX_next(), primaryexp(), LexState::t, TK_STRING, Token::token, and yindex().
Referenced by assignment(), exprstat(), and simpleexp().
static void test_then_block (LexState * ls, int * escapelist) static
Definition at line 1374 of file lparser.c.
References block_follow(), checknext(), enterblock(), expr(), expdesc::f, LexState::fs, gotostat(), leaveblock(), luaK_concat(), luaK_goiffalse(), luaK_goiftrue(), luaK_jump(), luaK_patchtohere(), luaX_next(), skipnoopstat(), statlist(), expdesc::t, LexState::t, TK_BREAK, TK_ELSE, TK_ELSEIF, TK_GOTO, TK_THEN, Token::token, and LHS_assign::v.
Referenced by ifstat().
static int testnext (LexState * ls, int c) static
Definition at line 101 of file lparser.c.
References luaX_next(), LexState::t, and Token::token.
Referenced by assignment(), check_match(), constructor(), explist(), forlist(), fornum(), gotostat(), ifstat(), localstat(), parlist(), retstat(), and statement().
static l_noret undefgoto (LexState * ls, Labeldesc * gt) static
Definition at line 463 of file lparser.c.
References getstr, isreserved, LexState::L, Labeldesc::line, LUA_QS, luaO_pushfstring(), Labeldesc::name, and semerror().
Referenced by leaveblock().
static void whilestat (LexState * ls, int line) static
Definition at line 1233 of file lparser.c.
References block(), check_match(), checknext(), cond(), enterblock(), LexState::fs, leaveblock(), luaK_getlabel(), luaK_jumpto, luaK_patchtohere(), luaX_next(), TK_DO, TK_END, and TK_WHILE.
Referenced by statement().
static void yindex (LexState * ls, expdesc * v) static
Definition at line 627 of file lparser.c.
References checknext(), expr(), LexState::fs, luaK_exp2val(), and luaX_next().
Referenced by recfield(), and suffixedexp().
Variable Documentation
lu_byte left
Definition at line 1020 of file lparser.c.
Referenced by subexpr().
const { ... } priority[]
Initial value:
= {
   {6, 6}, {6, 6}, {7, 7}, {7, 7}, {7, 7},
   {10, 9}, {5, 4},
   {3, 3}, {3, 3}, {3, 3},
   {3, 3}, {3, 3}, {3, 3},
   {2, 2}, {1, 1}
}
Referenced by subexpr().
lu_byte right
Definition at line 1021 of file lparser.c.
Referenced by subexpr().