Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lauxlib.c File Reference
lauxlib.c File Reference
#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
Classes
struct LoadF
struct LoadS
Macros
#define lauxlib_c
#define LUA_LIB
#define LEVELS1 12 /* size of the first part of the stack */
#define LEVELS2 10 /* size of the second part of the stack */
#define inspectstat(stat, what) /* no op */
#define buffonstack(B) ((B)->b != (B)->initb)
#define freelist 0
Typedefs
typedef struct LoadF LoadF
typedef struct LoadS LoadS
Functions
static int findfield (lua_State *L, int objidx, int level)
static int pushglobalfuncname (lua_State *L, lua_Debug *ar)
static void pushfuncname (lua_State *L, lua_Debug *ar)
static int countlevels (lua_State *L)
LUALIB_API void luaL_traceback (lua_State *L, lua_State *L1, const char *msg, int level)
LUALIB_API int luaL_argerror (lua_State *L, int narg, const char *extramsg)
static int typeerror (lua_State *L, int narg, const char *tname)
static void tag_error (lua_State *L, int narg, int tag)
LUALIB_API void luaL_where (lua_State *L, int level)
LUALIB_API int luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int luaL_fileresult (lua_State *L, int stat, const char *fname)
LUALIB_API int luaL_execresult (lua_State *L, int stat)
LUALIB_API int luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void luaL_setmetatable (lua_State *L, const char *tname)
LUALIB_API void * luaL_testudata (lua_State *L, int ud, const char *tname)
LUALIB_API void * luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API int luaL_checkoption (lua_State *L, int narg, const char *def, const char *const lst[])
LUALIB_API void luaL_checkstack (lua_State *L, int space, const char *msg)
LUALIB_API void luaL_checktype (lua_State *L, int narg, int t)
LUALIB_API void luaL_checkany (lua_State *L, int narg)
LUALIB_API const char * luaL_checklstring (lua_State *L, int narg, size_t *len)
LUALIB_API const char * luaL_optlstring (lua_State *L, int narg, const char *def, size_t *len)
LUALIB_API lua_Number luaL_checknumber (lua_State *L, int narg)
LUALIB_API lua_Number luaL_optnumber (lua_State *L, int narg, lua_Number def)
LUALIB_API lua_Integer luaL_checkinteger (lua_State *L, int narg)
LUALIB_API lua_Unsigned luaL_checkunsigned (lua_State *L, int narg)
LUALIB_API lua_Integer luaL_optinteger (lua_State *L, int narg, lua_Integer def)
LUALIB_API lua_Unsigned luaL_optunsigned (lua_State *L, int narg, lua_Unsigned def)
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void luaL_pushresult (luaL_Buffer *B)
LUALIB_API void luaL_pushresultsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addvalue (luaL_Buffer *B)
LUALIB_API void luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API char * luaL_buffinitsize (lua_State *L, luaL_Buffer *B, size_t sz)
LUALIB_API int luaL_ref (lua_State *L, int t)
LUALIB_API void luaL_unref (lua_State *L, int t, int ref)
static const char * getF (lua_State *L, void *ud, size_t *size)
static int errfile (lua_State *L, const char *what, int fnameindex)
static int skipBOM (LoadF *lf)
static int skipcomment (LoadF *lf, int *cp)
LUALIB_API int luaL_loadfilex (lua_State *L, const char *filename, const char *mode)
static const char * getS (lua_State *L, void *ud, size_t *size)
LUALIB_API int luaL_loadbufferx (lua_State *L, const char *buff, size_t size, const char *name, const char *mode)
LUALIB_API int luaL_loadstring (lua_State *L, const char *s)
LUALIB_API int luaL_getmetafield (lua_State *L, int obj, const char *event)
LUALIB_API int luaL_callmeta (lua_State *L, int obj, const char *event)
LUALIB_API int luaL_len (lua_State *L, int idx)
LUALIB_API const char * luaL_tolstring (lua_State *L, int idx, size_t *len)
LUALIB_API void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup)
LUALIB_API int luaL_getsubtable (lua_State *L, int idx, const char *fname)
LUALIB_API void luaL_requiref (lua_State *L, const char *modname, lua_CFunction openf, int glb)
LUALIB_API const char * luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
static void * l_alloc (void *ud, void *ptr, size_t osize, size_t nsize)
static int panic (lua_State *L)
LUALIB_API lua_State * luaL_newstate (void)
LUALIB_API void luaL_checkversion_ (lua_State *L, lua_Number ver)
Macro Definition Documentation
#define buffonstack (B) ((B)->b != (B)->initb)
Definition at line 431 of file lauxlib.c.
Referenced by luaL_addvalue(), luaL_prepbuffsize(), and luaL_pushresult().
#define freelist 0
Definition at line 519 of file lauxlib.c.
Referenced by luaL_ref(), and luaL_unref().
#define inspectstat (stat, what) /* no op */
Definition at line 240 of file lauxlib.c.
Referenced by luaL_execresult().
#define lauxlib_c
Definition at line 19 of file lauxlib.c.
#define LEVELS1 12 /* size of the first part of the stack */
Definition at line 34 of file lauxlib.c.
Referenced by luaL_traceback().
#define LEVELS2 10 /* size of the second part of the stack */
Definition at line 35 of file lauxlib.c.
Referenced by luaL_traceback().
#define LUA_LIB
Definition at line 20 of file lauxlib.c.
Typedef Documentation
typedef struct LoadF LoadF
typedef struct LoadS LoadS
Function Documentation
static int countlevels (lua_State * L) static
Definition at line 101 of file lauxlib.c.
References lua_getstack().
Referenced by luaL_traceback().
static int errfile (lua_State * L, const char * what, int fnameindex) static
Definition at line 587 of file lauxlib.c.
References LUA_ERRFILE, lua_pushfstring(), lua_remove(), and lua_tostring.
Referenced by luaL_loadfilex().
static int findfield (lua_State * L, int objidx, int level) static
Definition at line 43 of file lauxlib.c.
References lua_concat(), lua_insert(), lua_istable, lua_next(), lua_pop, lua_pushliteral, lua_pushnil(), lua_rawequal(), lua_remove(), LUA_TSTRING, and lua_type().
Referenced by pushglobalfuncname().
static const char* getF (lua_State * L, void * ud, size_t * size) static
Definition at line 569 of file lauxlib.c.
References LoadF::buff, LoadF::f, and LoadF::n.
Referenced by luaL_loadfilex().
static const char* getS (lua_State * L, void * ud, size_t * size) static
Definition at line 672 of file lauxlib.c.
References LoadS::s, and LoadS::size.
Referenced by luaL_loadbufferx().
static void* l_alloc (void * ud, void * ptr, size_t osize, size_t nsize) static
Definition at line 919 of file lauxlib.c.
Referenced by luaL_newstate().
LUALIB_API void luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 459 of file lauxlib.c.
References luaL_addsize, and luaL_prepbuffsize().
Referenced by add_s(), luaL_addstring(), luaL_addvalue(), luaL_gsub(), os_date(), str_gsub(), tconcat(), and writer().
LUALIB_API void luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 466 of file lauxlib.c.
References luaL_addlstring().
Referenced by addquoted(), and luaL_gsub().
LUALIB_API void luaL_addvalue (luaL_Buffer * B)
Definition at line 485 of file lauxlib.c.
References buffonstack, luaL_Buffer::L, lua_insert(), lua_remove(), lua_tolstring(), and luaL_addlstring().
Referenced by add_s(), add_value(), addfield(), findloader(), searchpath(), and str_format().
LUALIB_API int luaL_argerror (lua_State * L, int narg, const char * extramsg)
Definition at line 153 of file lauxlib.c.
References lua_getinfo(), lua_getstack(), LUA_QS, lua_tostring, luaL_error(), lua_Debug::name, lua_Debug::namewhat, and pushglobalfuncname().
Referenced by checkoption(), db_getinfo(), db_getlocal(), db_setlocal(), db_setuservalue(), g_read(), luaL_checkany(), luaL_checkoption(), str_format(), and typeerror().
LUALIB_API void luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 496 of file lauxlib.c.
References luaL_Buffer::b, luaL_Buffer::initb, luaL_Buffer::L, LUAL_BUFFERSIZE, luaL_Buffer::n, and luaL_Buffer::size.
Referenced by findloader(), luaL_buffinitsize(), luaL_gsub(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), and tconcat().
LUALIB_API char* luaL_buffinitsize (lua_State * L, luaL_Buffer * B, size_t sz)
Definition at line 504 of file lauxlib.c.
References luaL_buffinit(), and luaL_prepbuffsize().
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
LUALIB_API int luaL_callmeta (lua_State * L, int obj, const char * event)
Definition at line 715 of file lauxlib.c.
References lua_absindex(), lua_call, lua_pushvalue(), and luaL_getmetafield().
Referenced by luaL_tolstring().
LUALIB_API void luaL_checkany (lua_State * L, int narg)
Definition at line 351 of file lauxlib.c.
References LUA_TNONE, lua_type(), and luaL_argerror().
Referenced by db_getmetatable(), db_setlocal(), db_setupvalue(), io_type(), luaB_getmetatable(), luaB_pcall(), luaB_rawequal(), luaB_rawget(), luaB_rawset(), luaB_tonumber(), luaB_tostring(), and luaB_type().
LUALIB_API lua_Integer luaL_checkinteger (lua_State * L, int narg)
Definition at line 389 of file lauxlib.c.
References LUA_TNUMBER, lua_tointegerx(), and tag_error().
Referenced by luaL_optinteger(), and str_sub().
LUALIB_API const char* luaL_checklstring (lua_State * L, int narg, size_t * len)
Definition at line 357 of file lauxlib.c.
References lua_tolstring(), LUA_TSTRING, and tag_error().
Referenced by addquoted(), g_write(), luaB_tonumber(), luaL_optlstring(), str_byte(), str_find_aux(), str_format(), str_gsub(), str_len(), str_lower(), str_rep(), str_reverse(), str_sub(), and str_upper().
LUALIB_API lua_Number luaL_checknumber (lua_State * L, int narg)
Definition at line 375 of file lauxlib.c.
References LUA_TNUMBER, lua_tonumberx(), and tag_error().
Referenced by luaL_optnumber(), math_abs(), math_acos(), math_asin(), math_atan(), math_atan2(), math_ceil(), math_cos(), math_cosh(), math_deg(), math_exp(), math_floor(), math_fmod(), math_frexp(), math_ldexp(), math_log(), math_max(), math_min(), math_modf(), math_pow(), math_rad(), math_random(), math_sin(), math_sinh(), math_sqrt(), math_tan(), math_tanh(), os_date(), os_difftime(), and str_format().
LUALIB_API int luaL_checkoption (lua_State * L, int narg, const char * def, const char *const lst[])
Definition at line 320 of file lauxlib.c.
References lua_pushfstring(), LUA_QS, luaL_argerror(), luaL_checkstring, and luaL_optstring.
Referenced by f_seek(), f_setvbuf(), luaB_collectgarbage(), and os_setlocale().
LUALIB_API void luaL_checkstack (lua_State * L, int space, const char * msg)
Definition at line 333 of file lauxlib.c.
References lua_checkstack(), LUA_MINSTACK, and luaL_error().
Referenced by g_read(), generic_reader(), luaL_setfuncs(), push_captures(), sort(), and str_byte().
LUALIB_API void luaL_checktype (lua_State * L, int narg, int t)
Definition at line 345 of file lauxlib.c.
References lua_type(), and tag_error().
Referenced by auxupvalue(), checkupval(), db_sethook(), db_setuservalue(), ipairsaux(), luaB_cocreate(), luaB_load(), luaB_next(), luaB_rawget(), luaB_rawset(), luaB_setmetatable(), os_time(), pairsmeta(), sort(), str_dump(), tconcat(), and unpack().
LUALIB_API void* luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 305 of file lauxlib.c.
References luaL_testudata(), and typeerror().
LUALIB_API lua_Unsigned luaL_checkunsigned (lua_State * L, int narg)
Definition at line 398 of file lauxlib.c.
References LUA_TNUMBER, lua_tounsignedx(), and tag_error().
Referenced by andaux(), b_arshift(), b_extract(), b_lshift(), b_not(), b_or(), b_replace(), b_rot(), b_rshift(), b_xor(), luaL_optunsigned(), and math_randomseed().
LUALIB_API void luaL_checkversion_ (lua_State * L, lua_Number ver)
Definition at line 944 of file lauxlib.c.
References lua_pop, lua_pushnumber(), lua_tointeger, lua_tounsigned, lua_version(), and luaL_error().
LUALIB_API int luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 196 of file lauxlib.c.
References lua_concat(), lua_error(), lua_pushvfstring(), and luaL_where().
Referenced by add_s(), add_value(), addfield(), auxsort(), capture_to_close(), check_capture(), checkload(), classend(), fieldargs(), findfile(), findloader(), generic_reader(), getfield(), getiofile(), io_readline(), luaB_assert(), luaB_print(), luaB_setmetatable(), luaL_argerror(), luaL_checkstack(), luaL_checkversion_(), luaL_len(), luaL_prepbuffsize(), match(), matchbalance(), math_random(), opencheck(), os_tmpname(), push_onecapture(), scanformat(), start_capture(), str_byte(), str_dump(), str_format(), str_rep(), tinsert(), tofile(), and unpack().
LUALIB_API int luaL_execresult (lua_State * L, int stat)
Definition at line 247 of file lauxlib.c.
References inspectstat, lua_pushboolean(), lua_pushinteger(), lua_pushnil(), lua_pushstring(), and luaL_fileresult().
Referenced by io_pclose(), and os_execute().
LUALIB_API int luaL_fileresult (lua_State * L, int stat, const char * fname)
Definition at line 207 of file lauxlib.c.
References lua_pushboolean(), lua_pushfstring(), lua_pushinteger(), lua_pushnil(), and lua_pushstring().
Referenced by f_flush(), f_seek(), f_setvbuf(), g_read(), g_write(), io_fclose(), io_flush(), io_open(), io_popen(), io_tmpfile(), luaL_execresult(), os_remove(), and os_rename().
LUALIB_API int luaL_getmetafield (lua_State * L, int obj, const char * event)
Definition at line 699 of file lauxlib.c.
References lua_getmetatable(), lua_isnil, lua_pop, lua_pushstring(), lua_rawget(), and lua_remove().
Referenced by luaB_getmetatable(), luaB_setmetatable(), luaL_callmeta(), and pairsmeta().
LUALIB_API int luaL_getsubtable (lua_State * L, int idx, const char * fname)
Definition at line 866 of file lauxlib.c.
References lua_absindex(), lua_getfield(), lua_istable, lua_newtable, lua_pop, lua_pushvalue(), and lua_setfield().
Referenced by luaL_openlibs(), luaL_requiref(), and luaopen_package().
LUALIB_API const char* luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 902 of file lauxlib.c.
References lua_tostring, luaL_addlstring(), luaL_addstring(), luaL_buffinit(), and luaL_pushresult().
Referenced by loadfunc(), searchpath(), and setpath().
LUALIB_API int luaL_len (lua_State * L, int idx)
Definition at line 725 of file lauxlib.c.
References lua_len(), lua_pop, lua_tointegerx(), and luaL_error().
Referenced by gctm(), ll_addtoclib(), tconcat(), and unpack().
LUALIB_API int luaL_loadbufferx (lua_State * L, const char * buff, size_t size, const char * name, const char * mode)
Definition at line 682 of file lauxlib.c.
References getS(), lua_load(), LoadS::s, and LoadS::size.
Referenced by luaB_load().
LUALIB_API int luaL_loadfilex (lua_State * L, const char * filename, const char * mode)
Definition at line 630 of file lauxlib.c.
References LoadF::buff, errfile(), LoadF::f, getF(), lua_gettop(), lua_load(), lua_pushfstring(), lua_pushliteral, lua_remove(), lua_settop(), LUA_SIGNATURE, lua_tostring, LoadF::n, and skipcomment().
Referenced by luaB_loadfile().
LUALIB_API int luaL_loadstring (lua_State * L, const char * s)
Definition at line 691 of file lauxlib.c.
References luaL_loadbuffer.
Referenced by KenshoLuaWrapper::evaluate.
LUALIB_API int luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 272 of file lauxlib.c.
References lua_isnil, lua_newtable, lua_pop, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), and luaL_getmetatable.
Referenced by createmeta().
LUALIB_API lua_State* luaL_newstate (void)
Definition at line 937 of file lauxlib.c.
References l_alloc(), lua_atpanic(), lua_newstate(), and panic().
Referenced by KenshoLuaWrapper::evaluate.
LUALIB_API lua_Integer luaL_optinteger (lua_State * L, int narg, lua_Integer def)
Definition at line 407 of file lauxlib.c.
References luaL_checkinteger(), and luaL_opt.
Referenced by f_setvbuf(), str_byte(), str_find_aux(), str_gsub(), and str_sub().
LUALIB_API const char* luaL_optlstring (lua_State * L, int narg, const char * def, size_t * len)
Definition at line 364 of file lauxlib.c.
References lua_isnoneornil, and luaL_checklstring().
Referenced by str_rep(), and tconcat().
LUALIB_API lua_Number luaL_optnumber (lua_State * L, int narg, lua_Number def)
Definition at line 384 of file lauxlib.c.
References luaL_checknumber(), and luaL_opt.
Referenced by f_seek(), and os_difftime().
LUALIB_API lua_Unsigned luaL_optunsigned (lua_State * L, int narg, lua_Unsigned def)
Definition at line 413 of file lauxlib.c.
References luaL_checkunsigned(), and luaL_opt.
LUALIB_API char* luaL_prepbuffsize (luaL_Buffer * B, size_t sz)
Definition at line 437 of file lauxlib.c.
References luaL_Buffer::b, buffonstack, luaL_Buffer::L, lua_newuserdata(), lua_remove(), luaL_error(), luaL_Buffer::n, and luaL_Buffer::size.
Referenced by luaL_addlstring(), luaL_buffinitsize(), read_all(), read_chars(), and str_format().
LUALIB_API void luaL_pushresult (luaL_Buffer * B)
Definition at line 471 of file lauxlib.c.
References luaL_Buffer::b, buffonstack, luaL_Buffer::L, lua_pushlstring(), lua_remove(), and luaL_Buffer::n.
Referenced by findloader(), luaL_gsub(), luaL_pushresultsize(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), and tconcat().
LUALIB_API void luaL_pushresultsize (luaL_Buffer * B, size_t sz)
Definition at line 479 of file lauxlib.c.
References luaL_addsize, and luaL_pushresult().
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
LUALIB_API int luaL_ref (lua_State * L, int t)
Definition at line 522 of file lauxlib.c.
References freelist, lua_absindex(), lua_isnil, lua_pop, lua_rawgeti(), lua_rawlen(), lua_rawseti(), LUA_REFNIL, and lua_tointeger.
LUALIB_API void luaL_requiref (lua_State * L, const char * modname, lua_CFunction openf, int glb)
Definition at line 886 of file lauxlib.c.
References lua_call, lua_pop, lua_pushcfunction, lua_pushstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_setglobal(), and luaL_getsubtable().
Referenced by luaL_openlibs().
LUALIB_API void luaL_setfuncs (lua_State * L, const luaL_Reg * l, int nup)
Definition at line 848 of file lauxlib.c.
References luaL_Reg::func, lua_pop, lua_pushcclosure(), lua_pushvalue(), lua_setfield(), luaL_checkstack(), luaL_checkversion, and luaL_Reg::name.
Referenced by createmeta(), luaopen_base(), and luaopen_package().
LUALIB_API void luaL_setmetatable (lua_State * L, const char * tname)
Definition at line 284 of file lauxlib.c.
References lua_setmetatable(), and luaL_getmetatable.
Referenced by newprefile().
LUALIB_API void* luaL_testudata (lua_State * L, int ud, const char * tname)
Definition at line 290 of file lauxlib.c.
References lua_getmetatable(), lua_pop, lua_rawequal(), lua_touserdata(), and luaL_getmetatable.
Referenced by io_type(), and luaL_checkudata().
LUALIB_API const char* luaL_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 737 of file lauxlib.c.
References lua_pushfstring(), lua_pushliteral, lua_pushstring(), lua_pushvalue(), LUA_TBOOLEAN, LUA_TNIL, LUA_TNUMBER, lua_toboolean(), lua_tolstring(), lua_topointer(), LUA_TSTRING, lua_type(), luaL_callmeta(), and luaL_typename.
Referenced by luaB_tostring(), and str_format().
LUALIB_API void luaL_traceback (lua_State * L, lua_State * L1, const char * msg, int level)
Definition at line 116 of file lauxlib.c.
References countlevels(), lua_Debug::currentline, lua_Debug::istailcall, LEVELS1, LEVELS2, lua_concat(), lua_getinfo(), lua_getstack(), lua_gettop(), lua_pushfstring(), lua_pushliteral, pushfuncname(), and lua_Debug::short_src.
Referenced by db_traceback().
LUALIB_API void luaL_unref (lua_State * L, int t, int ref)
Definition at line 543 of file lauxlib.c.
References freelist, lua_absindex(), lua_pushinteger(), lua_rawgeti(), and lua_rawseti().
LUALIB_API void luaL_where (lua_State * L, int level)
Definition at line 183 of file lauxlib.c.
References lua_Debug::currentline, lua_getinfo(), lua_getstack(), lua_pushfstring(), lua_pushliteral, and lua_Debug::short_src.
Referenced by luaB_auxwrap(), luaB_error(), and luaL_error().
static int panic (lua_State * L) static
Definition at line 930 of file lauxlib.c.
References lua_tostring, and luai_writestringerror.
Referenced by luaD_throw(), and luaL_newstate().
static void pushfuncname (lua_State * L, lua_Debug * ar) static
Definition at line 83 of file lauxlib.c.
References lua_Debug::linedefined, lua_pushfstring(), lua_pushliteral, LUA_QS, lua_remove(), lua_tostring, lua_Debug::name, lua_Debug::namewhat, pushglobalfuncname(), lua_Debug::short_src, and lua_Debug::what.
Referenced by luaL_traceback().
static int pushglobalfuncname (lua_State * L, lua_Debug * ar) static
Definition at line 67 of file lauxlib.c.
References findfield(), lua_copy(), lua_getinfo(), lua_gettop(), lua_pop, lua_pushglobaltable, and lua_settop().
Referenced by luaL_argerror(), and pushfuncname().
static int skipBOM (LoadF * lf) static
Definition at line 596 of file lauxlib.c.
References LoadF::buff, LoadF::f, and LoadF::n.
Referenced by skipcomment().
static int skipcomment (LoadF * lf, int * cp) static
Definition at line 617 of file lauxlib.c.
References LoadF::f, and skipBOM().
Referenced by luaL_loadfilex().
static void tag_error (lua_State * L, int narg, int tag) static
Definition at line 178 of file lauxlib.c.
References lua_typename(), and typeerror().
Referenced by luaL_checkinteger(), luaL_checklstring(), luaL_checknumber(), luaL_checktype(), and luaL_checkunsigned().
static int typeerror (lua_State * L, int narg, const char * tname) static
Definition at line 171 of file lauxlib.c.
References lua_pushfstring(), luaL_argerror(), and luaL_typename.
Referenced by luaL_checkudata(), and tag_error().