Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/liolib.c File Reference
liolib.c File Reference
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define _LARGEFILE_SOURCE 1
#define _FILE_OFFSET_BITS 64
#define liolib_c
#define LUA_LIB
#define lua_checkmode(mode)
#define lua_popen(L, c, m)
#define lua_pclose(L, file) ((void)((void)L, file), -1)
#define l_fseek(f, o, w) fseek(f,o,w)
#define l_ftell(f) ftell(f)
#define l_seeknum long
#define IO_PREFIX "_IO_"
#define IO_INPUT (IO_PREFIX "input")
#define IO_OUTPUT (IO_PREFIX "output")
#define tolstream(L) ((LStream *)luaL_checkudata(L, 1, LUA_FILEHANDLE))
#define isclosed(p) ((p)->closef == NULL)
#define MAX_SIZE_T (~(size_t)0)
Typedefs
typedef luaL_Stream LStream
Functions
static int io_type (lua_State *L)
static int f_tostring (lua_State *L)
static FILE * tofile (lua_State *L)
static LStream * newprefile (lua_State *L)
static int aux_close (lua_State *L)
static int io_close (lua_State *L)
static int f_gc (lua_State *L)
static int io_fclose (lua_State *L)
static LStream * newfile (lua_State *L)
static void opencheck (lua_State *L, const char *fname, const char *mode)
static int io_open (lua_State *L)
static int io_pclose (lua_State *L)
static int io_popen (lua_State *L)
static int io_tmpfile (lua_State *L)
static FILE * getiofile (lua_State *L, const char *findex)
static int g_iofile (lua_State *L, const char *f, const char *mode)
static int io_input (lua_State *L)
static int io_output (lua_State *L)
static int io_readline (lua_State *L)
static void aux_lines (lua_State *L, int toclose)
static int f_lines (lua_State *L)
static int io_lines (lua_State *L)
static int read_number (lua_State *L, FILE *f)
static int test_eof (lua_State *L, FILE *f)
static int read_line (lua_State *L, FILE *f, int chop)
static void read_all (lua_State *L, FILE *f)
static int read_chars (lua_State *L, FILE *f, size_t n)
static int g_read (lua_State *L, FILE *f, int first)
static int io_read (lua_State *L)
static int f_read (lua_State *L)
static int g_write (lua_State *L, FILE *f, int arg)
static int io_write (lua_State *L)
static int f_write (lua_State *L)
static int f_seek (lua_State *L)
static int f_setvbuf (lua_State *L)
static int io_flush (lua_State *L)
static int f_flush (lua_State *L)
static void createmeta (lua_State *L)
static int io_noclose (lua_State *L)
static void createstdfile (lua_State *L, FILE *f, const char *k, const char *fname)
LUAMOD_API int luaopen_io (lua_State *L)
Variables
static const luaL_Reg iolib []
static const luaL_Reg flib []
Macro Definition Documentation
#define _FILE_OFFSET_BITS 64
Definition at line 14 of file liolib.c.
#define _LARGEFILE_SOURCE 1
Definition at line 13 of file liolib.c.
#define IO_INPUT (IO_PREFIX "input")
Definition at line 118 of file liolib.c.
Referenced by io_input(), io_lines(), io_read(), and luaopen_io().
#define IO_OUTPUT (IO_PREFIX "output")
Definition at line 119 of file liolib.c.
Referenced by io_close(), io_flush(), io_output(), io_write(), and luaopen_io().
#define IO_PREFIX "_IO_"
Definition at line 117 of file liolib.c.
Referenced by getiofile().
#define isclosed (p) ((p)->closef == NULL)
Definition at line 127 of file liolib.c.
Referenced by f_gc(), f_tostring(), getiofile(), io_readline(), io_type(), and tofile().
#define l_fseek (f, o, w) fseek(f,o,w)
Definition at line 109 of file liolib.c.
Referenced by f_seek().
#define l_ftell (f) ftell(f)
Definition at line 110 of file liolib.c.
Referenced by f_seek().
#define l_seeknum long
Definition at line 111 of file liolib.c.
Referenced by f_seek().
#define liolib_c
Definition at line 23 of file liolib.c.
#define lua_checkmode (mode)
Value:
(*mode != '\0' && strchr("rwa", *(mode++)) != NULL &&   \
        (*mode != '+' || ++mode) &&  /* skip if char is '+' */  \
        (*mode != 'b' || ++mode) &&  /* skip if char is 'b' */  \
        (*mode == '\0'))
Definition at line 39 of file liolib.c.
Referenced by io_open().
#define LUA_LIB
Definition at line 24 of file liolib.c.
#define lua_pclose (L, file) ((void)((void)L, file), -1)
Definition at line 71 of file liolib.c.
Referenced by io_pclose().
#define lua_popen (L, c, m)
Value:
((void)((void)c, m),  \
                luaL_error(L, LUA_QL("popen") " not supported"), (FILE*)0)
Definition at line 69 of file liolib.c.
Referenced by io_popen().
#define MAX_SIZE_T (~(size_t)0)
Definition at line 393 of file liolib.c.
Referenced by read_all().
#define tolstream (L) ((LStream *)luaL_checkudata(L, 1, LUA_FILEHANDLE))
Definition at line 125 of file liolib.c.
Referenced by aux_close(), f_gc(), f_tostring(), io_fclose(), io_noclose(), io_pclose(), and tofile().
Typedef Documentation
typedef luaL_Stream LStream
Definition at line 122 of file liolib.c.
Function Documentation
static int aux_close (lua_State * L) static
Definition at line 176 of file liolib.c.
References luaL_Stream::closef, and tolstream.
Referenced by f_gc(), io_close(), and io_readline().
static void aux_lines (lua_State * L, int toclose) static
Definition at line 303 of file liolib.c.
References io_readline(), lua_gettop(), LUA_MINSTACK, lua_pushboolean(), lua_pushcclosure(), lua_pushinteger(), lua_pushvalue(), and luaL_argcheck.
Referenced by f_lines(), and io_lines().
static void createmeta (lua_State * L) static
Definition at line 623 of file liolib.c.
References LUA_FILEHANDLE, lua_pop, lua_pushvalue(), lua_setfield(), luaL_newmetatable(), and luaL_setfuncs().
Referenced by luaopen_io().
static void createstdfile (lua_State * L, FILE * f, const char * k, const char * fname) static
Definition at line 644 of file liolib.c.
References luaL_Stream::closef, luaL_Stream::f, io_noclose(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), and newprefile().
Referenced by luaopen_io().
static int f_flush (lua_State * L) static
Definition at line 582 of file liolib.c.
References luaL_fileresult(), and tofile().
static int f_gc (lua_State * L) static
Definition at line 192 of file liolib.c.
References aux_close(), luaL_Stream::f, isclosed, and tolstream.
static int f_lines (lua_State * L) static
Definition at line 316 of file liolib.c.
References aux_lines(), and tofile().
static int f_read (lua_State * L) static
Definition at line 479 of file liolib.c.
References g_read(), and tofile().
static int f_seek (lua_State * L) static
Definition at line 546 of file liolib.c.
References l_fseek, l_ftell, l_seeknum, lua_pushnumber(), luaL_argcheck, luaL_checkoption(), luaL_fileresult(), luaL_optnumber(), and tofile().
static int f_setvbuf (lua_State * L) static
Definition at line 565 of file liolib.c.
References LUAL_BUFFERSIZE, luaL_checkoption(), luaL_fileresult(), luaL_optinteger(), and tofile().
static int f_tostring (lua_State * L) static
Definition at line 144 of file liolib.c.
References luaL_Stream::f, isclosed, lua_pushfstring(), lua_pushliteral, and tolstream.
static int f_write (lua_State * L) static
Definition at line 539 of file liolib.c.
References g_write(), lua_pushvalue(), and tofile().
static int g_iofile (lua_State * L, const char * f, const char * mode) static
Definition at line 273 of file liolib.c.
References lua_getfield(), lua_isnoneornil, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_tostring, opencheck(), and tofile().
Referenced by io_input(), and io_output().
static int g_read (lua_State * L, FILE * f, int first) static
Definition at line 424 of file liolib.c.
References lua_gettop(), LUA_MINSTACK, lua_pop, lua_pushnil(), LUA_TNUMBER, lua_tointeger, lua_tostring, lua_type(), luaL_argcheck, luaL_argerror(), luaL_checkstack(), luaL_fileresult(), read_all(), read_chars(), read_line(), read_number(), and test_eof().
Referenced by f_read(), io_read(), and io_readline().
static int g_write (lua_State * L, FILE * f, int arg) static
Definition at line 514 of file liolib.c.
References lua_gettop(), LUA_NUMBER_FMT, LUA_TNUMBER, lua_tonumber, lua_type(), luaL_checklstring(), and luaL_fileresult().
Referenced by f_write(), and io_write().
static FILE* getiofile (lua_State * L, const char * findex) static
Definition at line 263 of file liolib.c.
References luaL_Stream::f, IO_PREFIX, isclosed, lua_getfield(), LUA_REGISTRYINDEX, lua_touserdata(), and luaL_error().
Referenced by io_flush(), io_read(), and io_write().
static int io_close (lua_State * L) static
Definition at line 184 of file liolib.c.
References aux_close(), IO_OUTPUT, lua_getfield(), lua_isnone, LUA_REGISTRYINDEX, and tofile().
static int io_fclose (lua_State * L) static
Definition at line 203 of file liolib.c.
References luaL_Stream::f, luaL_fileresult(), and tolstream.
Referenced by newfile().
static int io_flush (lua_State * L) static
Definition at line 577 of file liolib.c.
References getiofile(), IO_OUTPUT, and luaL_fileresult().
static int io_input (lua_State * L) static
Definition at line 290 of file liolib.c.
References g_iofile(), and IO_INPUT.
static int io_lines (lua_State * L) static
Definition at line 323 of file liolib.c.
References aux_lines(), IO_INPUT, lua_getfield(), lua_isnil, lua_isnone, lua_pushnil(), LUA_REGISTRYINDEX, lua_replace(), luaL_checkstring, opencheck(), and tofile().
static int io_noclose (lua_State * L) static
Definition at line 635 of file liolib.c.
References luaL_Stream::closef, lua_pushliteral, lua_pushnil(), and tolstream.
Referenced by createstdfile().
static int io_open (lua_State * L) static
Definition at line 226 of file liolib.c.
References luaL_Stream::f, lua_checkmode, luaL_argcheck, luaL_checkstring, luaL_fileresult(), luaL_optstring, and newfile().
static int io_output (lua_State * L) static
Definition at line 295 of file liolib.c.
References g_iofile(), and IO_OUTPUT.
static int io_pclose (lua_State * L) static
Definition at line 240 of file liolib.c.
References luaL_Stream::f, lua_pclose, luaL_execresult(), and tolstream.
Referenced by io_popen().
static int io_popen (lua_State * L) static
Definition at line 246 of file liolib.c.
References luaL_Stream::closef, luaL_Stream::f, io_pclose(), lua_popen, luaL_checkstring, luaL_fileresult(), luaL_optstring, and newprefile().
static int io_read (lua_State * L) static
Definition at line 474 of file liolib.c.
References g_read(), getiofile(), and IO_INPUT.
static int io_readline (lua_State * L) static
Definition at line 484 of file liolib.c.
References aux_close(), luaL_Stream::f, g_read(), isclosed, lua_assert, lua_isnil, lua_pushvalue(), lua_settop(), lua_toboolean(), lua_tointeger, lua_tostring, lua_touserdata(), lua_upvalueindex, and luaL_error().
Referenced by aux_lines().
static int io_tmpfile (lua_State * L) static
Definition at line 256 of file liolib.c.
References luaL_Stream::f, luaL_fileresult(), and newfile().
static int io_type (lua_State * L) static
Definition at line 130 of file liolib.c.
References isclosed, LUA_FILEHANDLE, lua_pushliteral, lua_pushnil(), luaL_checkany(), and luaL_testudata().
static int io_write (lua_State * L) static
Definition at line 534 of file liolib.c.
References g_write(), getiofile(), and IO_OUTPUT.
LUAMOD_API int luaopen_io (lua_State * L)
Definition at line 657 of file liolib.c.
References createmeta(), createstdfile(), IO_INPUT, IO_OUTPUT, and luaL_newlib.
static LStream* newfile (lua_State * L) static
Definition at line 210 of file liolib.c.
References luaL_Stream::closef, luaL_Stream::f, io_fclose(), and newprefile().
Referenced by io_open(), io_tmpfile(), and opencheck().
static LStream* newprefile (lua_State * L) static
Definition at line 168 of file liolib.c.
References luaL_Stream::closef, LUA_FILEHANDLE, lua_newuserdata(), and luaL_setmetatable().
Referenced by createstdfile(), io_popen(), and newfile().
static void opencheck (lua_State * L, const char * fname, const char * mode) static
Definition at line 218 of file liolib.c.
References luaL_Stream::f, LUA_QS, luaL_error(), and newfile().
Referenced by g_iofile(), and io_lines().
static void read_all (lua_State * L, FILE * f) static
Definition at line 395 of file liolib.c.
References luaL_addsize, LUAL_BUFFERSIZE, luaL_buffinit(), luaL_prepbuffsize(), luaL_pushresult(), and MAX_SIZE_T.
Referenced by g_read().
static int read_chars (lua_State * L, FILE * f, size_t n) static
Definition at line 411 of file liolib.c.
References luaL_addsize, luaL_buffinit(), luaL_prepbuffsize(), and luaL_pushresult().
Referenced by g_read().
static int read_line (lua_State * L, FILE * f, int chop) static
Definition at line 371 of file liolib.c.
References lua_rawlen(), luaL_addsize, LUAL_BUFFERSIZE, luaL_buffinit(), luaL_prepbuffer, and luaL_pushresult().
Referenced by g_read().
static int read_number (lua_State * L, FILE * f) static
Definition at line 350 of file liolib.c.
References LUA_NUMBER_SCAN, lua_pushnil(), and lua_pushnumber().
Referenced by g_read().
static int test_eof (lua_State * L, FILE * f) static
Definition at line 363 of file liolib.c.
References lua_pushlstring().
Referenced by g_read().
static FILE* tofile (lua_State * L) static
Definition at line 154 of file liolib.c.
References luaL_Stream::f, isclosed, lua_assert, luaL_error(), and tolstream.
Referenced by f_flush(), f_lines(), f_read(), f_seek(), f_setvbuf(), f_write(), g_iofile(), io_close(), and io_lines().
Variable Documentation
const luaL_Reg flib[] static
Initial value:
= {
  {"close", io_close},
  {"flush", f_flush},
  {"lines", f_lines},
  {"read", f_read},
  {"seek", f_seek},
  {"setvbuf", f_setvbuf},
  {"write", f_write},
  {"__gc", f_gc},
  {"__tostring", f_tostring},
  {NULL, NULL}
}
Definition at line 609 of file liolib.c.
const luaL_Reg iolib[] static
Initial value:
= {
  {"close", io_close},
  {"flush", io_flush},
  {"input", io_input},
  {"lines", io_lines},
  {"open", io_open},
  {"output", io_output},
  {"popen", io_popen},
  {"read", io_read},
  {"tmpfile", io_tmpfile},
  {"type", io_type},
  {"write", io_write},
  {NULL, NULL}
}
Definition at line 590 of file liolib.c.