Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lapi.c File Reference
lapi.c File Reference
#include <stdarg.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lundump.h"
#include "lvm.h"
Classes
struct CallS
Macros
#define lapi_c
#define LUA_CORE
#define NONVALIDVALUE cast(TValue *, luaO_nilobject)
#define isvalid(o) ((o) != luaO_nilobject)
#define ispseudo(i) ((i) <= LUA_REGISTRYINDEX)
#define isstackindex(i, o) (isvalid(o) && !ispseudo(i))
#define api_checkvalidindex(L, o) api_check(L, isvalid(o), "invalid index")
#define api_checkstackindex(L, i, o) api_check(L, isstackindex(i, o), "index not in the stack")
#define checkresults(L, na, nr)
Functions
static TValue * index2addr (lua_State *L, int idx)
static void growstack (lua_State *L, void *ud)
LUA_API int lua_checkstack (lua_State *L, int size)
LUA_API void lua_xmove (lua_State *from, lua_State *to, int n)
LUA_API lua_CFunction lua_atpanic (lua_State *L, lua_CFunction panicf)
LUA_API const lua_Number * lua_version (lua_State *L)
LUA_API int lua_absindex (lua_State *L, int idx)
LUA_API int lua_gettop (lua_State *L)
LUA_API void lua_settop (lua_State *L, int idx)
LUA_API void lua_remove (lua_State *L, int idx)
LUA_API void lua_insert (lua_State *L, int idx)
static void moveto (lua_State *L, TValue *fr, int idx)
LUA_API void lua_replace (lua_State *L, int idx)
LUA_API void lua_copy (lua_State *L, int fromidx, int toidx)
LUA_API void lua_pushvalue (lua_State *L, int idx)
LUA_API int lua_type (lua_State *L, int idx)
LUA_API const char * lua_typename (lua_State *L, int t)
LUA_API int lua_iscfunction (lua_State *L, int idx)
LUA_API int lua_isnumber (lua_State *L, int idx)
LUA_API int lua_isstring (lua_State *L, int idx)
LUA_API int lua_isuserdata (lua_State *L, int idx)
LUA_API int lua_rawequal (lua_State *L, int index1, int index2)
LUA_API void lua_arith (lua_State *L, int op)
LUA_API int lua_compare (lua_State *L, int index1, int index2, int op)
LUA_API lua_Number lua_tonumberx (lua_State *L, int idx, int *isnum)
LUA_API lua_Integer lua_tointegerx (lua_State *L, int idx, int *isnum)
LUA_API lua_Unsigned lua_tounsignedx (lua_State *L, int idx, int *isnum)
LUA_API int lua_toboolean (lua_State *L, int idx)
LUA_API const char * lua_tolstring (lua_State *L, int idx, size_t *len)
LUA_API size_t lua_rawlen (lua_State *L, int idx)
LUA_API lua_CFunction lua_tocfunction (lua_State *L, int idx)
LUA_API void * lua_touserdata (lua_State *L, int idx)
LUA_API lua_State * lua_tothread (lua_State *L, int idx)
LUA_API const void * lua_topointer (lua_State *L, int idx)
LUA_API void lua_pushnil (lua_State *L)
LUA_API void lua_pushnumber (lua_State *L, lua_Number n)
LUA_API void lua_pushinteger (lua_State *L, lua_Integer n)
LUA_API void lua_pushunsigned (lua_State *L, lua_Unsigned u)
LUA_API const char * lua_pushlstring (lua_State *L, const char *s, size_t len)
LUA_API const char * lua_pushstring (lua_State *L, const char *s)
LUA_API const char * lua_pushvfstring (lua_State *L, const char *fmt, va_list argp)
LUA_API const char * lua_pushfstring (lua_State *L, const char *fmt,...)
LUA_API void lua_pushcclosure (lua_State *L, lua_CFunction fn, int n)
LUA_API void lua_pushboolean (lua_State *L, int b)
LUA_API void lua_pushlightuserdata (lua_State *L, void *p)
LUA_API int lua_pushthread (lua_State *L)
LUA_API void lua_getglobal (lua_State *L, const char *var)
LUA_API void lua_gettable (lua_State *L, int idx)
LUA_API void lua_getfield (lua_State *L, int idx, const char *k)
LUA_API void lua_rawget (lua_State *L, int idx)
LUA_API void lua_rawgeti (lua_State *L, int idx, int n)
LUA_API void lua_rawgetp (lua_State *L, int idx, const void *p)
LUA_API void lua_createtable (lua_State *L, int narray, int nrec)
LUA_API int lua_getmetatable (lua_State *L, int objindex)
LUA_API void lua_getuservalue (lua_State *L, int idx)
LUA_API void lua_setglobal (lua_State *L, const char *var)
LUA_API void lua_settable (lua_State *L, int idx)
LUA_API void lua_setfield (lua_State *L, int idx, const char *k)
LUA_API void lua_rawset (lua_State *L, int idx)
LUA_API void lua_rawseti (lua_State *L, int idx, int n)
LUA_API void lua_rawsetp (lua_State *L, int idx, const void *p)
LUA_API int lua_setmetatable (lua_State *L, int objindex)
LUA_API void lua_setuservalue (lua_State *L, int idx)
LUA_API int lua_getctx (lua_State *L, int *ctx)
LUA_API void lua_callk (lua_State *L, int nargs, int nresults, int ctx, lua_CFunction k)
static void f_call (lua_State *L, void *ud)
LUA_API int lua_pcallk (lua_State *L, int nargs, int nresults, int errfunc, int ctx, lua_CFunction k)
LUA_API int lua_load (lua_State *L, lua_Reader reader, void *data, const char *chunkname, const char *mode)
LUA_API int lua_dump (lua_State *L, lua_Writer writer, void *data)
LUA_API int lua_status (lua_State *L)
LUA_API int lua_gc (lua_State *L, int what, int data)
LUA_API int lua_error (lua_State *L)
LUA_API int lua_next (lua_State *L, int idx)
LUA_API void lua_concat (lua_State *L, int n)
LUA_API void lua_len (lua_State *L, int idx)
LUA_API lua_Alloc lua_getallocf (lua_State *L, void **ud)
LUA_API void lua_setallocf (lua_State *L, lua_Alloc f, void *ud)
LUA_API void * lua_newuserdata (lua_State *L, size_t size)
static const char * aux_upvalue (StkId fi, int n, TValue **val, GCObject **owner)
LUA_API const char * lua_getupvalue (lua_State *L, int funcindex, int n)
LUA_API const char * lua_setupvalue (lua_State *L, int funcindex, int n)
static UpVal ** getupvalref (lua_State *L, int fidx, int n, LClosure **pf)
LUA_API void * lua_upvalueid (lua_State *L, int fidx, int n)
LUA_API void lua_upvaluejoin (lua_State *L, int fidx1, int n1, int fidx2, int n2)
Variables
const char lua_ident []
Macro Definition Documentation
#define api_checkstackindex (L, i, o) api_check(L, isstackindex(i, o), "index not in the stack")
Definition at line 51 of file lapi.c.
Referenced by lua_insert(), lua_pcallk(), and lua_remove().
#define api_checkvalidindex (L, o) api_check(L, isvalid(o), "invalid index")
Definition at line 49 of file lapi.c.
Referenced by moveto().
#define checkresults (L, na, nr)
Value:
api_check(L, (nr) == LUA_MULTRET || (L->ci->top - L->top >= (nr) - (na)), \
        "results from function overflow current stack size")
Definition at line 875 of file lapi.c.
Referenced by lua_callk(), and lua_pcallk().
#define ispseudo (i) ((i) <= LUA_REGISTRYINDEX)
Definition at line 44 of file lapi.c.
Referenced by index2addr(), and lua_absindex().
#define isstackindex (i, o) (isvalid(o) && !ispseudo(i))
Definition at line 47 of file lapi.c.
#define isvalid (o) ((o) != luaO_nilobject)
Definition at line 41 of file lapi.c.
Referenced by lua_compare(), lua_rawequal(), and lua_type().
#define lapi_c
Definition at line 11 of file lapi.c.
#define LUA_CORE
Definition at line 12 of file lapi.c.
#define NONVALIDVALUE cast(TValue *, luaO_nilobject)
Definition at line 38 of file lapi.c.
Referenced by index2addr().
Function Documentation
static const char* aux_upvalue (StkId fi, int n, TValue ** val, GCObject ** owner) static
Definition at line 1188 of file lapi.c.
References clCvalue, clLvalue, getstr, LUA_TCCL, LUA_TLCL, Upvaldesc::name, obj2gco, LClosure::p, ttype, LClosure::upvals, CClosure::upvalue, Proto::upvalues, and UpVal::v.
Referenced by lua_getupvalue(), and lua_setupvalue().
static void f_call (lua_State * L, void * ud) static
Definition at line 921 of file lapi.c.
References cast, CallS::func, luaD_call(), and CallS::nresults.
Referenced by lua_pcallk().
static UpVal** getupvalref (lua_State * L, int fidx, int n, LClosure ** pf) static
Definition at line 1246 of file lapi.c.
References api_check, clLvalue, index2addr(), ttisLclosure, and LClosure::upvals.
Referenced by lua_upvalueid(), and lua_upvaluejoin().
static void growstack (lua_State * L, void * ud) static
Definition at line 86 of file lapi.c.
References luaD_growstack().
Referenced by lua_checkstack().
static TValue* index2addr (lua_State * L, int idx) static
Definition at line 55 of file lapi.c.
References api_check, lua_State::ci, clCvalue, CallInfo::func, G, ispseudo, LUA_REGISTRYINDEX, MAXUPVAL, NONVALIDVALUE, lua_State::top, ttislcf, and CClosure::upvalue.
Referenced by getupvalref(), lua_compare(), lua_copy(), lua_getfield(), lua_getmetatable(), lua_gettable(), lua_getupvalue(), lua_getuservalue(), lua_insert(), lua_iscfunction(), lua_isnumber(), lua_isuserdata(), lua_len(), lua_next(), lua_pcallk(), lua_pushvalue(), lua_rawequal(), lua_rawget(), lua_rawgeti(), lua_rawgetp(), lua_rawlen(), lua_rawset(), lua_rawseti(), lua_rawsetp(), lua_remove(), lua_setfield(), lua_setmetatable(), lua_settable(), lua_setupvalue(), lua_setuservalue(), lua_toboolean(), lua_tocfunction(), lua_tointegerx(), lua_tolstring(), lua_tonumberx(), lua_topointer(), lua_tothread(), lua_tounsignedx(), lua_touserdata(), lua_type(), lua_upvalueid(), and moveto().
LUA_API int lua_absindex (lua_State * L, int idx)
Definition at line 153 of file lapi.c.
References cast_int, lua_State::ci, CallInfo::func, ispseudo, and lua_State::top.
Referenced by luaL_callmeta(), luaL_getsubtable(), luaL_ref(), and luaL_unref().
LUA_API void lua_arith (lua_State * L, int op)
Definition at line 293 of file lapi.c.
References api_checknelems, cast, lua_lock, LUA_OPADD, LUA_OPUNM, lua_unlock, luaO_arith(), luaV_arith(), nvalue, setnvalue, setobjs2s, TM_ADD, lua_State::top, and ttisnumber.
LUA_API lua_CFunction lua_atpanic (lua_State * L, lua_CFunction panicf)
Definition at line 127 of file lapi.c.
References G, lua_lock, and lua_unlock.
Referenced by luaL_newstate().
LUA_API void lua_callk (lua_State * L, int nargs, int nresults, int ctx, lua_CFunction k)
Definition at line 889 of file lapi.c.
References adjustresults, api_check, api_checknelems, CallInfo::c, checkresults, lua_State::ci, isLua, lua_lock, LUA_OK, lua_unlock, luaD_call(), lua_State::nny, lua_State::status, lua_State::top, and CallInfo::u.
Referenced by luaB_dofile().
LUA_API int lua_checkstack (lua_State * L, int size)
Definition at line 92 of file lapi.c.
References cast_int, lua_State::ci, EXTRA_STACK, growstack(), lua_lock, LUA_OK, lua_unlock, luaD_rawrunprotected(), LUAI_MAXSTACK, lua_State::stack, lua_State::stack_last, CallInfo::top, and lua_State::top.
Referenced by auxresume(), finishpcall(), luaL_checkstack(), and unpack().
LUA_API int lua_compare (lua_State * L, int index1, int index2, int op)
Definition at line 316 of file lapi.c.
References api_check, equalobj, index2addr(), isvalid, lua_lock, LUA_OPEQ, LUA_OPLE, LUA_OPLT, lua_unlock, luaV_lessequal(), and luaV_lessthan().
Referenced by sort_comp().
LUA_API void lua_concat (lua_State * L, int n)
Definition at line 1131 of file lapi.c.
References api_checknelems, api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaS_newlstr(), luaV_concat(), setsvalue2s, and lua_State::top.
Referenced by findfield(), luaB_auxwrap(), luaB_error(), luaL_error(), and luaL_traceback().
LUA_API void lua_copy (lua_State * L, int fromidx, int toidx)
Definition at line 226 of file lapi.c.
References index2addr(), lua_lock, lua_unlock, and moveto().
Referenced by luaB_xpcall(), and pushglobalfuncname().
LUA_API void lua_createtable (lua_State * L, int narray, int nrec)
Definition at line 673 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaH_new(), luaH_resize(), sethvalue, and lua_State::top.
Referenced by createmetatable(), createsearcherstable(), db_getinfo(), luaopen_package(), os_date(), pack(), and pushValue().
LUA_API int lua_dump (lua_State * L, lua_Writer writer, void * data)
Definition at line 997 of file lapi.c.
References api_checknelems, getproto, isLfunction, lua_lock, lua_unlock, luaU_dump(), and lua_State::top.
Referenced by str_dump().
LUA_API int lua_error (lua_State * L)
Definition at line 1105 of file lapi.c.
References api_checknelems, lua_lock, and luaG_errormsg().
Referenced by luaB_auxwrap(), luaB_dofile(), luaB_error(), and luaL_error().
LUA_API int lua_gc (lua_State * L, int what, int data)
Definition at line 1021 of file lapi.c.
References cast, cast_int, G, global_State::GCdebt, global_State::GCestimate, global_State::gckind, global_State::gcmajorinc, global_State::gcpause, global_State::gcrunning, GCSpause, global_State::gcstate, global_State::gcstepmul, GCSTEPSIZE, gettotalbytes, KGC_GEN, KGC_NORMAL, LUA_GCCOLLECT, LUA_GCCOUNT, LUA_GCCOUNTB, LUA_GCGEN, LUA_GCINC, LUA_GCISRUNNING, LUA_GCRESTART, LUA_GCSETMAJORINC, LUA_GCSETPAUSE, LUA_GCSETSTEPMUL, LUA_GCSTEP, LUA_GCSTOP, lua_lock, lua_unlock, luaC_changemode(), luaC_forcestep(), luaC_fullgc(), and luaE_setdebt().
Referenced by luaB_collectgarbage().
LUA_API lua_Alloc lua_getallocf (lua_State * L, void ** ud)
Definition at line 1157 of file lapi.c.
References G, lua_lock, and lua_unlock.
LUA_API int lua_getctx (lua_State * L, int * ctx)
Definition at line 880 of file lapi.c.
References CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_YIELDED, LUA_OK, and CallInfo::u.
Referenced by pcallcont().
LUA_API void lua_getfield (lua_State * L, int idx, const char * k)
Definition at line 628 of file lapi.c.
References api_incr_top, index2addr(), lua_lock, lua_unlock, luaS_new(), luaV_gettable(), setsvalue2s, and lua_State::top.
Referenced by findfile(), findloader(), g_iofile(), getboolfield(), getfield(), getiofile(), io_close(), io_lines(), ll_addtoclib(), ll_checkclib(), ll_require(), lookupKey(), lookupNewKey(), luaL_getsubtable(), luaopen_table(), noenv(), popValue(), and searcher_preload().
LUA_API void lua_getglobal (lua_State * L, const char * var)
Definition at line 608 of file lapi.c.
References G, hvalue, lua_lock, LUA_RIDX_GLOBALS, lua_unlock, luaH_getint(), luaS_new(), luaV_gettable(), setsvalue2s, and lua_State::top.
Referenced by luaB_print().
LUA_API int lua_getmetatable (lua_State * L, int objindex)
Definition at line 686 of file lapi.c.
References api_incr_top, G, hvalue, index2addr(), lua_lock, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, sethvalue, lua_State::top, ttypenv, and uvalue.
Referenced by db_getmetatable(), luaB_getmetatable(), luaL_getmetafield(), and luaL_testudata().
LUA_API void lua_gettable (lua_State * L, int idx)
Definition at line 619 of file lapi.c.
References index2addr(), lua_lock, lua_unlock, luaV_gettable(), and lua_State::top.
Referenced by add_value().
LUA_API int lua_gettop (lua_State * L)
Definition at line 160 of file lapi.c.
References cast_int, lua_State::ci, CallInfo::func, and lua_State::top.
Referenced by andaux(), aux_lines(), auxresume(), b_or(), b_xor(), dofilecont(), finishpcall(), g_read(), g_write(), luaB_assert(), luaB_auxwrap(), luaB_coresume(), luaB_costatus(), luaB_pcall(), luaB_print(), luaB_select(), luaB_xpcall(), luaB_yield(), luaL_loadfilex(), luaL_traceback(), math_max(), math_min(), math_random(), pack(), pushglobalfuncname(), str_char(), str_format(), and tinsert().
LUA_API const char* lua_getupvalue (lua_State * L, int funcindex, int n)
Definition at line 1213 of file lapi.c.
References api_incr_top, aux_upvalue(), index2addr(), lua_lock, lua_unlock, setobj2s, and lua_State::top.
Referenced by auxupvalue().
LUA_API void lua_getuservalue (lua_State * L, int idx)
Definition at line 715 of file lapi.c.
References api_check, api_incr_top, index2addr(), lua_lock, lua_unlock, sethvalue, setnilvalue, lua_State::top, ttisuserdata, and uvalue.
Referenced by db_getuservalue().
LUA_API void lua_insert (lua_State * L, int idx)
Definition at line 193 of file lapi.c.
References api_checkstackindex, index2addr(), lua_lock, lua_unlock, setobjs2s, and lua_State::top.
Referenced by auxupvalue(), findfield(), ll_loadlib(), ll_require(), ll_searchpath(), load_aux(), luaB_auxwrap(), luaB_coresume(), luaB_pcall(), and luaL_addvalue().
LUA_API int lua_iscfunction (lua_State * L, int idx)
Definition at line 261 of file lapi.c.
References index2addr(), ttisCclosure, and ttislcf.
Referenced by db_upvaluejoin().
LUA_API int lua_isnumber (lua_State * L, int idx)
Definition at line 267 of file lapi.c.
References index2addr(), and tonumber.
Referenced by db_getinfo(), popValue(), and pushValue().
LUA_API int lua_isstring (lua_State * L, int idx)
Definition at line 274 of file lapi.c.
References LUA_TNUMBER, LUA_TSTRING, and lua_type().
Referenced by add_value(), addfield(), findloader(), generic_reader(), lookupKey(), lookupNewKey(), luaB_auxwrap(), luaB_error(), and popValue().
LUA_API int lua_isuserdata (lua_State * L, int idx)
Definition at line 280 of file lapi.c.
References index2addr(), ttislightuserdata, and ttisuserdata.
LUA_API void lua_len (lua_State * L, int idx)
Definition at line 1147 of file lapi.c.
References api_incr_top, index2addr(), lua_lock, lua_unlock, luaV_objlen(), and lua_State::top.
Referenced by luaL_len().
LUA_API int lua_load (lua_State * L, lua_Reader reader, void * data, const char * chunkname, const char * mode)
Definition at line 973 of file lapi.c.
References clLvalue, G, hvalue, lua_lock, LUA_OK, LUA_RIDX_GLOBALS, lua_unlock, luaC_barrier, luaD_protectedparser(), luaH_getint(), luaZ_init(), setobj, lua_State::top, LClosure::upvals, and UpVal::v.
Referenced by luaB_load(), luaL_loadbufferx(), and luaL_loadfilex().
LUA_API void* lua_newuserdata (lua_State * L, size_t size)
Definition at line 1175 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaS_newudata(), setuvalue, and lua_State::top.
Referenced by luaL_prepbuffsize(), newprefile(), and pushValue().
LUA_API int lua_next (lua_State * L, int idx)
Definition at line 1114 of file lapi.c.
References api_check, api_incr_top, hvalue, index2addr(), lua_lock, lua_unlock, luaH_next(), lua_State::top, and ttistable.
Referenced by findfield(), luaB_next(), and popValue().
LUA_API int lua_pcallk (lua_State * L, int nargs, int nresults, int errfunc, int ctx, lua_CFunction k)
Definition at line 928 of file lapi.c.
References adjustresults, lua_State::allowhook, api_check, api_checknelems, api_checkstackindex, CallInfo::c, CallInfo::callstatus, checkresults, lua_State::ci, CIST_YPCALL, lua_State::errfunc, CallInfo::extra, f_call(), CallS::func, index2addr(), isLua, lua_lock, LUA_OK, lua_unlock, luaD_call(), luaD_pcall(), lua_State::nny, CallS::nresults, savestack, lua_State::status, lua_State::top, and CallInfo::u.
Referenced by luaB_pcall(), and luaB_xpcall().
LUA_API void lua_pushboolean (lua_State * L, int b)
Definition at line 577 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, setbvalue, and lua_State::top.
Referenced by aux_lines(), b_test(), finishpcall(), ll_loadfunc(), ll_require(), luaB_collectgarbage(), luaB_coresume(), luaB_corunning(), luaB_rawequal(), luaL_execresult(), luaL_fileresult(), os_execute(), setboolfield(), and settabsb().
LUA_API void lua_pushcclosure (lua_State * L, lua_CFunction fn, int n)
Definition at line 555 of file lapi.c.
References api_check, api_checknelems, api_incr_top, Closure::c, CClosure::f, lua_lock, lua_unlock, luaC_checkGC, luaF_newCclosure(), MAXUPVAL, setclCvalue, setfvalue, setobj2n, lua_State::top, and CClosure::upvalue.
Referenced by aux_lines(), createsearcherstable(), gmatch(), luaB_cowrap(), and luaL_setfuncs().
LUA_API const char* lua_pushfstring (lua_State * L, const char * fmt, ...)
Definition at line 542 of file lapi.c.
References lua_lock, lua_unlock, luaC_checkGC, and luaO_pushvfstring().
Referenced by checkoption(), db_getinfo(), errfile(), f_tostring(), loadfunc(), luaL_checkoption(), luaL_fileresult(), luaL_loadfilex(), luaL_tolstring(), luaL_traceback(), luaL_where(), pushfuncname(), searcher_Croot(), searcher_preload(), searchpath(), and typeerror().
LUA_API void lua_pushinteger (lua_State * L, lua_Integer n)
Definition at line 483 of file lapi.c.
References api_incr_top, cast_num, lua_lock, lua_unlock, setnvalue, and lua_State::top.
Referenced by aux_lines(), db_gethook(), gmatch(), gmatch_aux(), hookf(), ipairsaux(), luaB_collectgarbage(), luaB_rawlen(), luaB_select(), luaL_execresult(), luaL_fileresult(), luaL_unref(), math_frexp(), pack(), pairsmeta(), push_onecapture(), setfield(), settabsi(), str_byte(), str_find_aux(), str_gsub(), and str_len().
LUA_API void lua_pushlightuserdata (lua_State * L, void * p)
Definition at line 585 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, setpvalue, and lua_State::top.
Referenced by db_upvalueid(), KenshoLuaWrapper::evaluate, ll_addtoclib(), and pushValue().
LUA_API const char* lua_pushlstring (lua_State * L, const char * s, size_t len)
Definition at line 501 of file lapi.c.
References api_incr_top, getstr, lua_lock, lua_unlock, luaC_checkGC, luaS_newlstr(), setsvalue2s, and lua_State::top.
Referenced by add_value(), loadfunc(), luaL_pushresult(), push_onecapture(), pushnexttemplate(), searcher_Croot(), str_sub(), and test_eof().
LUA_API void lua_pushnil (lua_State * L)
Definition at line 465 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, setnilvalue, and lua_State::top.
Referenced by db_getinfo(), db_getlocal(), db_getmetatable(), db_getuservalue(), findfield(), g_read(), hookf(), io_lines(), io_noclose(), io_type(), ll_loadlib(), ll_searchpath(), load_aux(), lua_pushstring(), luaB_getmetatable(), luaB_next(), luaB_pcall(), luaB_tonumber(), luaL_execresult(), luaL_fileresult(), os_date(), os_time(), pairsmeta(), read_number(), str_find_aux(), and tremove().
LUA_API void lua_pushnumber (lua_State * L, lua_Number n)
Definition at line 473 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, luaG_runerror(), luai_checknum, setnvalue, and lua_State::top.
Referenced by f_seek(), luaB_collectgarbage(), luaB_tonumber(), luaL_checkversion_(), luaopen_math(), math_abs(), math_acos(), math_asin(), math_atan(), math_atan2(), math_ceil(), math_cos(), math_cosh(), math_deg(), math_exp(), math_floor(), math_fmod(), math_frexp(), math_ldexp(), math_log(), math_max(), math_min(), math_modf(), math_pow(), math_rad(), math_random(), math_sin(), math_sinh(), math_sqrt(), math_tan(), math_tanh(), os_clock(), os_difftime(), os_time(), pushValue(), and read_number().
LUA_API const char* lua_pushstring (lua_State * L, const char * s)
Definition at line 513 of file lapi.c.
References api_incr_top, getstr, lua_lock, lua_pushnil(), lua_unlock, luaC_checkGC, luaS_new(), setsvalue2s, and lua_State::top.
Referenced by auxupvalue(), checkload(), db_gethook(), db_getlocal(), db_sethook(), db_setlocal(), KenshoLuaWrapper::evaluate, findloader(), finishpcall(), hookf(), ll_loadlib(), ll_require(), luaB_type(), luaL_execresult(), luaL_fileresult(), luaL_getmetafield(), luaL_requiref(), luaL_tolstring(), os_getenv(), os_setlocale(), os_tmpname(), pushValue(), searcher_Croot(), setpath(), and settabss().
LUA_API int lua_pushthread (lua_State * L)
Definition at line 593 of file lapi.c.
References api_incr_top, G, lua_lock, lua_unlock, setthvalue, and lua_State::top.
Referenced by db_gethook(), db_sethook(), hookf(), and luaB_corunning().
LUA_API void lua_pushunsigned (lua_State * L, lua_Unsigned u)
Definition at line 491 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, lua_unsigned2number, setnvalue, and lua_State::top.
Referenced by b_and(), b_arshift(), b_extract(), b_not(), b_or(), b_replace(), b_rot(), b_shift(), and b_xor().
LUA_API void lua_pushvalue (lua_State * L, int idx)
Definition at line 235 of file lapi.c.
References api_incr_top, index2addr(), lua_lock, lua_unlock, setobj2s, and lua_State::top.
Referenced by add_value(), aux_lines(), auxsort(), checkupval(), createmeta(), createmetatable(), createsearcherstable(), createstdfile(), db_getinfo(), db_getlocal(), db_getregistry(), db_sethook(), db_traceback(), f_write(), g_iofile(), generic_reader(), io_readline(), ll_addtoclib(), ll_require(), load_aux(), luaB_cocreate(), luaB_error(), luaB_print(), luaB_xpcall(), luaL_callmeta(), luaL_getsubtable(), luaL_newmetatable(), luaL_requiref(), luaL_setfuncs(), luaL_tolstring(), luaopen_package(), pack(), pairsmeta(), sort_comp(), and treatstackoption().
LUA_API const char* lua_pushvfstring (lua_State * L, const char * fmt, va_list argp)
Definition at line 531 of file lapi.c.
References lua_lock, lua_unlock, luaC_checkGC, and luaO_pushvfstring().
Referenced by luaL_error().
LUA_API int lua_rawequal (lua_State * L, int index1, int index2)
Definition at line 286 of file lapi.c.
References index2addr(), isvalid, and luaV_rawequalobj.
Referenced by findfield(), luaB_rawequal(), and luaL_testudata().
LUA_API void lua_rawget (lua_State * L, int idx)
Definition at line 639 of file lapi.c.
References api_check, hvalue, index2addr(), lua_lock, lua_unlock, luaH_get(), setobj2s, lua_State::top, and ttistable.
Referenced by db_gethook(), hookf(), luaB_rawget(), and luaL_getmetafield().
LUA_API void lua_rawgeti (lua_State * L, int idx, int n)
Definition at line 649 of file lapi.c.
References api_check, api_incr_top, hvalue, index2addr(), lua_lock, lua_unlock, luaH_getint(), setobj2s, lua_State::top, and ttistable.
Referenced by addfield(), auxsort(), findloader(), gctm(), ipairsaux(), luaL_ref(), luaL_unref(), tinsert(), tremove(), and unpack().
LUA_API void lua_rawgetp (lua_State * L, int idx, const void * p)
Definition at line 660 of file lapi.c.
References api_check, api_incr_top, cast, hvalue, index2addr(), lua_lock, lua_unlock, luaH_get(), setobj2s, setpvalue, lua_State::top, and ttistable.
LUA_API size_t lua_rawlen (lua_State * L, int idx)
Definition at line 407 of file lapi.c.
References hvalue, index2addr(), LUA_TSTRING, LUA_TTABLE, LUA_TUSERDATA, luaH_getn(), tsvalue, ttypenv, and uvalue.
Referenced by luaB_rawlen(), luaL_ref(), and read_line().
LUA_API void lua_rawset (lua_State * L, int idx)
Definition at line 770 of file lapi.c.
References api_check, api_checknelems, gcvalue, hvalue, index2addr(), invalidateTMcache, lua_lock, lua_unlock, luaC_barrierback, luaH_set(), setobj2t, lua_State::top, and ttistable.
Referenced by db_sethook(), and luaB_rawset().
LUA_API void lua_rawseti (lua_State * L, int idx, int n)
Definition at line 784 of file lapi.c.
References api_check, api_checknelems, gcvalue, hvalue, index2addr(), lua_lock, lua_unlock, luaC_barrierback, luaH_setint(), lua_State::top, and ttistable.
Referenced by createsearcherstable(), ll_addtoclib(), luaL_ref(), luaL_unref(), pack(), set2(), tinsert(), and tremove().
LUA_API void lua_rawsetp (lua_State * L, int idx, const void * p)
Definition at line 797 of file lapi.c.
References api_check, api_checknelems, cast, gcvalue, hvalue, index2addr(), lua_lock, lua_unlock, luaC_barrierback, luaH_set(), setobj2t, setpvalue, lua_State::top, and ttistable.
LUA_API void lua_remove (lua_State * L, int idx)
Definition at line 182 of file lapi.c.
References api_checkstackindex, index2addr(), lua_lock, lua_unlock, setobjs2s, and lua_State::top.
Referenced by db_gethook(), errfile(), findfield(), luaL_addvalue(), luaL_getmetafield(), luaL_loadfilex(), luaL_prepbuffsize(), luaL_pushresult(), pushfuncname(), searchpath(), setpath(), and treatstackoption().
LUA_API void lua_replace (lua_State * L, int idx)
Definition at line 217 of file lapi.c.
References api_checknelems, lua_lock, lua_unlock, moveto(), and lua_State::top.
Referenced by finishpcall(), generic_reader(), gmatch_aux(), io_lines(), luaB_xpcall(), and pack().
LUA_API void lua_setallocf (lua_State * L, lua_Alloc f, void * ud)
Definition at line 1167 of file lapi.c.
References G, lua_lock, and lua_unlock.
LUA_API void lua_setfield (lua_State * L, int idx, const char * k)
Definition at line 758 of file lapi.c.
References api_checknelems, index2addr(), lua_lock, lua_unlock, luaS_new(), luaV_settable(), setsvalue2s, and lua_State::top.
Referenced by createmeta(), createmetatable(), createstdfile(), db_sethook(), g_iofile(), ll_addtoclib(), ll_require(), luaL_getsubtable(), luaL_newmetatable(), luaL_openlibs(), luaL_requiref(), luaL_setfuncs(), luaopen_base(), luaopen_math(), luaopen_package(), pack(), pushValue(), setboolfield(), setfield(), setpath(), settabsb(), settabsi(), settabss(), and treatstackoption().
LUA_API void lua_setglobal (lua_State * L, const char * var)
Definition at line 734 of file lapi.c.
References api_checknelems, G, hvalue, lua_lock, LUA_RIDX_GLOBALS, lua_unlock, luaH_getint(), luaS_new(), luaV_settable(), setsvalue2s, and lua_State::top.
Referenced by KenshoLuaWrapper::evaluate, luaL_requiref(), and luaopen_table().
LUA_API int lua_setmetatable (lua_State * L, int objindex)
Definition at line 812 of file lapi.c.
References api_check, api_checknelems, G, gcvalue, hvalue, index2addr(), lua_lock, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, luaC_checkfinalizer(), luaC_objbarrier, luaC_objbarrierback, rawuvalue, lua_State::top, ttisnil, ttistable, ttypenv, and uvalue.
Referenced by createmetatable(), db_sethook(), db_setmetatable(), KenshoLuaWrapper::evaluate, luaB_setmetatable(), luaL_setmetatable(), luaopen_package(), and pushValue().
LUA_API void lua_settable (lua_State * L, int idx)
Definition at line 747 of file lapi.c.
References api_checknelems, index2addr(), lua_lock, lua_unlock, luaV_settable(), and lua_State::top.
Referenced by KenshoLuaWrapper::evaluate, and pushValue().
LUA_API void lua_settop (lua_State * L, int idx)
Definition at line 165 of file lapi.c.
References api_check, lua_State::ci, CallInfo::func, lua_lock, lua_unlock, setnilvalue, and lua_State::top.
Referenced by db_debug(), db_sethook(), db_setlocal(), db_setmetatable(), db_setuservalue(), finishpcall(), gmatch(), io_readline(), ll_require(), luaB_dofile(), luaB_error(), luaB_load(), luaB_next(), luaB_rawget(), luaB_rawset(), luaB_setmetatable(), luaL_loadfilex(), os_time(), pushglobalfuncname(), sort(), and str_dump().
LUA_API const char* lua_setupvalue (lua_State * L, int funcindex, int n)
Definition at line 1227 of file lapi.c.
References api_checknelems, aux_upvalue(), index2addr(), lua_lock, lua_unlock, luaC_barrier, setobj, and lua_State::top.
Referenced by auxupvalue(), and load_aux().
LUA_API void lua_setuservalue (lua_State * L, int idx)
Definition at line 852 of file lapi.c.
References api_check, api_checknelems, gcvalue, hvalue, index2addr(), lua_lock, lua_unlock, luaC_objbarrier, lua_State::top, ttisnil, ttistable, ttisuserdata, and uvalue.
Referenced by db_setuservalue().
LUA_API int lua_status (lua_State * L)
Definition at line 1012 of file lapi.c.
References lua_State::status.
Referenced by auxresume(), and luaB_costatus().
LUA_API int lua_toboolean (lua_State * L, int idx)
Definition at line 383 of file lapi.c.
References index2addr(), and l_isfalse.
Referenced by add_value(), getboolfield(), io_readline(), ll_require(), luaB_assert(), luaL_tolstring(), noenv(), os_exit(), popValue(), sort_comp(), and str_find_aux().
LUA_API lua_CFunction lua_tocfunction (lua_State * L, int idx)
Definition at line 418 of file lapi.c.
References clCvalue, fvalue, index2addr(), ttisCclosure, and ttislcf.
LUA_API lua_Integer lua_tointegerx (lua_State * L, int idx, int * isnum)
Definition at line 349 of file lapi.c.
References index2addr(), lua_number2integer, nvalue, and tonumber.
Referenced by getfield(), luaL_checkinteger(), and luaL_len().
LUA_API const char* lua_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 389 of file lapi.c.
References index2addr(), lua_lock, lua_unlock, luaC_checkGC, luaV_tostring(), svalue, tsvalue, and ttisstring.
Referenced by add_s(), generic_reader(), gmatch_aux(), luaB_load(), luaB_print(), luaL_addvalue(), luaL_checklstring(), and luaL_tolstring().
LUA_API lua_Number lua_tonumberx (lua_State * L, int idx, int * isnum)
Definition at line 335 of file lapi.c.
References index2addr(), nvalue, and tonumber.
Referenced by luaB_tonumber(), and luaL_checknumber().
LUA_API const void* lua_topointer (lua_State * L, int idx)
Definition at line 443 of file lapi.c.
References cast, clCvalue, clLvalue, fvalue, hvalue, index2addr(), LUA_TCCL, LUA_TLCF, LUA_TLCL, LUA_TLIGHTUSERDATA, lua_touserdata(), LUA_TTABLE, LUA_TTHREAD, LUA_TUSERDATA, thvalue, and ttype.
Referenced by luaL_tolstring().
LUA_API lua_State* lua_tothread (lua_State * L, int idx)
Definition at line 437 of file lapi.c.
References index2addr(), thvalue, and ttisthread.
Referenced by getthread(), luaB_auxwrap(), luaB_coresume(), and luaB_costatus().
LUA_API lua_Unsigned lua_tounsignedx (lua_State * L, int idx, int * isnum)
Definition at line 366 of file lapi.c.
References index2addr(), lua_number2unsigned, nvalue, and tonumber.
Referenced by luaL_checkunsigned().
LUA_API void* lua_touserdata (lua_State * L, int idx)
Definition at line 427 of file lapi.c.
References index2addr(), LUA_TLIGHTUSERDATA, LUA_TUSERDATA, pvalue, rawuvalue, and ttypenv.
Referenced by gctm(), getiofile(), io_readline(), ll_checkclib(), lookupKey(), lookupNewKey(), lua_topointer(), luaL_testudata(), and popValue().
LUA_API int lua_type (lua_State * L, int idx)
Definition at line 249 of file lapi.c.
References index2addr(), isvalid, LUA_TNONE, and ttypenv.
Referenced by db_getuservalue(), db_setmetatable(), db_setuservalue(), findfield(), g_read(), g_write(), lua_isstring(), luaB_rawlen(), luaB_select(), luaB_setmetatable(), luaL_checkany(), luaL_checktype(), luaL_tolstring(), popValue(), and str_gsub().
LUA_API const char* lua_typename (lua_State * L, int t)
Definition at line 255 of file lapi.c.
References ttypename, and UNUSED.
Referenced by popValue(), and tag_error().
LUA_API void* lua_upvalueid (lua_State * L, int fidx, int n)
Definition at line 1257 of file lapi.c.
References api_check, clCvalue, getupvalref(), index2addr(), LUA_TCCL, LUA_TLCL, ttype, and CClosure::upvalue.
Referenced by db_upvalueid().
LUA_API void lua_upvaluejoin (lua_State * L, int fidx1, int n1, int fidx2, int n2)
Definition at line 1276 of file lapi.c.
References getupvalref(), and luaC_objbarrier.
Referenced by db_upvaluejoin().
LUA_API const lua_Number* lua_version (lua_State * L)
Definition at line 137 of file lapi.c.
References G, and LUA_VERSION_NUM.
Referenced by f_luaopen(), and luaL_checkversion_().
LUA_API void lua_xmove (lua_State * from, lua_State * to, int n)
Definition at line 112 of file lapi.c.
References api_check, api_checknelems, lua_State::ci, G, lua_lock, lua_unlock, setobj2s, CallInfo::top, and lua_State::top.
Referenced by auxresume(), db_gethook(), db_getinfo(), db_getlocal(), db_sethook(), db_setlocal(), luaB_cocreate(), and treatstackoption().
static void moveto (lua_State * L, TValue * fr, int idx) static
Definition at line 206 of file lapi.c.
References api_checkvalidindex, lua_State::ci, clCvalue, CallInfo::func, index2addr(), LUA_REGISTRYINDEX, luaC_barrier, and setobj.
Referenced by lua_copy(), and lua_replace().
Variable Documentation
const char lua_ident[]
Initial value:
=
  "$LuaVersion: " LUA_COPYRIGHT " $"
  "$LuaAuthors: " LUA_AUTHORS " $"
Definition at line 32 of file lapi.c.