Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/loadlib.c File Reference
loadlib.c File Reference
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define loadlib_c
#define LUA_LIB
#define LUA_PATH "LUA_PATH"
#define LUA_CPATH "LUA_CPATH"
#define LUA_PATHSUFFIX "_" LUA_VERSION_MAJOR "_" LUA_VERSION_MINOR
#define LUA_PATHVERSION LUA_PATH LUA_PATHSUFFIX
#define LUA_CPATHVERSION LUA_CPATH LUA_PATHSUFFIX
#define LUA_PATH_SEP ";"
#define LUA_PATH_MARK "?"
#define LUA_EXEC_DIR "!"
#define LUA_IGMARK "-"
#define LUA_CSUBSEP LUA_DIRSEP
#define LUA_LSUBSEP LUA_DIRSEP
#define LUA_POF "luaopen_"
#define LUA_OFSEP "_"
#define CLIBS "_CLIBS"
#define LIB_FAIL "open"
#define ERRLIB 1
#define ERRFUNC 2
#define setprogdir(L) ((void)0)
#define LIB_FAIL "absent"
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
#define AUXMARK "\1"
Functions
static void ll_unloadlib (void *lib)
static void * ll_load (lua_State *L, const char *path, int seeglb)
static lua_CFunction ll_sym (lua_State *L, void *lib, const char *sym)
static void * ll_checkclib (lua_State *L, const char *path)
static void ll_addtoclib (lua_State *L, const char *path, void *plib)
static int gctm (lua_State *L)
static int ll_loadfunc (lua_State *L, const char *path, const char *sym)
static int ll_loadlib (lua_State *L)
static int readable (const char *filename)
static const char * pushnexttemplate (lua_State *L, const char *path)
static const char * searchpath (lua_State *L, const char *name, const char *path, const char *sep, const char *dirsep)
static int ll_searchpath (lua_State *L)
static const char * findfile (lua_State *L, const char *name, const char *pname, const char *dirsep)
static int checkload (lua_State *L, int stat, const char *filename)
static int searcher_Lua (lua_State *L)
static int loadfunc (lua_State *L, const char *filename, const char *modname)
static int searcher_C (lua_State *L)
static int searcher_Croot (lua_State *L)
static int searcher_preload (lua_State *L)
static void findloader (lua_State *L, const char *name)
static int ll_require (lua_State *L)
static int noenv (lua_State *L)
static void setpath (lua_State *L, const char *fieldname, const char *envname1, const char *envname2, const char *def)
static void createsearcherstable (lua_State *L)
LUAMOD_API int luaopen_package (lua_State *L)
Variables
static const luaL_Reg pk_funcs []
static const luaL_Reg ll_funcs []
Macro Definition Documentation
#define AUXMARK "\1"
Definition at line 622 of file loadlib.c.
Referenced by setpath().
#define CLIBS "_CLIBS"
Definition at line 96 of file loadlib.c.
Referenced by ll_addtoclib(), ll_checkclib(), and luaopen_package().
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
Definition at line 226 of file loadlib.c.
Referenced by ll_load(), and ll_sym().
#define ERRFUNC 2
Definition at line 103 of file loadlib.c.
Referenced by ll_loadfunc(), loadfunc(), and searcher_Croot().
#define ERRLIB 1
Definition at line 102 of file loadlib.c.
Referenced by ll_loadfunc(), and ll_loadlib().
#define LIB_FAIL "open"
Definition at line 223 of file loadlib.c.
Referenced by ll_loadlib().
#define LIB_FAIL "absent"
Definition at line 223 of file loadlib.c.
#define loadlib_c
Definition at line 24 of file loadlib.c.
#define LUA_CPATH "LUA_CPATH"
Definition at line 42 of file loadlib.c.
Referenced by luaopen_package().
#define LUA_CPATHVERSION LUA_CPATH LUA_PATHSUFFIX
Definition at line 48 of file loadlib.c.
Referenced by luaopen_package().
#define LUA_CSUBSEP LUA_DIRSEP
Definition at line 80 of file loadlib.c.
Referenced by searcher_C(), and searcher_Croot().
#define LUA_EXEC_DIR "!"
Definition at line 66 of file loadlib.c.
Referenced by luaopen_package().
#define LUA_IGMARK "-"
Definition at line 69 of file loadlib.c.
Referenced by loadfunc(), and luaopen_package().
#define LUA_LIB
Definition at line 25 of file loadlib.c.
#define LUA_LSUBSEP LUA_DIRSEP
Definition at line 84 of file loadlib.c.
Referenced by searcher_Lua().
#define LUA_OFSEP "_"
Definition at line 92 of file loadlib.c.
Referenced by loadfunc().
#define LUA_PATH "LUA_PATH"
Definition at line 38 of file loadlib.c.
Referenced by luaopen_package().
#define LUA_PATH_MARK "?"
Definition at line 63 of file loadlib.c.
Referenced by luaopen_package(), and searchpath().
#define LUA_PATH_SEP ";"
Definition at line 60 of file loadlib.c.
Referenced by luaopen_package(), pushnexttemplate(), and setpath().
#define LUA_PATHSUFFIX "_" LUA_VERSION_MAJOR "_" LUA_VERSION_MINOR
Definition at line 45 of file loadlib.c.
#define LUA_PATHVERSION LUA_PATH LUA_PATHSUFFIX
Definition at line 47 of file loadlib.c.
Referenced by luaopen_package().
#define LUA_POF "luaopen_"
Definition at line 89 of file loadlib.c.
Referenced by loadfunc().
#define setprogdir (L) ((void)0)
Definition at line 105 of file loadlib.c.
Referenced by setpath().
Function Documentation
static int checkload (lua_State * L, int stat, const char * filename) static
Definition at line 398 of file loadlib.c.
References lua_pushstring(), LUA_QS, lua_tostring, and luaL_error().
Referenced by searcher_C(), searcher_Croot(), and searcher_Lua().
static void createsearcherstable (lua_State * L) static
Definition at line 675 of file loadlib.c.
References lua_createtable(), lua_pushcclosure(), lua_pushvalue(), lua_rawseti(), searcher_C(), searcher_Croot(), searcher_Lua(), and searcher_preload().
Referenced by luaopen_package().
static const char* findfile (lua_State * L, const char * name, const char * pname, const char * dirsep) static
Definition at line 386 of file loadlib.c.
References lua_getfield(), LUA_QL, lua_tostring, lua_upvalueindex, luaL_error(), and searchpath().
Referenced by searcher_C(), searcher_Croot(), and searcher_Lua().
static void findloader (lua_State * L, const char * name) static
Definition at line 478 of file loadlib.c.
References lua_call, lua_getfield(), lua_isfunction, lua_isnil, lua_isstring(), lua_istable, lua_pop, lua_pushstring(), LUA_QL, LUA_QS, lua_rawgeti(), lua_tostring, lua_upvalueindex, luaL_addvalue(), luaL_buffinit(), luaL_error(), and luaL_pushresult().
Referenced by ll_require().
static int gctm (lua_State * L) static
Definition at line 275 of file loadlib.c.
References ll_unloadlib(), lua_pop, lua_rawgeti(), lua_touserdata(), and luaL_len().
Referenced by luaopen_package().
static void ll_addtoclib (lua_State * L, const char * path, void * plib) static
Definition at line 261 of file loadlib.c.
References CLIBS, lua_getfield(), lua_pop, lua_pushlightuserdata(), lua_pushvalue(), lua_rawseti(), LUA_REGISTRYINDEX, lua_setfield(), and luaL_len().
Referenced by ll_loadfunc().
static void* ll_checkclib (lua_State * L, const char * path) static
Definition at line 251 of file loadlib.c.
References CLIBS, lua_getfield(), lua_pop, LUA_REGISTRYINDEX, and lua_touserdata().
Referenced by ll_loadfunc().
static void * ll_load (lua_State * L, const char * path, int seeglb) static
Definition at line 234 of file loadlib.c.
References DLMSG, and lua_pushliteral.
Referenced by ll_loadfunc().
static int ll_loadfunc (lua_State * L, const char * path, const char * sym) static
Definition at line 286 of file loadlib.c.
References ERRFUNC, ERRLIB, ll_addtoclib(), ll_checkclib(), ll_load(), ll_sym(), lua_pushboolean(), and lua_pushcfunction.
Referenced by ll_loadlib(), and loadfunc().
static int ll_loadlib (lua_State * L) static
Definition at line 307 of file loadlib.c.
References ERRLIB, LIB_FAIL, ll_loadfunc(), lua_insert(), lua_pushnil(), lua_pushstring(), and luaL_checkstring.
static int ll_require (lua_State * L) static
Definition at line 508 of file loadlib.c.
References findloader(), lua_call, lua_getfield(), lua_insert(), lua_isnil, lua_pop, lua_pushboolean(), lua_pushstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_settop(), lua_toboolean(), and luaL_checkstring.
static int ll_searchpath (lua_State * L) static
Definition at line 372 of file loadlib.c.
References LUA_DIRSEP, lua_insert(), lua_pushnil(), luaL_checkstring, luaL_optstring, and searchpath().
static lua_CFunction ll_sym (lua_State * L, void * lib, const char * sym) static
Definition at line 241 of file loadlib.c.
References DLMSG, and lua_pushliteral.
Referenced by ll_loadfunc().
static void ll_unloadlib (void * lib) static
Definition at line 229 of file loadlib.c.
Referenced by gctm().
static int loadfunc (lua_State * L, const char * filename, const char * modname) static
Definition at line 419 of file loadlib.c.
References ERRFUNC, funcname(), ll_loadfunc(), LUA_IGMARK, LUA_OFSEP, LUA_POF, lua_pushfstring(), lua_pushlstring(), and luaL_gsub().
Referenced by searcher_C(), and searcher_Croot().
LUAMOD_API int luaopen_package (lua_State * L)
Definition at line 690 of file loadlib.c.
References CLIBS, createsearcherstable(), gctm(), LUA_CPATH, LUA_CPATH_DEFAULT, LUA_CPATHVERSION, lua_createtable(), LUA_DIRSEP, LUA_EXEC_DIR, LUA_IGMARK, LUA_PATH, LUA_PATH_DEFAULT, LUA_PATH_MARK, LUA_PATH_SEP, LUA_PATHVERSION, lua_pop, lua_pushcfunction, lua_pushglobaltable, lua_pushliteral, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_setmetatable(), luaL_getsubtable(), luaL_newlib, luaL_setfuncs(), and setpath().
static int noenv (lua_State * L) static
Definition at line 628 of file loadlib.c.
References lua_getfield(), lua_pop, LUA_REGISTRYINDEX, and lua_toboolean().
Referenced by setpath().
static const char* pushnexttemplate (lua_State * L, const char * path) static
Definition at line 338 of file loadlib.c.
References LUA_PATH_SEP, and lua_pushlstring().
Referenced by searchpath().
static int readable (const char * filename) static
Definition at line 330 of file loadlib.c.
Referenced by searchpath().
static int searcher_C (lua_State * L) static
Definition at line 437 of file loadlib.c.
References checkload(), findfile(), loadfunc(), LUA_CSUBSEP, and luaL_checkstring.
Referenced by createsearcherstable().
static int searcher_Croot (lua_State * L) static
Definition at line 445 of file loadlib.c.
References checkload(), ERRFUNC, findfile(), loadfunc(), LUA_CSUBSEP, lua_pushfstring(), lua_pushlstring(), lua_pushstring(), LUA_QS, lua_tostring, and luaL_checkstring.
Referenced by createsearcherstable().
static int searcher_Lua (lua_State * L) static
Definition at line 410 of file loadlib.c.
References checkload(), findfile(), LUA_LSUBSEP, LUA_OK, luaL_checkstring, and luaL_loadfile.
Referenced by createsearcherstable().
static int searcher_preload (lua_State * L) static
Definition at line 468 of file loadlib.c.
References lua_getfield(), lua_isnil, lua_pushfstring(), LUA_REGISTRYINDEX, and luaL_checkstring.
Referenced by createsearcherstable().
static const char* searchpath (lua_State * L, const char * name, const char * path, const char * sep, const char * dirsep) static
Definition at line 349 of file loadlib.c.
References LUA_PATH_MARK, lua_pushfstring(), LUA_QS, lua_remove(), lua_tostring, luaL_addvalue(), luaL_buffinit(), luaL_gsub(), luaL_pushresult(), pushnexttemplate(), and readable().
Referenced by findfile(), and ll_searchpath().
static void setpath (lua_State * L, const char * fieldname, const char * envname1, const char * envname2, const char * def) static
Definition at line 637 of file loadlib.c.
References AUXMARK, LUA_PATH_SEP, lua_pushstring(), lua_remove(), lua_setfield(), luaL_gsub(), noenv(), and setprogdir.
Referenced by luaopen_package().
Variable Documentation
const luaL_Reg ll_funcs[] static
Initial value:
= {
  {"require", ll_require},
  {NULL, NULL}
}
Definition at line 666 of file loadlib.c.
const luaL_Reg pk_funcs[] static
Initial value:
= {
  {"loadlib", ll_loadlib},
  {"searchpath", ll_searchpath},
  {NULL, NULL}
}
Definition at line 656 of file loadlib.c.