Kensho: ObservablePropertyReference Class Reference
ObservablePropertyReference Class Reference
#import <ObservablePropertyReference.h>
Instance Methods
(id) - initWithOwner:propertyName:
Class Methods
(NSObject *) + unwrap:
Properties
NSObject * owner
NSString * propertyName
NSObject * value
Detailed Description
Definition at line 12 of file ObservablePropertyReference.h.
Method Documentation
- (id) initWithOwner: (NSObject*) owner propertyName: (NSString*) name
Definition at line 29 of file ObservablePropertyReference.m.
References owner.
+ (NSObject *) unwrap: (NSObject*) value
Definition at line 16 of file ObservablePropertyReference.m.
References value.
Referenced by addValues(), concatValues(), divideValues(), equalsValues(), exponentValues(), KenshoLuaWrapper::finalValue, lessValues(), lookupKey(), modulusValues(), multiplyValues(), subtractValues(), UITextFieldBinding::updateValue, UILabelBinding::updateValue, and UIViewBinding::updateValue.
Property Documentation
- (NSObject*) owner read nonatomic strong
Definition at line 14 of file ObservablePropertyReference.h.
Referenced by callValue(), and initWithOwner:propertyName:.
- (NSString*) propertyName read nonatomic strong
Definition at line 15 of file ObservablePropertyReference.h.
Referenced by callValue().
- (NSObject *) value read nonatomic assign
Definition at line 16 of file ObservablePropertyReference.h.
Referenced by unwrap:.
The documentation for this class was generated from the following files:
/Users/nelliott/Documents/Projects/Kensho/ios/Kensho/Observables/ObservablePropertyReference.h
/Users/nelliott/Documents/Projects/Kensho/ios/Kensho/Observables/ObservablePropertyReference.m