Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/ldebug.h File Reference
ldebug.h File Reference
#include "lstate.h"
Macros
#define pcRel(pc, p) (cast(int, (pc) - (p)->code) - 1)
#define getfuncline(f, pc) (((f)->lineinfo) ? (f)->lineinfo[pc] : 0)
#define resethookcount(L) (L->hookcount = L->basehookcount)
#define ci_func(ci) (clLvalue((ci)->func))
Functions
LUAI_FUNC l_noret luaG_typeerror (lua_State *L, const TValue *o, const char *opname)
LUAI_FUNC l_noret luaG_concaterror (lua_State *L, StkId p1, StkId p2)
LUAI_FUNC l_noret luaG_aritherror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC l_noret luaG_ordererror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC l_noret luaG_runerror (lua_State *L, const char *fmt,...)
LUAI_FUNC l_noret luaG_errormsg (lua_State *L)
Macro Definition Documentation
#define ci_func (ci) (clLvalue((ci)->func))
Definition at line 21 of file ldebug.h.
Referenced by addinfo(), currentline(), currentpc(), findlocal(), getfuncname(), getupvalname(), luaG_typeerror(), and traceexec().
#define getfuncline (f, pc) (((f)->lineinfo) ? (f)->lineinfo[pc] : 0)
Definition at line 16 of file ldebug.h.
Referenced by currentline(), and traceexec().
#define pcRel (pc, p) (cast(int, (pc) - (p)->code) - 1)
Definition at line 14 of file ldebug.h.
Referenced by currentpc(), and traceexec().
#define resethookcount (L) (L->hookcount = L->basehookcount)
Definition at line 18 of file ldebug.h.
Referenced by lua_newthread(), lua_sethook(), preinit_state(), and traceexec().
Function Documentation
LUAI_FUNC l_noret luaG_aritherror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 539 of file ldebug.c.
References luaG_typeerror(), and luaV_tonumber().
Referenced by luaV_arith().
LUAI_FUNC l_noret luaG_concaterror (lua_State * L, StkId p1, StkId p2)
Definition at line 532 of file ldebug.c.
References lua_assert, luaG_typeerror(), ttisnumber, and ttisstring.
Referenced by luaV_concat().
LUAI_FUNC l_noret luaG_errormsg (lua_State * L)
Definition at line 573 of file ldebug.c.
References lua_State::errfunc, LUA_ERRERR, LUA_ERRRUN, luaD_call(), luaD_throw(), restorestack, setobjs2s, lua_State::top, and ttisfunction.
Referenced by lua_error(), and luaG_runerror().
LUAI_FUNC l_noret luaG_ordererror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 547 of file ldebug.c.
References luaG_runerror(), and objtypename.
Referenced by luaV_lessequal(), and luaV_lessthan().
LUAI_FUNC l_noret luaG_runerror (lua_State * L, const char * fmt, ...)
Definition at line 586 of file ldebug.c.
References addinfo(), luaG_errormsg(), and luaO_pushvfstring().
Referenced by findindex(), lua_pushnumber(), lua_yieldk(), luaD_call(), luaD_growstack(), luaG_ordererror(), luaG_typeerror(), luaH_newkey(), luaM_growaux_(), luaM_toobig(), luaO_pushvfstring(), luaV_concat(), luaV_execute(), luaV_gettable(), luaV_settable(), and setnodevector().
LUAI_FUNC l_noret luaG_typeerror (lua_State * L, const TValue * o, const char * opname)
Definition at line 513 of file ldebug.c.
References cast_int, lua_State::ci, ci_func, currentpc(), getobjname(), getupvalname(), isinstack(), isLua, CallInfo::l, LUA_QS, luaG_runerror(), objtypename, and CallInfo::u.
Referenced by luaG_aritherror(), luaG_concaterror(), luaV_gettable(), luaV_objlen(), luaV_settable(), and tryfuncTM().