Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lstring.c File Reference
lstring.c File Reference
#include <string.h>
#include "lua.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
Macros
#define lstring_c
#define LUA_CORE
#define LUAI_HASHLIMIT 5
Functions
int luaS_eqlngstr (TString *a, TString *b)
int luaS_eqstr (TString *a, TString *b)
unsigned int luaS_hash (const char *str, size_t l, unsigned int seed)
void luaS_resize (lua_State *L, int newsize)
static TString * createstrobj (lua_State *L, const char *str, size_t l, int tag, unsigned int h, GCObject **list)
static TString * newshrstr (lua_State *L, const char *str, size_t l, unsigned int h)
static TString * internshrstr (lua_State *L, const char *str, size_t l)
TString * luaS_newlstr (lua_State *L, const char *str, size_t l)
TString * luaS_new (lua_State *L, const char *str)
Udata * luaS_newudata (lua_State *L, size_t s, Table *e)
Macro Definition Documentation
#define lstring_c
Definition at line 10 of file lstring.c.
#define LUA_CORE
Definition at line 11 of file lstring.c.
#define LUAI_HASHLIMIT 5
Definition at line 26 of file lstring.c.
Referenced by luaS_hash().
Function Documentation
static TString* createstrobj (lua_State * L, const char * str, size_t l, int tag, unsigned int h, GCObject ** list) static
Definition at line 98 of file lstring.c.
References TString::extra, TString::hash, TString::len, luaC_newobj(), GCObject::ts, and TString::tsv.
Referenced by luaS_newlstr(), and newshrstr().
static TString* internshrstr (lua_State * L, const char * str, size_t l) static
Definition at line 133 of file lstring.c.
References changewhite, G, gch, getstr, stringtable::hash, TString::hash, isdead, TString::len, lmod, luaS_hash(), newshrstr(), next, rawgco2ts, global_State::seed, stringtable::size, global_State::strt, and TString::tsv.
Referenced by luaS_newlstr().
int luaS_eqlngstr (TString * a, TString * b)
Definition at line 33 of file lstring.c.
References getstr, TString::len, lua_assert, LUA_TLNGSTR, and TString::tsv.
Referenced by luaS_eqstr(), and luaV_equalobj_().
int luaS_eqstr (TString * a, TString * b)
Definition at line 45 of file lstring.c.
References eqshrstr, LUA_TSHRSTR, luaS_eqlngstr(), and TString::tsv.
Referenced by checkrepeated(), closegoto(), findgotos(), findlabel(), searchupvalue(), and searchvar().
unsigned int luaS_hash (const char * str, size_t l, unsigned int seed)
Definition at line 51 of file lstring.c.
References cast, cast_byte, and LUAI_HASHLIMIT.
Referenced by internshrstr(), mainposition(), and makeseed().
TString* luaS_new (lua_State * L, const char * str)
Definition at line 170 of file lstring.c.
References luaS_newlstr().
Referenced by breaklabel(), gotostat(), lua_getfield(), lua_getglobal(), lua_pushstring(), lua_setfield(), lua_setglobal(), luaT_init(), luaX_init(), luaX_setinput(), luaY_parser(), and resume_error().
TString* luaS_newlstr (lua_State * L, const char * str, size_t l)
Definition at line 156 of file lstring.c.
References createstrobj(), G, internshrstr(), LUA_TLNGSTR, LUAI_MAXSHORTLEN, luaM_toobig(), and MAX_SIZET.
Referenced by LoadString(), lua_concat(), lua_pushlstring(), luaK_numberK(), luaS_new(), luaV_concat(), luaV_tostring(), luaX_newstring(), and pushstr().
Udata* luaS_newudata (lua_State * L, size_t s, Table * e)
Definition at line 175 of file lstring.c.
References Udata::env, Udata::len, LUA_TUSERDATA, luaC_newobj(), luaM_toobig(), MAX_SIZET, Udata::metatable, GCObject::u, and Udata::uv.
Referenced by lua_newuserdata().
void luaS_resize (lua_State * L, int newsize)
Definition at line 64 of file lstring.c.
References bitmask, G, gch, gco2ts, GCSsweepstring, stringtable::hash, lmod, lua_assert, luaC_runtilstate(), luaM_reallocvector, next, resetoldbit, and stringtable::size.
Referenced by checkSizes(), f_luaopen(), and newshrstr().
static TString* newshrstr (lua_State * L, const char * str, size_t l, unsigned int h) static
Definition at line 116 of file lstring.c.
References cast, createstrobj(), G, stringtable::hash, lmod, LUA_TSHRSTR, luaS_resize(), MAX_INT, stringtable::nuse, and stringtable::size.
Referenced by internshrstr().