Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/llex.h File Reference
llex.h File Reference
#include "lobject.h"
#include "lzio.h"
Classes
union SemInfo
struct Token
struct LexState
Macros
#define FIRST_RESERVED 257
#define NUM_RESERVED (cast(int, TK_WHILE-FIRST_RESERVED+1))
Typedefs
typedef struct Token Token
typedef struct LexState LexState
Enumerations
enum RESERVED {
TK_AND = FIRST_RESERVED, TK_BREAK, TK_DO, TK_ELSE,
TK_ELSEIF, TK_END, TK_FALSE, TK_FOR,
TK_FUNCTION, TK_GOTO, TK_IF, TK_IN,
TK_LOCAL, TK_NIL, TK_NOT, TK_OR,
TK_REPEAT, TK_RETURN, TK_THEN, TK_TRUE,
TK_UNTIL, TK_WHILE, TK_CONCAT, TK_DOTS,
TK_EQ, TK_GE, TK_LE, TK_NE,
TK_DBCOLON, TK_EOS, TK_NUMBER, TK_NAME,
TK_STRING
}
Functions
LUAI_FUNC void luaX_init (lua_State *L)
LUAI_FUNC void luaX_setinput (lua_State *L, LexState *ls, ZIO *z, TString *source, int firstchar)
LUAI_FUNC TString * luaX_newstring (LexState *ls, const char *str, size_t l)
LUAI_FUNC void luaX_next (LexState *ls)
LUAI_FUNC int luaX_lookahead (LexState *ls)
LUAI_FUNC l_noret luaX_syntaxerror (LexState *ls, const char *s)
LUAI_FUNC const char * luaX_token2str (LexState *ls, int token)
Macro Definition Documentation
#define FIRST_RESERVED 257
Definition at line 14 of file llex.h.
Referenced by llex(), and luaX_token2str().
#define NUM_RESERVED (cast(int, TK_WHILE-FIRST_RESERVED+1))
Definition at line 34 of file llex.h.
Referenced by luaX_init().
Typedef Documentation
typedef struct LexState LexState
typedef struct Token Token
Enumeration Type Documentation
enum RESERVED
Enumerator
TK_AND
TK_BREAK
TK_DO
TK_ELSE
TK_ELSEIF
TK_END
TK_FALSE
TK_FOR
TK_FUNCTION
TK_GOTO
TK_IF
TK_IN
TK_LOCAL
TK_NIL
TK_NOT
TK_OR
TK_REPEAT
TK_RETURN
TK_THEN
TK_TRUE
TK_UNTIL
TK_WHILE
TK_CONCAT
TK_DOTS
TK_EQ
TK_GE
TK_LE
TK_NE
TK_DBCOLON
TK_EOS
TK_NUMBER
TK_NAME
TK_STRING
Definition at line 22 of file llex.h.
Function Documentation
LUAI_FUNC void luaX_init (lua_State * L)
Definition at line 65 of file llex.c.
References cast_byte, TString::extra, luaS_fix, luaS_new(), luaX_tokens, NUM_RESERVED, and TString::tsv.
Referenced by f_luaopen().
LUAI_FUNC int luaX_lookahead (LexState * ls)
Definition at line 525 of file llex.c.
References llex(), LexState::lookahead, lua_assert, Token::seminfo, TK_EOS, and Token::token.
Referenced by field().
LUAI_FUNC TString* luaX_newstring (LexState * ls, const char * str, size_t l)
Definition at line 124 of file llex.c.
References LexState::fs, FuncState::h, keyfromval, LexState::L, luaC_checkGC, luaH_set(), luaS_newlstr(), rawtsvalue, setbvalue, setsvalue2s, lua_State::top, and ttisnil.
Referenced by anchor_token(), llex(), new_localvarliteral_(), read_long_string(), and read_string().
LUAI_FUNC void luaX_next (LexState * ls)
Definition at line 514 of file llex.c.
References LexState::lastline, LexState::linenumber, llex(), LexState::lookahead, Token::seminfo, LexState::t, TK_EOS, and Token::token.
Referenced by checknext(), fieldsel(), forstat(), funcargs(), funcstat(), gotostat(), mainfunc(), parlist(), primaryexp(), repeatstat(), simpleexp(), statement(), str_checkname(), subexpr(), suffixedexp(), test_then_block(), testnext(), whilestat(), and yindex().
LUAI_FUNC void luaX_setinput (lua_State * L, LexState * ls, ZIO * z, TString * source, int firstchar)
Definition at line 159 of file llex.c.
References LexState::buff, LexState::current, LexState::decpoint, LexState::envn, LexState::fs, LexState::L, LexState::lastline, LexState::linenumber, LexState::lookahead, LUA_ENV, LUA_MINBUFFER, luaS_fix, luaS_new(), luaZ_resizebuffer, LexState::source, TK_EOS, Token::token, and LexState::z.
Referenced by luaY_parser().
LUAI_FUNC l_noret luaX_syntaxerror (LexState * ls, const char * s)
Definition at line 114 of file llex.c.
References lexerror(), LexState::t, and Token::token.
Referenced by check_match(), error_expected(), errorlimit(), fixjump(), forstat(), funcargs(), inclinenumber(), luaK_checkstack(), luaK_setlist(), parlist(), primaryexp(), and semerror().
LUAI_FUNC const char* luaX_token2str (LexState * ls, int token)
Definition at line 75 of file llex.c.
References cast, FIRST_RESERVED, LexState::L, lisprint, lua_assert, LUA_QL, LUA_QS, luaO_pushfstring(), luaX_tokens, and TK_EOS.
Referenced by check_match(), error_expected(), and txtToken().