Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lbitlib.c File Reference
lbitlib.c File Reference
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lbitlib_c
#define LUA_LIB
#define LUA_NBITS 32
#define ALLONES (~(((~(lua_Unsigned)0) << (LUA_NBITS - 1)) << 1))
#define trim(x) ((x) & ALLONES)
#define mask(n) (~((ALLONES << 1) << ((n) - 1)))
Typedefs
typedef lua_Unsigned b_uint
Functions
static b_uint andaux (lua_State *L)
static int b_and (lua_State *L)
static int b_test (lua_State *L)
static int b_or (lua_State *L)
static int b_xor (lua_State *L)
static int b_not (lua_State *L)
static int b_shift (lua_State *L, b_uint r, int i)
static int b_lshift (lua_State *L)
static int b_rshift (lua_State *L)
static int b_arshift (lua_State *L)
static int b_rot (lua_State *L, int i)
static int b_lrot (lua_State *L)
static int b_rrot (lua_State *L)
static int fieldargs (lua_State *L, int farg, int *width)
static int b_extract (lua_State *L)
static int b_replace (lua_State *L)
LUAMOD_API int luaopen_bit32 (lua_State *L)
Variables
static const luaL_Reg bitlib []
Macro Definition Documentation
#define ALLONES (~(((~(lua_Unsigned)0) << (LUA_NBITS - 1)) << 1))
Definition at line 22 of file lbitlib.c.
Referenced by b_arshift().
#define lbitlib_c
Definition at line 7 of file lbitlib.c.
#define LUA_LIB
Definition at line 8 of file lbitlib.c.
#define LUA_NBITS 32
Definition at line 18 of file lbitlib.c.
Referenced by b_arshift(), b_rot(), b_shift(), and fieldargs().
#define mask (n) (~((ALLONES << 1) << ((n) - 1)))
Definition at line 29 of file lbitlib.c.
Referenced by b_extract(), b_replace(), db_gethook(), db_sethook(), makemask(), and traceexec().
#define trim (x) ((x) & ALLONES)
Definition at line 25 of file lbitlib.c.
Referenced by andaux(), b_arshift(), b_not(), b_or(), b_rot(), b_shift(), and b_xor().
Typedef Documentation
typedef lua_Unsigned b_uint
Definition at line 32 of file lbitlib.c.
Function Documentation
static b_uint andaux (lua_State * L) static
Definition at line 36 of file lbitlib.c.
References lua_gettop(), luaL_checkunsigned(), and trim.
Referenced by b_and(), and b_test().
static int b_and (lua_State * L) static
Definition at line 45 of file lbitlib.c.
References andaux(), and lua_pushunsigned().
static int b_arshift (lua_State * L) static
Definition at line 113 of file lbitlib.c.
References ALLONES, b_shift(), LUA_NBITS, lua_pushunsigned(), luaL_checkint, luaL_checkunsigned(), and trim.
static int b_extract (lua_State * L) static
Definition at line 167 of file lbitlib.c.
References fieldargs(), lua_pushunsigned(), luaL_checkunsigned(), and mask.
static int b_lrot (lua_State * L) static
Definition at line 139 of file lbitlib.c.
References b_rot(), and luaL_checkint.
static int b_lshift (lua_State * L) static
Definition at line 103 of file lbitlib.c.
References b_shift(), luaL_checkint, and luaL_checkunsigned().
static int b_not (lua_State * L) static
Definition at line 79 of file lbitlib.c.
References lua_pushunsigned(), luaL_checkunsigned(), and trim.
static int b_or (lua_State * L) static
Definition at line 59 of file lbitlib.c.
References lua_gettop(), lua_pushunsigned(), luaL_checkunsigned(), and trim.
static int b_replace (lua_State * L) static
Definition at line 177 of file lbitlib.c.
References fieldargs(), lua_pushunsigned(), luaL_checkunsigned(), and mask.
static int b_rot (lua_State * L, int i) static
Definition at line 128 of file lbitlib.c.
References LUA_NBITS, lua_pushunsigned(), luaL_checkunsigned(), and trim.
Referenced by b_lrot(), and b_rrot().
static int b_rrot (lua_State * L) static
Definition at line 144 of file lbitlib.c.
References b_rot(), and luaL_checkint.
static int b_rshift (lua_State * L) static
Definition at line 108 of file lbitlib.c.
References b_shift(), luaL_checkint, and luaL_checkunsigned().
static int b_shift (lua_State * L, b_uint r, int i) static
Definition at line 86 of file lbitlib.c.
References LUA_NBITS, lua_pushunsigned(), and trim.
Referenced by b_arshift(), b_lshift(), and b_rshift().
static int b_test (lua_State * L) static
Definition at line 52 of file lbitlib.c.
References andaux(), and lua_pushboolean().
static int b_xor (lua_State * L) static
Definition at line 69 of file lbitlib.c.
References lua_gettop(), lua_pushunsigned(), luaL_checkunsigned(), and trim.
static int fieldargs (lua_State * L, int farg, int * width) static
Definition at line 155 of file lbitlib.c.
References LUA_NBITS, luaL_argcheck, luaL_checkint, luaL_error(), and luaL_optint.
Referenced by b_extract(), and b_replace().
LUAMOD_API int luaopen_bit32 (lua_State * L)
Definition at line 208 of file lbitlib.c.
References luaL_newlib.
Variable Documentation
const luaL_Reg bitlib[] static
Initial value:
= {
  {"arshift", b_arshift},
  {"band", b_and},
  {"bnot", b_not},
  {"bor", b_or},
  {"bxor", b_xor},
  {"btest", b_test},
  {"extract", b_extract},
  {"lrotate", b_lrot},
  {"lshift", b_lshift},
  {"replace", b_replace},
  {"rrotate", b_rrot},
  {"rshift", b_rshift},
  {NULL, NULL}
}
Definition at line 190 of file lbitlib.c.