Kensho: /Users/nelliott/Documents/Projects/Kensho/ios/Kensho/Utilities/KenshoLuaWrapper.m File Reference
KenshoLuaWrapper.m File Reference
#import "KenshoLuaWrapper.h"
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
#import "IObservable.h"
#import "NSObject+Observable.h"
#import "ObservablePropertyReference.h"
Functions
int lookupKey (lua_State *L)
This is executed when the LUA subsystem attempts to read data to from an index that it doesn't think exists.
int pushValue (lua_State *L, NSObject *value)
int addValues (lua_State *L)
int subtractValues (lua_State *L)
int multiplyValues (lua_State *L)
int divideValues (lua_State *L)
int exponentValues (lua_State *L)
int modulusValues (lua_State *L)
int concatValues (lua_State *L)
int equalsValues (lua_State *L)
int lessValues (lua_State *L)
int callValue (lua_State *L)
int pushValue (lua_State *L, ObservablePropertyReference *valueWrapper)
Push an NSObject-derived value onto the stack.
int pushLuaValue (lua_State *L, NSObject *value)
NSObject * popValue (lua_State *L, int stackLevel)
int lookupNewKey (lua_State *L)
This is executed when the LUA subsystem attempts to assign data to a new index.
Variables
NSMutableArray * valueWrappers
Function Documentation
int addValues (lua_State * L)
Definition at line 395 of file KenshoLuaWrapper.m.
References ObservablePropertyReference::unwrap:.
Referenced by pushValue().
int callValue (lua_State * L)
Todo:
support native-type returns, not just NSObject*s. This is a very complicated situation - see 'makeClassObservable' in NSObject+Observable.m
Definition at line 471 of file KenshoLuaWrapper.m.
References ObservablePropertyReference::owner, popValue(), ObservablePropertyReference::propertyName, and pushLuaValue().
Referenced by pushValue().
int concatValues (lua_State * L)
Definition at line 443 of file KenshoLuaWrapper.m.
References ObservablePropertyReference::unwrap:.
Referenced by pushValue().
int divideValues (lua_State * L)
Definition at line 419 of file KenshoLuaWrapper.m.
References ObservablePropertyReference::unwrap:.
Referenced by pushValue().
int equalsValues (lua_State * L)
Definition at line 451 of file KenshoLuaWrapper.m.
References ObservablePropertyReference::unwrap:.
Referenced by pushValue().
int exponentValues (lua_State * L)
Definition at line 427 of file KenshoLuaWrapper.m.
References ObservablePropertyReference::unwrap:.
Referenced by pushValue().
int lessValues (lua_State * L)
Definition at line 459 of file KenshoLuaWrapper.m.
References ObservablePropertyReference::unwrap:.
Referenced by pushValue().
int lookupKey (lua_State * L)
This is executed when the LUA subsystem attempts to read data to from an index that it doesn't think exists.
Parameters
L The LUA state object
Returns
0 on error, otherwise 1.
Todo:
Consider how to pass-through property references. This is important for two cases:
Tight binding to collections (eg, add an item, remove an item. re-order)
Two-way binding, to allow assignment
Knockout lets you specify a property name, eg value: 'myValue' (at least for items in a list) It would be nice if we could do this automagically, eg: value = my.value;
Definition at line 205 of file KenshoLuaWrapper.m.
References pushValue(), and ObservablePropertyReference::unwrap:.
Referenced by KenshoLuaWrapper::finalValue, pushLuaValue(), and pushValue().
int lookupNewKey (lua_State * L)
This is executed when the LUA subsystem attempts to assign data to a new index.
This will probably only be executed when our implicit result is assigned. Originally each parameter was being assigned at the top level, but now we'll get a 'table' back with the result data.
Parameters
L The LUA subsystem
Returns
0 if not handled (and nil is used in the LUA subsystem)
Definition at line 350 of file KenshoLuaWrapper.m.
References popValue(), and <KenshoValueParameters>::value.
Referenced by KenshoLuaWrapper::finalValue.
int modulusValues (lua_State * L)
Definition at line 435 of file KenshoLuaWrapper.m.
References ObservablePropertyReference::unwrap:.
Referenced by pushValue().
int multiplyValues (lua_State * L)
Definition at line 411 of file KenshoLuaWrapper.m.
References ObservablePropertyReference::unwrap:.
Referenced by pushValue().
NSObject* popValue (lua_State * L, int stackLevel)
Definition at line 257 of file KenshoLuaWrapper.m.
References <KenshoValueParameters>::value.
Referenced by callValue(), and lookupNewKey().
int pushLuaValue (lua_State * L, NSObject * value)
Definition at line 153 of file KenshoLuaWrapper.m.
References lookupKey(), and <KenshoValueParameters>::value.
Referenced by callValue().
int pushValue (lua_State * L, NSObject * value)
Referenced by lookupKey().
int pushValue (lua_State * L, ObservablePropertyReference * valueWrapper)
Push an NSObject-derived value onto the stack.
Parameters
L <#L description#>
value <#value description#>
Returns
0 on error, otherwise 1.
Definition at line 95 of file KenshoLuaWrapper.m.
References addValues(), callValue(), concatValues(), divideValues(), equalsValues(), exponentValues(), lessValues(), lookupKey(), modulusValues(), multiplyValues(), and subtractValues().
int subtractValues (lua_State * L)
Definition at line 403 of file KenshoLuaWrapper.m.
References ObservablePropertyReference::unwrap:.
Referenced by pushValue().
Variable Documentation
NSMutableArray* valueWrappers
Definition at line 72 of file KenshoLuaWrapper.m.
Referenced by KenshoLuaWrapper::initWithKensho:context:code:.