Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lparser.h File Reference
lparser.h File Reference
#include "llimits.h"
#include "lobject.h"
#include "lzio.h"
Classes
struct expdesc
struct Vardesc
struct Labeldesc
struct Labellist
struct Dyndata
struct FuncState
Macros
#define vkisvar(k) (VLOCAL <= (k) && (k) <= VINDEXED)
#define vkisinreg(k) ((k) == VNONRELOC || (k) == VLOCAL)
Typedefs
typedef struct expdesc expdesc
typedef struct Vardesc Vardesc
typedef struct Labeldesc Labeldesc
typedef struct Labellist Labellist
typedef struct Dyndata Dyndata
typedef struct FuncState FuncState
Enumerations
enum expkind {
VVOID, VNIL, VTRUE, VFALSE,
VK, VKNUM, VNONRELOC, VLOCAL,
VUPVAL, VINDEXED, VJMP, VRELOCABLE,
VCALL, VVARARG
}
Functions
LUAI_FUNC Closure * luaY_parser (lua_State *L, ZIO *z, Mbuffer *buff, Dyndata *dyd, const char *name, int firstchar)
Macro Definition Documentation
#define vkisinreg (k) ((k) == VNONRELOC || (k) == VLOCAL)
Definition at line 38 of file lparser.h.
Referenced by luaK_indexed().
#define vkisvar (k) (VLOCAL <= (k) && (k) <= VINDEXED)
Definition at line 37 of file lparser.h.
Referenced by assignment().
Typedef Documentation
typedef struct Dyndata Dyndata
typedef struct expdesc expdesc
typedef struct FuncState FuncState
typedef struct Labeldesc Labeldesc
typedef struct Labellist Labellist
typedef struct Vardesc Vardesc
Enumeration Type Documentation
enum expkind
Enumerator
VVOID
VNIL
VTRUE
VFALSE
VK
VKNUM
VNONRELOC
VLOCAL
VUPVAL
VINDEXED
VJMP
VRELOCABLE
VCALL
VVARARG
Definition at line 19 of file lparser.h.
Function Documentation
LUAI_FUNC Closure* luaY_parser (lua_State * L, ZIO * z, Mbuffer * buff, Dyndata * dyd, const char * name, int firstchar)
Definition at line 1618 of file lparser.c.
References Dyndata::actvar, LexState::buff, LexState::dyd, FuncState::f, LexState::fs, Dyndata::gt, incr_top, Closure::l, Dyndata::label, lua_assert, luaF_newLclosure(), luaF_newproto(), luaS_new(), luaX_setinput(), mainfunc(), Labellist::n, Dyndata::n, FuncState::nups, LClosure::p, FuncState::prev, setclLvalue, Proto::source, and lua_State::top.
Referenced by f_parser().