Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lua.h File Reference
lua.h File Reference
#include <stdarg.h>
#include <stddef.h>
#include "luaconf.h"
Classes
struct lua_Debug
Macros
#define LUA_VERSION_MAJOR "5"
#define LUA_VERSION_MINOR "2"
#define LUA_VERSION_NUM 502
#define LUA_VERSION_RELEASE "3"
#define LUA_VERSION "Lua " LUA_VERSION_MAJOR "." LUA_VERSION_MINOR
#define LUA_RELEASE LUA_VERSION "." LUA_VERSION_RELEASE
#define LUA_COPYRIGHT LUA_RELEASE " Copyright (C) 1994-2013 Lua.org, PUC-Rio"
#define LUA_AUTHORS "R. Ierusalimschy, L. H. de Figueiredo, W. Celes"
#define LUA_SIGNATURE "\033Lua"
#define LUA_MULTRET (-1)
#define LUA_REGISTRYINDEX LUAI_FIRSTPSEUDOIDX
#define lua_upvalueindex(i) (LUA_REGISTRYINDEX - (i))
#define LUA_OK 0
#define LUA_YIELD 1
#define LUA_ERRRUN 2
#define LUA_ERRSYNTAX 3
#define LUA_ERRMEM 4
#define LUA_ERRGCMM 5
#define LUA_ERRERR 6
#define LUA_TNONE (-1)
#define LUA_TNIL 0
#define LUA_TBOOLEAN 1
#define LUA_TLIGHTUSERDATA 2
#define LUA_TNUMBER 3
#define LUA_TSTRING 4
#define LUA_TTABLE 5
#define LUA_TFUNCTION 6
#define LUA_TUSERDATA 7
#define LUA_TTHREAD 8
#define LUA_NUMTAGS 9
#define LUA_MINSTACK 20
#define LUA_RIDX_MAINTHREAD 1
#define LUA_RIDX_GLOBALS 2
#define LUA_RIDX_LAST LUA_RIDX_GLOBALS
#define LUA_OPADD 0 /* ORDER TM */
#define LUA_OPSUB 1
#define LUA_OPMUL 2
#define LUA_OPDIV 3
#define LUA_OPMOD 4
#define LUA_OPPOW 5
#define LUA_OPUNM 6
#define LUA_OPEQ 0
#define LUA_OPLT 1
#define LUA_OPLE 2
#define lua_call(L, n, r) lua_callk(L, (n), (r), 0, NULL)
#define lua_pcall(L, n, r, f) lua_pcallk(L, (n), (r), (f), 0, NULL)
#define lua_yield(L, n) lua_yieldk(L, (n), 0, NULL)
#define LUA_GCSTOP 0
#define LUA_GCRESTART 1
#define LUA_GCCOLLECT 2
#define LUA_GCCOUNT 3
#define LUA_GCCOUNTB 4
#define LUA_GCSTEP 5
#define LUA_GCSETPAUSE 6
#define LUA_GCSETSTEPMUL 7
#define LUA_GCSETMAJORINC 8
#define LUA_GCISRUNNING 9
#define LUA_GCGEN 10
#define LUA_GCINC 11
#define lua_tonumber(L, i) lua_tonumberx(L,i,NULL)
#define lua_tointeger(L, i) lua_tointegerx(L,i,NULL)
#define lua_tounsigned(L, i) lua_tounsignedx(L,i,NULL)
#define lua_pop(L, n) lua_settop(L, -(n)-1)
#define lua_newtable(L) lua_createtable(L, 0, 0)
#define lua_register(L, n, f) (lua_pushcfunction(L, (f)), lua_setglobal(L, (n)))
#define lua_pushcfunction(L, f) lua_pushcclosure(L, (f), 0)
#define lua_isfunction(L, n) (lua_type(L, (n)) == LUA_TFUNCTION)
#define lua_istable(L, n) (lua_type(L, (n)) == LUA_TTABLE)
#define lua_islightuserdata(L, n) (lua_type(L, (n)) == LUA_TLIGHTUSERDATA)
#define lua_isnil(L, n) (lua_type(L, (n)) == LUA_TNIL)
#define lua_isboolean(L, n) (lua_type(L, (n)) == LUA_TBOOLEAN)
#define lua_isthread(L, n) (lua_type(L, (n)) == LUA_TTHREAD)
#define lua_isnone(L, n) (lua_type(L, (n)) == LUA_TNONE)
#define lua_isnoneornil(L, n) (lua_type(L, (n)) <= 0)
#define lua_pushliteral(L, s) lua_pushlstring(L, "" s, (sizeof(s)/sizeof(char))-1)
#define lua_pushglobaltable(L) lua_rawgeti(L, LUA_REGISTRYINDEX, LUA_RIDX_GLOBALS)
#define lua_tostring(L, i) lua_tolstring(L, (i), NULL)
#define LUA_HOOKCALL 0
#define LUA_HOOKRET 1
#define LUA_HOOKLINE 2
#define LUA_HOOKCOUNT 3
#define LUA_HOOKTAILCALL 4
#define LUA_MASKCALL (1 << LUA_HOOKCALL)
#define LUA_MASKRET (1 << LUA_HOOKRET)
#define LUA_MASKLINE (1 << LUA_HOOKLINE)
#define LUA_MASKCOUNT (1 << LUA_HOOKCOUNT)
Typedefs
typedef struct lua_State lua_State
typedef int(* lua_CFunction)(lua_State *L)
typedef const char *(* lua_Reader)(lua_State *L, void *ud, size_t *sz)
typedef int(* lua_Writer)(lua_State *L, const void *p, size_t sz, void *ud)
typedef void *(* lua_Alloc)(void *ud, void *ptr, size_t osize, size_t nsize)
typedef LUA_NUMBER lua_Number
typedef LUA_INTEGER lua_Integer
typedef LUA_UNSIGNED lua_Unsigned
typedef struct lua_Debug lua_Debug
typedef void(* lua_Hook)(lua_State *L, lua_Debug *ar)
Functions
LUA_API lua_State *() lua_newstate (lua_Alloc f, void *ud)
LUA_API void() lua_close (lua_State *L)
LUA_API lua_State *() lua_newthread (lua_State *L)
LUA_API lua_CFunction() lua_atpanic (lua_State *L, lua_CFunction panicf)
LUA_API const lua_Number *() lua_version (lua_State *L)
LUA_API int() lua_absindex (lua_State *L, int idx)
LUA_API int() lua_gettop (lua_State *L)
LUA_API void() lua_settop (lua_State *L, int idx)
LUA_API void() lua_pushvalue (lua_State *L, int idx)
LUA_API void() lua_remove (lua_State *L, int idx)
LUA_API void() lua_insert (lua_State *L, int idx)
LUA_API void() lua_replace (lua_State *L, int idx)
LUA_API void() lua_copy (lua_State *L, int fromidx, int toidx)
LUA_API int() lua_checkstack (lua_State *L, int sz)
LUA_API void() lua_xmove (lua_State *from, lua_State *to, int n)
LUA_API int() lua_isnumber (lua_State *L, int idx)
LUA_API int() lua_isstring (lua_State *L, int idx)
LUA_API int() lua_iscfunction (lua_State *L, int idx)
LUA_API int() lua_isuserdata (lua_State *L, int idx)
LUA_API int() lua_type (lua_State *L, int idx)
LUA_API const char *() lua_typename (lua_State *L, int tp)
LUA_API lua_Number() lua_tonumberx (lua_State *L, int idx, int *isnum)
LUA_API lua_Integer() lua_tointegerx (lua_State *L, int idx, int *isnum)
LUA_API lua_Unsigned() lua_tounsignedx (lua_State *L, int idx, int *isnum)
LUA_API int() lua_toboolean (lua_State *L, int idx)
LUA_API const char *() lua_tolstring (lua_State *L, int idx, size_t *len)
LUA_API size_t() lua_rawlen (lua_State *L, int idx)
LUA_API lua_CFunction() lua_tocfunction (lua_State *L, int idx)
LUA_API void *() lua_touserdata (lua_State *L, int idx)
LUA_API lua_State *() lua_tothread (lua_State *L, int idx)
LUA_API const void *() lua_topointer (lua_State *L, int idx)
LUA_API void() lua_arith (lua_State *L, int op)
LUA_API int() lua_rawequal (lua_State *L, int idx1, int idx2)
LUA_API int() lua_compare (lua_State *L, int idx1, int idx2, int op)
LUA_API void() lua_pushnil (lua_State *L)
LUA_API void() lua_pushnumber (lua_State *L, lua_Number n)
LUA_API void() lua_pushinteger (lua_State *L, lua_Integer n)
LUA_API void() lua_pushunsigned (lua_State *L, lua_Unsigned n)
LUA_API const char *() lua_pushlstring (lua_State *L, const char *s, size_t l)
LUA_API const char *() lua_pushstring (lua_State *L, const char *s)
LUA_API const char *() lua_pushvfstring (lua_State *L, const char *fmt, va_list argp)
LUA_API const char *() lua_pushfstring (lua_State *L, const char *fmt,...)
LUA_API void() lua_pushcclosure (lua_State *L, lua_CFunction fn, int n)
LUA_API void() lua_pushboolean (lua_State *L, int b)
LUA_API void() lua_pushlightuserdata (lua_State *L, void *p)
LUA_API int() lua_pushthread (lua_State *L)
LUA_API void() lua_getglobal (lua_State *L, const char *var)
LUA_API void() lua_gettable (lua_State *L, int idx)
LUA_API void() lua_getfield (lua_State *L, int idx, const char *k)
LUA_API void() lua_rawget (lua_State *L, int idx)
LUA_API void() lua_rawgeti (lua_State *L, int idx, int n)
LUA_API void() lua_rawgetp (lua_State *L, int idx, const void *p)
LUA_API void() lua_createtable (lua_State *L, int narr, int nrec)
LUA_API void *() lua_newuserdata (lua_State *L, size_t sz)
LUA_API int() lua_getmetatable (lua_State *L, int objindex)
LUA_API void() lua_getuservalue (lua_State *L, int idx)
LUA_API void() lua_setglobal (lua_State *L, const char *var)
LUA_API void() lua_settable (lua_State *L, int idx)
LUA_API void() lua_setfield (lua_State *L, int idx, const char *k)
LUA_API void() lua_rawset (lua_State *L, int idx)
LUA_API void() lua_rawseti (lua_State *L, int idx, int n)
LUA_API void() lua_rawsetp (lua_State *L, int idx, const void *p)
LUA_API int() lua_setmetatable (lua_State *L, int objindex)
LUA_API void() lua_setuservalue (lua_State *L, int idx)
LUA_API void() lua_callk (lua_State *L, int nargs, int nresults, int ctx, lua_CFunction k)
LUA_API int() lua_getctx (lua_State *L, int *ctx)
LUA_API int() lua_pcallk (lua_State *L, int nargs, int nresults, int errfunc, int ctx, lua_CFunction k)
LUA_API int() lua_load (lua_State *L, lua_Reader reader, void *dt, const char *chunkname, const char *mode)
LUA_API int() lua_dump (lua_State *L, lua_Writer writer, void *data)
LUA_API int() lua_yieldk (lua_State *L, int nresults, int ctx, lua_CFunction k)
LUA_API int() lua_resume (lua_State *L, lua_State *from, int narg)
LUA_API int() lua_status (lua_State *L)
LUA_API int() lua_gc (lua_State *L, int what, int data)
LUA_API int() lua_error (lua_State *L)
LUA_API int() lua_next (lua_State *L, int idx)
LUA_API void() lua_concat (lua_State *L, int n)
LUA_API void() lua_len (lua_State *L, int idx)
LUA_API lua_Alloc() lua_getallocf (lua_State *L, void **ud)
LUA_API void() lua_setallocf (lua_State *L, lua_Alloc f, void *ud)
LUA_API int() lua_getstack (lua_State *L, int level, lua_Debug *ar)
LUA_API int() lua_getinfo (lua_State *L, const char *what, lua_Debug *ar)
LUA_API const char *() lua_getlocal (lua_State *L, const lua_Debug *ar, int n)
LUA_API const char *() lua_setlocal (lua_State *L, const lua_Debug *ar, int n)
LUA_API const char *() lua_getupvalue (lua_State *L, int funcindex, int n)
LUA_API const char *() lua_setupvalue (lua_State *L, int funcindex, int n)
LUA_API void *() lua_upvalueid (lua_State *L, int fidx, int n)
LUA_API void() lua_upvaluejoin (lua_State *L, int fidx1, int n1, int fidx2, int n2)
LUA_API int() lua_sethook (lua_State *L, lua_Hook func, int mask, int count)
LUA_API lua_Hook() lua_gethook (lua_State *L)
LUA_API int() lua_gethookmask (lua_State *L)
LUA_API int() lua_gethookcount (lua_State *L)
Variables
const char lua_ident []
Macro Definition Documentation
#define LUA_AUTHORS "R. Ierusalimschy, L. H. de Figueiredo, W. Celes"
Definition at line 27 of file lua.h.
#define lua_call (L, n, r) lua_callk(L, (n), (r), 0, NULL)
Definition at line 253 of file lua.h.
Referenced by add_value(), findloader(), generic_reader(), hookf(), ll_require(), luaB_print(), luaL_callmeta(), luaL_requiref(), pairsmeta(), and sort_comp().
#define LUA_COPYRIGHT LUA_RELEASE " Copyright (C) 1994-2013 Lua.org, PUC-Rio"
Definition at line 26 of file lua.h.
#define LUA_ERRERR 6
Definition at line 51 of file lua.h.
Referenced by luaD_call(), luaD_growstack(), luaG_errormsg(), and seterrorobj().
#define LUA_ERRGCMM 5
Definition at line 50 of file lua.h.
Referenced by GCTM().
#define LUA_ERRMEM 4
Definition at line 49 of file lua.h.
Referenced by luaM_realloc_(), and seterrorobj().
#define LUA_ERRRUN 2
Definition at line 47 of file lua.h.
Referenced by GCTM(), lua_resume(), and luaG_errormsg().
#define LUA_ERRSYNTAX 3
Definition at line 48 of file lua.h.
Referenced by checkmode(), error(), and lexerror().
#define LUA_GCCOLLECT 2
Definition at line 283 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCCOUNT 3
Definition at line 284 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCCOUNTB 4
Definition at line 285 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCGEN 10
Definition at line 291 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCINC 11
Definition at line 292 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCISRUNNING 9
Definition at line 290 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCRESTART 1
Definition at line 282 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCSETMAJORINC 8
Definition at line 289 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCSETPAUSE 6
Definition at line 287 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCSETSTEPMUL 7
Definition at line 288 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCSTEP 5
Definition at line 286 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_GCSTOP 0
Definition at line 281 of file lua.h.
Referenced by lua_gc(), and luaB_collectgarbage().
#define LUA_HOOKCALL 0
Definition at line 360 of file lua.h.
Referenced by callhook(), and luaD_precall().
#define LUA_HOOKCOUNT 3
Definition at line 363 of file lua.h.
Referenced by traceexec().
#define LUA_HOOKLINE 2
Definition at line 362 of file lua.h.
Referenced by traceexec().
#define LUA_HOOKRET 1
Definition at line 361 of file lua.h.
Referenced by luaD_poscall().
#define LUA_HOOKTAILCALL 4
Definition at line 364 of file lua.h.
Referenced by callhook().
#define lua_isboolean (L, n) (lua_type(L, (n)) == LUA_TBOOLEAN)
Definition at line 335 of file lua.h.
Referenced by os_exit(), and popValue().
#define lua_isfunction (L, n) (lua_type(L, (n)) == LUA_TFUNCTION)
Definition at line 331 of file lua.h.
Referenced by db_getinfo(), db_getlocal(), findloader(), and hookf().
#define lua_islightuserdata (L, n) (lua_type(L, (n)) == LUA_TLIGHTUSERDATA)
Definition at line 333 of file lua.h.
#define lua_isnil (L, n) (lua_type(L, (n)) == LUA_TNIL)
Definition at line 334 of file lua.h.
Referenced by findloader(), generic_reader(), getboolfield(), io_lines(), io_readline(), ipairsaux(), ll_require(), luaL_getmetafield(), luaL_newmetatable(), luaL_ref(), searcher_preload(), and sort_comp().
#define lua_isnone (L, n) (lua_type(L, (n)) == LUA_TNONE)
Definition at line 337 of file lua.h.
Referenced by io_close(), io_lines(), luaB_load(), and luaB_loadfile().
#define lua_isnoneornil (L, n) (lua_type(L, (n)) <= 0)
Definition at line 338 of file lua.h.
Referenced by db_sethook(), db_setuservalue(), db_traceback(), g_iofile(), luaB_tonumber(), luaL_optlstring(), math_log(), os_time(), and sort().
#define lua_istable (L, n) (lua_type(L, (n)) == LUA_TTABLE)
Definition at line 332 of file lua.h.
Referenced by findfield(), findloader(), lookupKey(), lookupNewKey(), luaL_getsubtable(), popValue(), and pushValue().
#define lua_isthread (L, n) (lua_type(L, (n)) == LUA_TTHREAD)
Definition at line 336 of file lua.h.
Referenced by getthread().
#define LUA_MASKCALL (1 << LUA_HOOKCALL)
Definition at line 370 of file lua.h.
Referenced by luaD_precall(), makemask(), and unmakemask().
#define LUA_MASKCOUNT (1 << LUA_HOOKCOUNT)
Definition at line 373 of file lua.h.
Referenced by luaV_execute(), makemask(), and traceexec().
#define LUA_MASKLINE (1 << LUA_HOOKLINE)
Definition at line 372 of file lua.h.
Referenced by luaD_poscall(), luaV_execute(), makemask(), traceexec(), and unmakemask().
#define LUA_MASKRET (1 << LUA_HOOKRET)
Definition at line 371 of file lua.h.
Referenced by luaD_poscall(), makemask(), and unmakemask().
#define LUA_MINSTACK 20
Definition at line 93 of file lua.h.
Referenced by aux_lines(), g_read(), luaD_hook(), luaD_precall(), luaL_checkstack(), and stack_init().
#define LUA_MULTRET (-1)
Definition at line 34 of file lua.h.
Referenced by funcargs(), lastlistfield(), luaB_dofile(), luaB_pcall(), luaB_xpcall(), luaD_poscall(), luaK_setlist(), luaV_execute(), resume(), and retstat().
#define lua_newtable (L) lua_createtable(L, 0, 0)
Definition at line 325 of file lua.h.
Referenced by KenshoLuaWrapper::evaluate, luaL_getsubtable(), and luaL_newmetatable().
#define LUA_NUMTAGS 9
Definition at line 88 of file lua.h.
Referenced by lua_newstate(), and markmt().
#define LUA_OK 0
Definition at line 45 of file lua.h.
Referenced by auxresume(), finishCcall(), GCTM(), load_aux(), lua_callk(), lua_checkstack(), lua_getctx(), lua_load(), lua_newstate(), lua_pcallk(), lua_resume(), luaB_costatus(), luaB_dofile(), luaB_pcall(), luaB_xpcall(), luaD_pcall(), luaD_rawrunprotected(), preinit_state(), resume(), and searcher_Lua().
#define LUA_OPADD 0 /* ORDER TM */
Definition at line 184 of file lua.h.
Referenced by constfolding(), lua_arith(), luaO_arith(), and luaV_arith().
#define LUA_OPDIV 3
Definition at line 187 of file lua.h.
Referenced by luaO_arith().
#define LUA_OPEQ 0
Definition at line 194 of file lua.h.
Referenced by lua_compare().
#define LUA_OPLE 2
Definition at line 196 of file lua.h.
Referenced by lua_compare().
#define LUA_OPLT 1
Definition at line 195 of file lua.h.
Referenced by lua_compare(), and sort_comp().
#define LUA_OPMOD 4
Definition at line 188 of file lua.h.
Referenced by luaO_arith().
#define LUA_OPMUL 2
Definition at line 186 of file lua.h.
Referenced by luaO_arith().
#define LUA_OPPOW 5
Definition at line 189 of file lua.h.
Referenced by luaO_arith().
#define LUA_OPSUB 1
Definition at line 185 of file lua.h.
Referenced by luaO_arith().
#define LUA_OPUNM 6
Definition at line 190 of file lua.h.
Referenced by lua_arith(), and luaO_arith().
#define lua_pcall (L, n, r, f) lua_pcallk(L, (n), (r), (f), 0, NULL)
Definition at line 259 of file lua.h.
Referenced by db_debug(), and KenshoLuaWrapper::evaluate.
#define lua_pop (L, n) lua_settop(L, -(n)-1)
Definition at line 323 of file lua.h.
Referenced by add_value(), auxresume(), auxsort(), createmeta(), createmetatable(), KenshoLuaWrapper::evaluate, findfield(), findloader(), g_read(), gctm(), generic_reader(), getboolfield(), getfield(), ll_addtoclib(), ll_checkclib(), ll_require(), load_aux(), lookupNewKey(), luaB_print(), luaL_checkversion_(), luaL_getmetafield(), luaL_getsubtable(), luaL_len(), luaL_newmetatable(), luaL_openlibs(), luaL_ref(), luaL_requiref(), luaL_setfuncs(), luaL_testudata(), luaopen_package(), noenv(), popValue(), pushglobalfuncname(), sort_comp(), and str_format().
#define lua_pushcfunction (L, f) lua_pushcclosure(L, (f), 0)
Definition at line 329 of file lua.h.
Referenced by KenshoLuaWrapper::evaluate, ll_loadfunc(), luaL_openlibs(), luaL_requiref(), luaopen_package(), pairsmeta(), and pushValue().
#define lua_pushglobaltable (L) lua_rawgeti(L, LUA_REGISTRYINDEX, LUA_RIDX_GLOBALS)
Definition at line 343 of file lua.h.
Referenced by KenshoLuaWrapper::evaluate, luaopen_base(), luaopen_package(), and pushglobalfuncname().
#define lua_pushliteral (L, s) lua_pushlstring(L, "" s, (sizeof(s)/sizeof(char))-1)
Definition at line 340 of file lua.h.
Referenced by auxresume(), createmetatable(), db_gethook(), f_tostring(), findfield(), io_noclose(), io_type(), ll_load(), ll_sym(), luaB_costatus(), luaL_loadfilex(), luaL_tolstring(), luaL_traceback(), luaL_where(), luaopen_base(), luaopen_package(), pushfuncname(), str_rep(), and str_sub().
#define lua_register (L, n, f) (lua_pushcfunction(L, (f)), lua_setglobal(L, (n)))
Definition at line 327 of file lua.h.
#define LUA_REGISTRYINDEX LUAI_FIRSTPSEUDOIDX
Definition at line 40 of file lua.h.
Referenced by createstdfile(), db_getregistry(), g_iofile(), getiofile(), index2addr(), io_close(), io_lines(), ll_addtoclib(), ll_checkclib(), ll_require(), luaL_newmetatable(), luaL_openlibs(), luaL_requiref(), luaopen_package(), moveto(), noenv(), and searcher_preload().
#define LUA_RELEASE LUA_VERSION "." LUA_VERSION_RELEASE
Definition at line 25 of file lua.h.
#define LUA_RIDX_GLOBALS 2
Definition at line 98 of file lua.h.
Referenced by init_registry(), lua_getglobal(), lua_load(), and lua_setglobal().
#define LUA_RIDX_LAST LUA_RIDX_GLOBALS
Definition at line 99 of file lua.h.
Referenced by init_registry().
#define LUA_RIDX_MAINTHREAD 1
Definition at line 97 of file lua.h.
Referenced by init_registry().
#define LUA_SIGNATURE "\033Lua"
Definition at line 31 of file lua.h.
Referenced by f_parser(), luaL_loadfilex(), luaU_header(), and luaU_undump().
#define LUA_TBOOLEAN 1
Definition at line 79 of file lua.h.
Referenced by DumpConstants(), LoadConstants(), luaL_tolstring(), luaV_equalobj_(), and mainposition().
#define LUA_TFUNCTION 6
Definition at line 84 of file lua.h.
Referenced by add_value(), auxupvalue(), checkupval(), db_sethook(), luaB_cocreate(), luaB_load(), sort(), str_dump(), and str_gsub().
#define LUA_TLIGHTUSERDATA 2
Definition at line 80 of file lua.h.
Referenced by db_setuservalue(), lua_topointer(), lua_touserdata(), luaV_equalobj_(), and mainposition().
#define LUA_TNIL 0
Definition at line 78 of file lua.h.
Referenced by db_setmetatable(), DumpConstants(), LoadConstants(), luaB_setmetatable(), luaH_get(), luaL_tolstring(), and luaV_equalobj_().
#define LUA_TNONE (-1)
Definition at line 76 of file lua.h.
Referenced by lua_type(), and luaL_checkany().
#define LUA_TNUMBER 3
Definition at line 81 of file lua.h.
Referenced by DumpConstants(), g_read(), g_write(), LoadConstants(), lua_isstring(), luaH_get(), luaL_checkinteger(), luaL_checknumber(), luaL_checkunsigned(), luaL_tolstring(), luaV_equalobj_(), mainposition(), and str_gsub().
#define lua_tointeger (L, i) lua_tointegerx(L,i,NULL)
Definition at line 320 of file lua.h.
Referenced by db_getinfo(), g_read(), gmatch_aux(), io_readline(), luaL_checkversion_(), and luaL_ref().
#define lua_tonumber (L, i) lua_tonumberx(L,i,NULL)
Definition at line 319 of file lua.h.
Referenced by g_write(), and popValue().
#define lua_tostring (L, i) lua_tolstring(L, (i), NULL)
Definition at line 346 of file lua.h.
Referenced by checkload(), db_debug(), db_getinfo(), db_traceback(), errfile(), findfile(), findloader(), g_iofile(), g_read(), io_readline(), lookupKey(), lookupNewKey(), luaB_select(), luaL_argerror(), luaL_gsub(), luaL_loadfilex(), panic(), popValue(), pushfuncname(), searcher_Croot(), and searchpath().
#define lua_tounsigned (L, i) lua_tounsignedx(L,i,NULL)
Definition at line 321 of file lua.h.
Referenced by luaL_checkversion_().
#define LUA_TSTRING 4
Definition at line 82 of file lua.h.
Referenced by DumpConstants(), findfield(), LoadConstants(), lua_isstring(), lua_rawlen(), luaB_rawlen(), luaB_select(), luaL_checklstring(), luaL_tolstring(), luaV_objlen(), and str_gsub().
#define LUA_TTABLE 5
Definition at line 83 of file lua.h.
Referenced by add_value(), db_setmetatable(), db_setuservalue(), freeobj(), ipairsaux(), lua_getmetatable(), lua_rawlen(), lua_setmetatable(), lua_topointer(), luaB_next(), luaB_rawget(), luaB_rawlen(), luaB_rawset(), luaB_setmetatable(), luaC_barrier_(), luaC_barrierback_(), luaH_new(), luaT_gettmbyobj(), luaV_equalobj_(), luaV_objlen(), os_time(), pairsmeta(), propagatemark(), reallymarkobject(), str_gsub(), tconcat(), and unpack().
#define LUA_TTHREAD 8
Definition at line 86 of file lua.h.
Referenced by freeobj(), lua_newstate(), lua_newthread(), lua_topointer(), propagatemark(), reallymarkobject(), and sweeplist().
#define LUA_TUSERDATA 7
Definition at line 85 of file lua.h.
Referenced by db_getuservalue(), db_setuservalue(), freeobj(), lua_getmetatable(), lua_rawlen(), lua_setmetatable(), lua_topointer(), lua_touserdata(), luaS_newudata(), luaT_gettmbyobj(), luaV_equalobj_(), and reallymarkobject().
#define lua_upvalueindex (i) (LUA_REGISTRYINDEX - (i))
Definition at line 41 of file lua.h.
Referenced by findfile(), findloader(), gmatch_aux(), io_readline(), and luaB_auxwrap().
#define LUA_VERSION "Lua " LUA_VERSION_MAJOR "." LUA_VERSION_MINOR
Definition at line 24 of file lua.h.
Referenced by luaopen_base().
#define LUA_VERSION_MAJOR "5"
Definition at line 19 of file lua.h.
#define LUA_VERSION_MINOR "2"
Definition at line 20 of file lua.h.
#define LUA_VERSION_NUM 502
Definition at line 21 of file lua.h.
Referenced by lua_version().
#define LUA_VERSION_RELEASE "3"
Definition at line 22 of file lua.h.
#define LUA_YIELD 1
Definition at line 46 of file lua.h.
Referenced by auxresume(), finishCcall(), lua_resume(), lua_yieldk(), luaB_costatus(), pcallcont(), resume(), and traceexec().
#define lua_yield (L, n) lua_yieldk(L, (n), 0, NULL)
Definition at line 273 of file lua.h.
Referenced by luaB_yield().
Typedef Documentation
typedef void*(* lua_Alloc)(void *ud, void *ptr, size_t osize, size_t nsize)
Definition at line 70 of file lua.h.
typedef int(* lua_CFunction)(lua_State *L)
Definition at line 56 of file lua.h.
typedef struct lua_Debug lua_Debug
Definition at line 375 of file lua.h.
typedef void(* lua_Hook)(lua_State *L, lua_Debug *ar)
Definition at line 379 of file lua.h.
typedef LUA_INTEGER lua_Integer
Definition at line 107 of file lua.h.
typedef LUA_NUMBER lua_Number
Definition at line 103 of file lua.h.
typedef const char*(* lua_Reader)(lua_State *L, void *ud, size_t *sz)
Definition at line 62 of file lua.h.
typedef struct lua_State lua_State
Definition at line 54 of file lua.h.
typedef LUA_UNSIGNED lua_Unsigned
Definition at line 110 of file lua.h.
typedef int(* lua_Writer)(lua_State *L, const void *p, size_t sz, void *ud)
Definition at line 64 of file lua.h.
Function Documentation
LUA_API int() lua_absindex (lua_State * L, int idx)
Definition at line 153 of file lapi.c.
References cast_int, lua_State::ci, CallInfo::func, ispseudo, and lua_State::top.
Referenced by luaL_callmeta(), luaL_getsubtable(), luaL_ref(), and luaL_unref().
LUA_API void() lua_arith (lua_State * L, int op)
Definition at line 293 of file lapi.c.
References api_checknelems, cast, lua_lock, LUA_OPADD, LUA_OPUNM, lua_unlock, luaO_arith(), luaV_arith(), nvalue, setnvalue, setobjs2s, TM_ADD, lua_State::top, and ttisnumber.
LUA_API lua_CFunction() lua_atpanic (lua_State * L, lua_CFunction panicf)
Definition at line 127 of file lapi.c.
References G, lua_lock, and lua_unlock.
Referenced by luaL_newstate().
LUA_API void() lua_callk (lua_State * L, int nargs, int nresults, int ctx, lua_CFunction k)
Definition at line 889 of file lapi.c.
References adjustresults, api_check, api_checknelems, CallInfo::c, checkresults, lua_State::ci, isLua, lua_lock, LUA_OK, lua_unlock, luaD_call(), lua_State::nny, lua_State::status, lua_State::top, and CallInfo::u.
Referenced by luaB_dofile().
LUA_API int() lua_checkstack (lua_State * L, int sz)
Definition at line 92 of file lapi.c.
References cast_int, lua_State::ci, EXTRA_STACK, growstack(), lua_lock, LUA_OK, lua_unlock, luaD_rawrunprotected(), LUAI_MAXSTACK, lua_State::stack, lua_State::stack_last, CallInfo::top, and lua_State::top.
Referenced by auxresume(), finishpcall(), luaL_checkstack(), and unpack().
LUA_API void() lua_close (lua_State * L)
Definition at line 317 of file lstate.c.
References close_state(), G, and lua_lock.
Referenced by os_exit().
LUA_API int() lua_compare (lua_State * L, int idx1, int idx2, int op)
Definition at line 316 of file lapi.c.
References api_check, equalobj, index2addr(), isvalid, lua_lock, LUA_OPEQ, LUA_OPLE, LUA_OPLT, lua_unlock, luaV_lessequal(), and luaV_lessthan().
Referenced by sort_comp().
LUA_API void() lua_concat (lua_State * L, int n)
Definition at line 1131 of file lapi.c.
References api_checknelems, api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaS_newlstr(), luaV_concat(), setsvalue2s, and lua_State::top.
Referenced by findfield(), luaB_auxwrap(), luaB_error(), luaL_error(), and luaL_traceback().
LUA_API void() lua_copy (lua_State * L, int fromidx, int toidx)
Definition at line 226 of file lapi.c.
References index2addr(), lua_lock, lua_unlock, and moveto().
Referenced by luaB_xpcall(), and pushglobalfuncname().
LUA_API void() lua_createtable (lua_State * L, int narr, int nrec)
Definition at line 673 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaH_new(), luaH_resize(), sethvalue, and lua_State::top.
Referenced by createmetatable(), createsearcherstable(), db_getinfo(), luaopen_package(), os_date(), pack(), and pushValue().
LUA_API int() lua_dump (lua_State * L, lua_Writer writer, void * data)
Definition at line 997 of file lapi.c.
References api_checknelems, getproto, isLfunction, lua_lock, lua_unlock, luaU_dump(), and lua_State::top.
Referenced by str_dump().
LUA_API int() lua_error (lua_State * L)
Definition at line 1105 of file lapi.c.
References api_checknelems, lua_lock, and luaG_errormsg().
Referenced by luaB_auxwrap(), luaB_dofile(), luaB_error(), and luaL_error().
LUA_API int() lua_gc (lua_State * L, int what, int data)
Definition at line 1021 of file lapi.c.
References cast, cast_int, G, global_State::GCdebt, global_State::GCestimate, global_State::gckind, global_State::gcmajorinc, global_State::gcpause, global_State::gcrunning, GCSpause, global_State::gcstate, global_State::gcstepmul, GCSTEPSIZE, gettotalbytes, KGC_GEN, KGC_NORMAL, LUA_GCCOLLECT, LUA_GCCOUNT, LUA_GCCOUNTB, LUA_GCGEN, LUA_GCINC, LUA_GCISRUNNING, LUA_GCRESTART, LUA_GCSETMAJORINC, LUA_GCSETPAUSE, LUA_GCSETSTEPMUL, LUA_GCSTEP, LUA_GCSTOP, lua_lock, lua_unlock, luaC_changemode(), luaC_forcestep(), luaC_fullgc(), and luaE_setdebt().
Referenced by luaB_collectgarbage().
LUA_API lua_Alloc() lua_getallocf (lua_State * L, void ** ud)
Definition at line 1157 of file lapi.c.
References G, lua_lock, and lua_unlock.
LUA_API int() lua_getctx (lua_State * L, int * ctx)
Definition at line 880 of file lapi.c.
References CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_YIELDED, LUA_OK, and CallInfo::u.
Referenced by pcallcont().
LUA_API void() lua_getfield (lua_State * L, int idx, const char * k)
Definition at line 628 of file lapi.c.
References api_incr_top, index2addr(), lua_lock, lua_unlock, luaS_new(), luaV_gettable(), setsvalue2s, and lua_State::top.
Referenced by findfile(), findloader(), g_iofile(), getboolfield(), getfield(), getiofile(), io_close(), io_lines(), ll_addtoclib(), ll_checkclib(), ll_require(), lookupKey(), lookupNewKey(), luaL_getsubtable(), luaopen_table(), noenv(), popValue(), and searcher_preload().
LUA_API void() lua_getglobal (lua_State * L, const char * var)
Definition at line 608 of file lapi.c.
References G, hvalue, lua_lock, LUA_RIDX_GLOBALS, lua_unlock, luaH_getint(), luaS_new(), luaV_gettable(), setsvalue2s, and lua_State::top.
Referenced by luaB_print().
LUA_API lua_Hook() lua_gethook (lua_State * L)
Definition at line 68 of file ldebug.c.
References lua_State::hook.
Referenced by db_gethook().
LUA_API int() lua_gethookcount (lua_State * L)
Definition at line 78 of file ldebug.c.
References lua_State::basehookcount.
Referenced by db_gethook().
LUA_API int() lua_gethookmask (lua_State * L)
Definition at line 73 of file ldebug.c.
References lua_State::hookmask.
Referenced by db_gethook().
LUA_API int() lua_getinfo (lua_State * L, const char * what, lua_Debug * ar)
Definition at line 266 of file ldebug.c.
References api_check, api_incr_top, auxgetinfo(), clvalue, collectvalidlines(), CallInfo::func, lua_Debug::i_ci, lua_assert, lua_lock, lua_unlock, setobjs2s, lua_State::top, ttisclosure, and ttisfunction.
Referenced by checkupval(), db_getinfo(), hookf(), luaL_argerror(), luaL_traceback(), luaL_where(), and pushglobalfuncname().
LUA_API const char*() lua_getlocal (lua_State * L, const lua_Debug * ar, int n)
Definition at line 144 of file ldebug.c.
References api_incr_top, clLvalue, findlocal(), lua_Debug::i_ci, isLfunction, lua_lock, lua_unlock, luaF_getlocalname(), setobj2s, and lua_State::top.
Referenced by db_getlocal().
LUA_API int() lua_getmetatable (lua_State * L, int objindex)
Definition at line 686 of file lapi.c.
References api_incr_top, G, hvalue, index2addr(), lua_lock, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, sethvalue, lua_State::top, ttypenv, and uvalue.
Referenced by db_getmetatable(), luaB_getmetatable(), luaL_getmetafield(), and luaL_testudata().
LUA_API int() lua_getstack (lua_State * L, int level, lua_Debug * ar)
Definition at line 83 of file ldebug.c.
References lua_State::base_ci, lua_State::ci, lua_Debug::i_ci, lua_lock, lua_unlock, and CallInfo::previous.
Referenced by countlevels(), db_getinfo(), db_getlocal(), db_setlocal(), luaB_costatus(), luaL_argerror(), luaL_traceback(), and luaL_where().
LUA_API void() lua_gettable (lua_State * L, int idx)
Definition at line 619 of file lapi.c.
References index2addr(), lua_lock, lua_unlock, luaV_gettable(), and lua_State::top.
Referenced by add_value().
LUA_API int() lua_gettop (lua_State * L)
Definition at line 160 of file lapi.c.
References cast_int, lua_State::ci, CallInfo::func, and lua_State::top.
Referenced by andaux(), aux_lines(), auxresume(), b_or(), b_xor(), dofilecont(), finishpcall(), g_read(), g_write(), luaB_assert(), luaB_auxwrap(), luaB_coresume(), luaB_costatus(), luaB_pcall(), luaB_print(), luaB_select(), luaB_xpcall(), luaB_yield(), luaL_loadfilex(), luaL_traceback(), math_max(), math_min(), math_random(), pack(), pushglobalfuncname(), str_char(), str_format(), and tinsert().
LUA_API const char*() lua_getupvalue (lua_State * L, int funcindex, int n)
Definition at line 1213 of file lapi.c.
References api_incr_top, aux_upvalue(), index2addr(), lua_lock, lua_unlock, setobj2s, and lua_State::top.
Referenced by auxupvalue().
LUA_API void() lua_getuservalue (lua_State * L, int idx)
Definition at line 715 of file lapi.c.
References api_check, api_incr_top, index2addr(), lua_lock, lua_unlock, sethvalue, setnilvalue, lua_State::top, ttisuserdata, and uvalue.
Referenced by db_getuservalue().
LUA_API void() lua_insert (lua_State * L, int idx)
Definition at line 193 of file lapi.c.
References api_checkstackindex, index2addr(), lua_lock, lua_unlock, setobjs2s, and lua_State::top.
Referenced by auxupvalue(), findfield(), ll_loadlib(), ll_require(), ll_searchpath(), load_aux(), luaB_auxwrap(), luaB_coresume(), luaB_pcall(), and luaL_addvalue().
LUA_API int() lua_iscfunction (lua_State * L, int idx)
Definition at line 261 of file lapi.c.
References index2addr(), ttisCclosure, and ttislcf.
Referenced by db_upvaluejoin().
LUA_API int() lua_isnumber (lua_State * L, int idx)
Definition at line 267 of file lapi.c.
References index2addr(), and tonumber.
Referenced by db_getinfo(), popValue(), and pushValue().
LUA_API int() lua_isstring (lua_State * L, int idx)
Definition at line 274 of file lapi.c.
References LUA_TNUMBER, LUA_TSTRING, and lua_type().
Referenced by add_value(), addfield(), findloader(), generic_reader(), lookupKey(), lookupNewKey(), luaB_auxwrap(), luaB_error(), and popValue().
LUA_API int() lua_isuserdata (lua_State * L, int idx)
Definition at line 280 of file lapi.c.
References index2addr(), ttislightuserdata, and ttisuserdata.
LUA_API void() lua_len (lua_State * L, int idx)
Definition at line 1147 of file lapi.c.
References api_incr_top, index2addr(), lua_lock, lua_unlock, luaV_objlen(), and lua_State::top.
Referenced by luaL_len().
LUA_API int() lua_load (lua_State * L, lua_Reader reader, void * dt, const char * chunkname, const char * mode)
Definition at line 973 of file lapi.c.
References clLvalue, G, hvalue, lua_lock, LUA_OK, LUA_RIDX_GLOBALS, lua_unlock, luaC_barrier, luaD_protectedparser(), luaH_getint(), luaZ_init(), setobj, lua_State::top, LClosure::upvals, and UpVal::v.
Referenced by luaB_load(), luaL_loadbufferx(), and luaL_loadfilex().
LUA_API lua_State*() lua_newstate (lua_Alloc f, void * ud)
Definition at line 266 of file lstate.c.
References global_State::allgc, global_State::allweak, bit2mask, global_State::buff, cast, close_state(), global_State::currentwhite, global_State::ephemeron, f_luaopen(), global_State::finobj, FIXEDBIT, global_State::frealloc, LG::g, global_State::GCdebt, global_State::GCestimate, global_State::gckind, global_State::gcmajorinc, global_State::gcpause, global_State::gcrunning, GCSpause, global_State::gcstate, global_State::gcstepmul, global_State::gray, global_State::grayagain, stringtable::hash, KGC_NORMAL, LX::l, LG::l, UpVal::l, global_State::l_registry, LUA_NUMTAGS, LUA_OK, LUA_TTHREAD, luaC_white, luaD_rawrunprotected(), LUAI_GCMAJOR, LUAI_GCMUL, LUAI_GCPAUSE, luaZ_initbuffer, global_State::mainthread, makeseed(), global_State::mt, stringtable::nuse, global_State::panic, preinit_state(), global_State::seed, setnilvalue, stringtable::size, global_State::strt, global_State::sweepfin, global_State::sweepgc, global_State::tobefnz, global_State::totalbytes, UpVal::u, global_State::ud, global_State::uvhead, global_State::version, global_State::weak, and WHITE0BIT.
Referenced by luaL_newstate(), and makeseed().
LUA_API lua_State*() lua_newthread (lua_State * L)
Definition at line 237 of file lstate.c.
References api_incr_top, lua_State::basehookcount, G, lua_State::hook, lua_State::hookmask, lua_lock, LUA_TTHREAD, lua_unlock, luaC_checkGC, luaC_newobj(), luai_userstatethread, preinit_state(), resethookcount, setthvalue, stack_init(), GCObject::th, and lua_State::top.
Referenced by luaB_cocreate().
LUA_API void*() lua_newuserdata (lua_State * L, size_t sz)
Definition at line 1175 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, luaC_checkGC, luaS_newudata(), setuvalue, and lua_State::top.
Referenced by luaL_prepbuffsize(), newprefile(), and pushValue().
LUA_API int() lua_next (lua_State * L, int idx)
Definition at line 1114 of file lapi.c.
References api_check, api_incr_top, hvalue, index2addr(), lua_lock, lua_unlock, luaH_next(), lua_State::top, and ttistable.
Referenced by findfield(), luaB_next(), and popValue().
LUA_API int() lua_pcallk (lua_State * L, int nargs, int nresults, int errfunc, int ctx, lua_CFunction k)
Definition at line 928 of file lapi.c.
References adjustresults, lua_State::allowhook, api_check, api_checknelems, api_checkstackindex, CallInfo::c, CallInfo::callstatus, checkresults, lua_State::ci, CIST_YPCALL, lua_State::errfunc, CallInfo::extra, f_call(), CallS::func, index2addr(), isLua, lua_lock, LUA_OK, lua_unlock, luaD_call(), luaD_pcall(), lua_State::nny, CallS::nresults, savestack, lua_State::status, lua_State::top, and CallInfo::u.
Referenced by luaB_pcall(), and luaB_xpcall().
LUA_API void() lua_pushboolean (lua_State * L, int b)
Definition at line 577 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, setbvalue, and lua_State::top.
Referenced by aux_lines(), b_test(), finishpcall(), ll_loadfunc(), ll_require(), luaB_collectgarbage(), luaB_coresume(), luaB_corunning(), luaB_rawequal(), luaL_execresult(), luaL_fileresult(), os_execute(), setboolfield(), and settabsb().
LUA_API void() lua_pushcclosure (lua_State * L, lua_CFunction fn, int n)
Definition at line 555 of file lapi.c.
References api_check, api_checknelems, api_incr_top, Closure::c, CClosure::f, lua_lock, lua_unlock, luaC_checkGC, luaF_newCclosure(), MAXUPVAL, setclCvalue, setfvalue, setobj2n, lua_State::top, and CClosure::upvalue.
Referenced by aux_lines(), createsearcherstable(), gmatch(), luaB_cowrap(), and luaL_setfuncs().
LUA_API const char*() lua_pushfstring (lua_State * L, const char * fmt, ...)
Definition at line 542 of file lapi.c.
References lua_lock, lua_unlock, luaC_checkGC, and luaO_pushvfstring().
Referenced by checkoption(), db_getinfo(), errfile(), f_tostring(), loadfunc(), luaL_checkoption(), luaL_fileresult(), luaL_loadfilex(), luaL_tolstring(), luaL_traceback(), luaL_where(), pushfuncname(), searcher_Croot(), searcher_preload(), searchpath(), and typeerror().
LUA_API void() lua_pushinteger (lua_State * L, lua_Integer n)
Definition at line 483 of file lapi.c.
References api_incr_top, cast_num, lua_lock, lua_unlock, setnvalue, and lua_State::top.
Referenced by aux_lines(), db_gethook(), gmatch(), gmatch_aux(), hookf(), ipairsaux(), luaB_collectgarbage(), luaB_rawlen(), luaB_select(), luaL_execresult(), luaL_fileresult(), luaL_unref(), math_frexp(), pack(), pairsmeta(), push_onecapture(), setfield(), settabsi(), str_byte(), str_find_aux(), str_gsub(), and str_len().
LUA_API void() lua_pushlightuserdata (lua_State * L, void * p)
Definition at line 585 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, setpvalue, and lua_State::top.
Referenced by db_upvalueid(), KenshoLuaWrapper::evaluate, ll_addtoclib(), and pushValue().
LUA_API const char*() lua_pushlstring (lua_State * L, const char * s, size_t l)
Definition at line 501 of file lapi.c.
References api_incr_top, getstr, lua_lock, lua_unlock, luaC_checkGC, luaS_newlstr(), setsvalue2s, and lua_State::top.
Referenced by add_value(), loadfunc(), luaL_pushresult(), push_onecapture(), pushnexttemplate(), searcher_Croot(), str_sub(), and test_eof().
LUA_API void() lua_pushnil (lua_State * L)
Definition at line 465 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, setnilvalue, and lua_State::top.
Referenced by db_getinfo(), db_getlocal(), db_getmetatable(), db_getuservalue(), findfield(), g_read(), hookf(), io_lines(), io_noclose(), io_type(), ll_loadlib(), ll_searchpath(), load_aux(), lua_pushstring(), luaB_getmetatable(), luaB_next(), luaB_pcall(), luaB_tonumber(), luaL_execresult(), luaL_fileresult(), os_date(), os_time(), pairsmeta(), read_number(), str_find_aux(), and tremove().
LUA_API void() lua_pushnumber (lua_State * L, lua_Number n)
Definition at line 473 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, luaG_runerror(), luai_checknum, setnvalue, and lua_State::top.
Referenced by f_seek(), luaB_collectgarbage(), luaB_tonumber(), luaL_checkversion_(), luaopen_math(), math_abs(), math_acos(), math_asin(), math_atan(), math_atan2(), math_ceil(), math_cos(), math_cosh(), math_deg(), math_exp(), math_floor(), math_fmod(), math_frexp(), math_ldexp(), math_log(), math_max(), math_min(), math_modf(), math_pow(), math_rad(), math_random(), math_sin(), math_sinh(), math_sqrt(), math_tan(), math_tanh(), os_clock(), os_difftime(), os_time(), pushValue(), and read_number().
LUA_API const char*() lua_pushstring (lua_State * L, const char * s)
Definition at line 513 of file lapi.c.
References api_incr_top, getstr, lua_lock, lua_pushnil(), lua_unlock, luaC_checkGC, luaS_new(), setsvalue2s, and lua_State::top.
Referenced by auxupvalue(), checkload(), db_gethook(), db_getlocal(), db_sethook(), db_setlocal(), KenshoLuaWrapper::evaluate, findloader(), finishpcall(), hookf(), ll_loadlib(), ll_require(), luaB_type(), luaL_execresult(), luaL_fileresult(), luaL_getmetafield(), luaL_requiref(), luaL_tolstring(), os_getenv(), os_setlocale(), os_tmpname(), pushValue(), searcher_Croot(), setpath(), and settabss().
LUA_API int() lua_pushthread (lua_State * L)
Definition at line 593 of file lapi.c.
References api_incr_top, G, lua_lock, lua_unlock, setthvalue, and lua_State::top.
Referenced by db_gethook(), db_sethook(), hookf(), and luaB_corunning().
LUA_API void() lua_pushunsigned (lua_State * L, lua_Unsigned n)
Definition at line 491 of file lapi.c.
References api_incr_top, lua_lock, lua_unlock, lua_unsigned2number, setnvalue, and lua_State::top.
Referenced by b_and(), b_arshift(), b_extract(), b_not(), b_or(), b_replace(), b_rot(), b_shift(), and b_xor().
LUA_API void() lua_pushvalue (lua_State * L, int idx)
Definition at line 235 of file lapi.c.
References api_incr_top, index2addr(), lua_lock, lua_unlock, setobj2s, and lua_State::top.
Referenced by add_value(), aux_lines(), auxsort(), checkupval(), createmeta(), createmetatable(), createsearcherstable(), createstdfile(), db_getinfo(), db_getlocal(), db_getregistry(), db_sethook(), db_traceback(), f_write(), g_iofile(), generic_reader(), io_readline(), ll_addtoclib(), ll_require(), load_aux(), luaB_cocreate(), luaB_error(), luaB_print(), luaB_xpcall(), luaL_callmeta(), luaL_getsubtable(), luaL_newmetatable(), luaL_requiref(), luaL_setfuncs(), luaL_tolstring(), luaopen_package(), pack(), pairsmeta(), sort_comp(), and treatstackoption().
LUA_API const char*() lua_pushvfstring (lua_State * L, const char * fmt, va_list argp)
Definition at line 531 of file lapi.c.
References lua_lock, lua_unlock, luaC_checkGC, and luaO_pushvfstring().
Referenced by luaL_error().
LUA_API int() lua_rawequal (lua_State * L, int idx1, int idx2)
Definition at line 286 of file lapi.c.
References index2addr(), isvalid, and luaV_rawequalobj.
Referenced by findfield(), luaB_rawequal(), and luaL_testudata().
LUA_API void() lua_rawget (lua_State * L, int idx)
Definition at line 639 of file lapi.c.
References api_check, hvalue, index2addr(), lua_lock, lua_unlock, luaH_get(), setobj2s, lua_State::top, and ttistable.
Referenced by db_gethook(), hookf(), luaB_rawget(), and luaL_getmetafield().
LUA_API void() lua_rawgeti (lua_State * L, int idx, int n)
Definition at line 649 of file lapi.c.
References api_check, api_incr_top, hvalue, index2addr(), lua_lock, lua_unlock, luaH_getint(), setobj2s, lua_State::top, and ttistable.
Referenced by addfield(), auxsort(), findloader(), gctm(), ipairsaux(), luaL_ref(), luaL_unref(), tinsert(), tremove(), and unpack().
LUA_API void() lua_rawgetp (lua_State * L, int idx, const void * p)
Definition at line 660 of file lapi.c.
References api_check, api_incr_top, cast, hvalue, index2addr(), lua_lock, lua_unlock, luaH_get(), setobj2s, setpvalue, lua_State::top, and ttistable.
LUA_API size_t() lua_rawlen (lua_State * L, int idx)
Definition at line 407 of file lapi.c.
References hvalue, index2addr(), LUA_TSTRING, LUA_TTABLE, LUA_TUSERDATA, luaH_getn(), tsvalue, ttypenv, and uvalue.
Referenced by luaB_rawlen(), luaL_ref(), and read_line().
LUA_API void() lua_rawset (lua_State * L, int idx)
Definition at line 770 of file lapi.c.
References api_check, api_checknelems, gcvalue, hvalue, index2addr(), invalidateTMcache, lua_lock, lua_unlock, luaC_barrierback, luaH_set(), setobj2t, lua_State::top, and ttistable.
Referenced by db_sethook(), and luaB_rawset().
LUA_API void() lua_rawseti (lua_State * L, int idx, int n)
Definition at line 784 of file lapi.c.
References api_check, api_checknelems, gcvalue, hvalue, index2addr(), lua_lock, lua_unlock, luaC_barrierback, luaH_setint(), lua_State::top, and ttistable.
Referenced by createsearcherstable(), ll_addtoclib(), luaL_ref(), luaL_unref(), pack(), set2(), tinsert(), and tremove().
LUA_API void() lua_rawsetp (lua_State * L, int idx, const void * p)
Definition at line 797 of file lapi.c.
References api_check, api_checknelems, cast, gcvalue, hvalue, index2addr(), lua_lock, lua_unlock, luaC_barrierback, luaH_set(), setobj2t, setpvalue, lua_State::top, and ttistable.
LUA_API void() lua_remove (lua_State * L, int idx)
Definition at line 182 of file lapi.c.
References api_checkstackindex, index2addr(), lua_lock, lua_unlock, setobjs2s, and lua_State::top.
Referenced by db_gethook(), errfile(), findfield(), luaL_addvalue(), luaL_getmetafield(), luaL_loadfilex(), luaL_prepbuffsize(), luaL_pushresult(), pushfuncname(), searchpath(), setpath(), and treatstackoption().
LUA_API void() lua_replace (lua_State * L, int idx)
Definition at line 217 of file lapi.c.
References api_checknelems, lua_lock, lua_unlock, moveto(), and lua_State::top.
Referenced by finishpcall(), generic_reader(), gmatch_aux(), io_lines(), luaB_xpcall(), and pack().
LUA_API int() lua_resume (lua_State * L, lua_State * from, int narg)
Definition at line 535 of file ldo.c.
References api_checknelems, cast_byte, lua_State::ci, lua_assert, LUA_ERRRUN, lua_lock, LUA_OK, lua_unlock, LUA_YIELD, luaD_rawrunprotected(), luai_userstateresume, lua_State::nCcalls, lua_State::nny, recover(), resume(), seterrorobj(), lua_longjmp::status, lua_State::status, CallInfo::top, lua_State::top, and unroll().
Referenced by auxresume().
LUA_API void() lua_setallocf (lua_State * L, lua_Alloc f, void * ud)
Definition at line 1167 of file lapi.c.
References G, lua_lock, and lua_unlock.
LUA_API void() lua_setfield (lua_State * L, int idx, const char * k)
Definition at line 758 of file lapi.c.
References api_checknelems, index2addr(), lua_lock, lua_unlock, luaS_new(), luaV_settable(), setsvalue2s, and lua_State::top.
Referenced by createmeta(), createmetatable(), createstdfile(), db_sethook(), g_iofile(), ll_addtoclib(), ll_require(), luaL_getsubtable(), luaL_newmetatable(), luaL_openlibs(), luaL_requiref(), luaL_setfuncs(), luaopen_base(), luaopen_math(), luaopen_package(), pack(), pushValue(), setboolfield(), setfield(), setpath(), settabsb(), settabsi(), settabss(), and treatstackoption().
LUA_API void() lua_setglobal (lua_State * L, const char * var)
Definition at line 734 of file lapi.c.
References api_checknelems, G, hvalue, lua_lock, LUA_RIDX_GLOBALS, lua_unlock, luaH_getint(), luaS_new(), luaV_settable(), setsvalue2s, and lua_State::top.
Referenced by KenshoLuaWrapper::evaluate, luaL_requiref(), and luaopen_table().
LUA_API int() lua_sethook (lua_State * L, lua_Hook func, int mask, int count)
Definition at line 53 of file ldebug.c.
References lua_State::basehookcount, cast_byte, lua_State::ci, lua_State::hook, lua_State::hookmask, isLua, CallInfo::l, lua_State::oldpc, resethookcount, and CallInfo::u.
Referenced by db_sethook().
LUA_API const char*() lua_setlocal (lua_State * L, const lua_Debug * ar, int n)
Definition at line 166 of file ldebug.c.
References findlocal(), lua_Debug::i_ci, lua_lock, lua_unlock, setobjs2s, and lua_State::top.
Referenced by db_setlocal().
LUA_API int() lua_setmetatable (lua_State * L, int objindex)
Definition at line 812 of file lapi.c.
References api_check, api_checknelems, G, gcvalue, hvalue, index2addr(), lua_lock, LUA_TTABLE, LUA_TUSERDATA, lua_unlock, luaC_checkfinalizer(), luaC_objbarrier, luaC_objbarrierback, rawuvalue, lua_State::top, ttisnil, ttistable, ttypenv, and uvalue.
Referenced by createmetatable(), db_sethook(), db_setmetatable(), KenshoLuaWrapper::evaluate, luaB_setmetatable(), luaL_setmetatable(), luaopen_package(), and pushValue().
LUA_API void() lua_settable (lua_State * L, int idx)
Definition at line 747 of file lapi.c.
References api_checknelems, index2addr(), lua_lock, lua_unlock, luaV_settable(), and lua_State::top.
Referenced by KenshoLuaWrapper::evaluate, and pushValue().
LUA_API void() lua_settop (lua_State * L, int idx)
Definition at line 165 of file lapi.c.
References api_check, lua_State::ci, CallInfo::func, lua_lock, lua_unlock, setnilvalue, and lua_State::top.
Referenced by db_debug(), db_sethook(), db_setlocal(), db_setmetatable(), db_setuservalue(), finishpcall(), gmatch(), io_readline(), ll_require(), luaB_dofile(), luaB_error(), luaB_load(), luaB_next(), luaB_rawget(), luaB_rawset(), luaB_setmetatable(), luaL_loadfilex(), os_time(), pushglobalfuncname(), sort(), and str_dump().
LUA_API const char*() lua_setupvalue (lua_State * L, int funcindex, int n)
Definition at line 1227 of file lapi.c.
References api_checknelems, aux_upvalue(), index2addr(), lua_lock, lua_unlock, luaC_barrier, setobj, and lua_State::top.
Referenced by auxupvalue(), and load_aux().
LUA_API void() lua_setuservalue (lua_State * L, int idx)
Definition at line 852 of file lapi.c.
References api_check, api_checknelems, gcvalue, hvalue, index2addr(), lua_lock, lua_unlock, luaC_objbarrier, lua_State::top, ttisnil, ttistable, ttisuserdata, and uvalue.
Referenced by db_setuservalue().
LUA_API int() lua_status (lua_State * L)
Definition at line 1012 of file lapi.c.
References lua_State::status.
Referenced by auxresume(), and luaB_costatus().
LUA_API int() lua_toboolean (lua_State * L, int idx)
Definition at line 383 of file lapi.c.
References index2addr(), and l_isfalse.
Referenced by add_value(), getboolfield(), io_readline(), ll_require(), luaB_assert(), luaL_tolstring(), noenv(), os_exit(), popValue(), sort_comp(), and str_find_aux().
LUA_API lua_CFunction() lua_tocfunction (lua_State * L, int idx)
Definition at line 418 of file lapi.c.
References clCvalue, fvalue, index2addr(), ttisCclosure, and ttislcf.
LUA_API lua_Integer() lua_tointegerx (lua_State * L, int idx, int * isnum)
Definition at line 349 of file lapi.c.
References index2addr(), lua_number2integer, nvalue, and tonumber.
Referenced by getfield(), luaL_checkinteger(), and luaL_len().
LUA_API const char*() lua_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 389 of file lapi.c.
References index2addr(), lua_lock, lua_unlock, luaC_checkGC, luaV_tostring(), svalue, tsvalue, and ttisstring.
Referenced by add_s(), generic_reader(), gmatch_aux(), luaB_load(), luaB_print(), luaL_addvalue(), luaL_checklstring(), and luaL_tolstring().
LUA_API lua_Number() lua_tonumberx (lua_State * L, int idx, int * isnum)
Definition at line 335 of file lapi.c.
References index2addr(), nvalue, and tonumber.
Referenced by luaB_tonumber(), and luaL_checknumber().
LUA_API const void*() lua_topointer (lua_State * L, int idx)
Definition at line 443 of file lapi.c.
References cast, clCvalue, clLvalue, fvalue, hvalue, index2addr(), LUA_TCCL, LUA_TLCF, LUA_TLCL, LUA_TLIGHTUSERDATA, lua_touserdata(), LUA_TTABLE, LUA_TTHREAD, LUA_TUSERDATA, thvalue, and ttype.
Referenced by luaL_tolstring().
LUA_API lua_State*() lua_tothread (lua_State * L, int idx)
Definition at line 437 of file lapi.c.
References index2addr(), thvalue, and ttisthread.
Referenced by getthread(), luaB_auxwrap(), luaB_coresume(), and luaB_costatus().
LUA_API lua_Unsigned() lua_tounsignedx (lua_State * L, int idx, int * isnum)
Definition at line 366 of file lapi.c.
References index2addr(), lua_number2unsigned, nvalue, and tonumber.
Referenced by luaL_checkunsigned().
LUA_API void*() lua_touserdata (lua_State * L, int idx)
Definition at line 427 of file lapi.c.
References index2addr(), LUA_TLIGHTUSERDATA, LUA_TUSERDATA, pvalue, rawuvalue, and ttypenv.
Referenced by gctm(), getiofile(), io_readline(), ll_checkclib(), lookupKey(), lookupNewKey(), lua_topointer(), luaL_testudata(), and popValue().
LUA_API int() lua_type (lua_State * L, int idx)
Definition at line 249 of file lapi.c.
References index2addr(), isvalid, LUA_TNONE, and ttypenv.
Referenced by db_getuservalue(), db_setmetatable(), db_setuservalue(), findfield(), g_read(), g_write(), lua_isstring(), luaB_rawlen(), luaB_select(), luaB_setmetatable(), luaL_checkany(), luaL_checktype(), luaL_tolstring(), popValue(), and str_gsub().
LUA_API const char*() lua_typename (lua_State * L, int tp)
Definition at line 255 of file lapi.c.
References ttypename, and UNUSED.
Referenced by popValue(), and tag_error().
LUA_API void*() lua_upvalueid (lua_State * L, int fidx, int n)
Definition at line 1257 of file lapi.c.
References api_check, clCvalue, getupvalref(), index2addr(), LUA_TCCL, LUA_TLCL, ttype, and CClosure::upvalue.
Referenced by db_upvalueid().
LUA_API void() lua_upvaluejoin (lua_State * L, int fidx1, int n1, int fidx2, int n2)
Definition at line 1276 of file lapi.c.
References getupvalref(), and luaC_objbarrier.
Referenced by db_upvaluejoin().
LUA_API const lua_Number*() lua_version (lua_State * L)
Definition at line 137 of file lapi.c.
References G, and LUA_VERSION_NUM.
Referenced by f_luaopen(), and luaL_checkversion_().
LUA_API void() lua_xmove (lua_State * from, lua_State * to, int n)
Definition at line 112 of file lapi.c.
References api_check, api_checknelems, lua_State::ci, G, lua_lock, lua_unlock, setobj2s, CallInfo::top, and lua_State::top.
Referenced by auxresume(), db_gethook(), db_getinfo(), db_getlocal(), db_sethook(), db_setlocal(), luaB_cocreate(), and treatstackoption().
LUA_API int() lua_yieldk (lua_State * L, int nresults, int ctx, lua_CFunction k)
Definition at line 567 of file ldo.c.
References api_check, api_checknelems, CallInfo::c, CallInfo::callstatus, lua_State::ci, CIST_HOOKED, CallInfo::extra, CallInfo::func, G, isLua, lua_assert, lua_lock, lua_unlock, LUA_YIELD, luaD_throw(), luaG_runerror(), luai_userstateyield, lua_State::nny, savestack, lua_State::status, lua_State::top, and CallInfo::u.
Variable Documentation
const char lua_ident[]
Definition at line 32 of file lapi.c.