Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lundump.h File Reference
lundump.h File Reference
#include "lobject.h"
#include "lzio.h"
Macros
#define LUAC_TAIL "\x19\x93\r\n\x1a\n"
#define LUAC_HEADERSIZE (sizeof(LUA_SIGNATURE)-sizeof(char)+2+6+sizeof(LUAC_TAIL)-sizeof(char))
Functions
LUAI_FUNC Closure * luaU_undump (lua_State *L, ZIO *Z, Mbuffer *buff, const char *name)
LUAI_FUNC void luaU_header (lu_byte *h)
LUAI_FUNC int luaU_dump (lua_State *L, const Proto *f, lua_Writer w, void *data, int strip)
Macro Definition Documentation
#define LUAC_HEADERSIZE (sizeof(LUA_SIGNATURE)-sizeof(char)+2+6+sizeof(LUAC_TAIL)-sizeof(char))
Definition at line 26 of file lundump.h.
Referenced by DumpHeader(), and LoadHeader().
#define LUAC_TAIL "\x19\x93\r\n\x1a\n"
Definition at line 23 of file lundump.h.
Referenced by luaU_header().
Function Documentation
LUAI_FUNC int luaU_dump (lua_State * L, const Proto * f, lua_Writer w, void * data, int strip)
Definition at line 162 of file ldump.c.
References DumpState::data, DumpFunction(), DumpHeader(), DumpState::L, DumpState::status, DumpState::strip, and DumpState::writer.
Referenced by lua_dump().
LUAI_FUNC void luaU_header (lu_byte * h)
Definition at line 244 of file lundump.c.
References cast_byte, FORMAT, LUA_SIGNATURE, LUAC_TAIL, and VERSION.
Referenced by DumpHeader(), and LoadHeader().
LUAI_FUNC Closure* luaU_undump (lua_State * L, ZIO * Z, Mbuffer * buff, const char * name)
Definition at line 206 of file lundump.c.
References LoadState::b, incr_top, LoadState::L, Closure::l, LoadFunction(), LoadHeader(), LUA_SIGNATURE, luaF_newLclosure(), luaF_newproto(), luai_verifycode, LoadState::name, LClosure::p, setclLvalue, Proto::sizeupvalues, lua_State::top, and LoadState::Z.
Referenced by f_parser().