Kensho: <KenshoValueParameters> Protocol Reference
<KenshoValueParameters> Protocol Reference
#import <IObservable.h>
Properties
NSDictionary * parameters
NSObject * value
Additional Inherited Members
Instance Methods inherited from <IObservable>
(void) - addObserver:attribute:context:
(void) - removeObserver:attribute:context:
Detailed Description
Definition at line 23 of file IObservable.h.
Property Documentation
- (NSDictionary*) parameters read nonatomic assign
Definition at line 24 of file IObservable.h.
- (NSObject*) value read nonatomic assign
Definition at line 25 of file IObservable.h.
Referenced by lookupNewKey(), popValue(), and pushLuaValue().
The documentation for this protocol was generated from the following file:
/Users/nelliott/Documents/Projects/Kensho/ios/Kensho/Observables/IObservable.h