Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lcorolib.c File Reference
lcorolib.c File Reference
#include <stdlib.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lcorolib_c
#define LUA_LIB
Functions
static int auxresume (lua_State *L, lua_State *co, int narg)
static int luaB_coresume (lua_State *L)
static int luaB_auxwrap (lua_State *L)
static int luaB_cocreate (lua_State *L)
static int luaB_cowrap (lua_State *L)
static int luaB_yield (lua_State *L)
static int luaB_costatus (lua_State *L)
static int luaB_corunning (lua_State *L)
LUAMOD_API int luaopen_coroutine (lua_State *L)
Variables
static const luaL_Reg co_funcs []
Macro Definition Documentation
#define lcorolib_c
Definition at line 11 of file lcorolib.c.
#define LUA_LIB
Definition at line 12 of file lcorolib.c.
Function Documentation
static int auxresume (lua_State * L, lua_State * co, int narg) static
Definition at line 20 of file lcorolib.c.
References lua_checkstack(), lua_gettop(), LUA_OK, lua_pop, lua_pushliteral, lua_resume(), lua_status(), lua_xmove(), and LUA_YIELD.
Referenced by luaB_auxwrap(), and luaB_coresume().
static int luaB_auxwrap (lua_State * L) static
Definition at line 67 of file lcorolib.c.
References auxresume(), lua_concat(), lua_error(), lua_gettop(), lua_insert(), lua_isstring(), lua_tothread(), lua_upvalueindex, and luaL_where().
Referenced by luaB_cowrap().
static int luaB_cocreate (lua_State * L) static
Definition at line 82 of file lcorolib.c.
References lua_newthread(), lua_pushvalue(), LUA_TFUNCTION, lua_xmove(), and luaL_checktype().
Referenced by luaB_cowrap().
static int luaB_coresume (lua_State * L) static
Definition at line 49 of file lcorolib.c.
References auxresume(), lua_gettop(), lua_insert(), lua_pushboolean(), lua_tothread(), and luaL_argcheck.
static int luaB_corunning (lua_State * L) static
Definition at line 132 of file lcorolib.c.
References lua_pushboolean(), and lua_pushthread().
static int luaB_costatus (lua_State * L) static
Definition at line 104 of file lcorolib.c.
References lua_getstack(), lua_gettop(), LUA_OK, lua_pushliteral, lua_status(), lua_tothread(), LUA_YIELD, and luaL_argcheck.
static int luaB_cowrap (lua_State * L) static
Definition at line 92 of file lcorolib.c.
References lua_pushcclosure(), luaB_auxwrap(), and luaB_cocreate().
static int luaB_yield (lua_State * L) static
Definition at line 99 of file lcorolib.c.
References lua_gettop(), and lua_yield.
LUAMOD_API int luaopen_coroutine (lua_State * L)
Definition at line 151 of file lcorolib.c.
References luaL_newlib.
Variable Documentation
const luaL_Reg co_funcs[] static
Initial value:
= {
  {"create", luaB_cocreate},
  {"resume", luaB_coresume},
  {"running", luaB_corunning},
  {"status", luaB_costatus},
  {"wrap", luaB_cowrap},
  {"yield", luaB_yield},
  {NULL, NULL}
}
Definition at line 139 of file lcorolib.c.