Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/ldo.h File Reference
ldo.h File Reference
#include "lobject.h"
#include "lstate.h"
#include "lzio.h"
Macros
#define luaD_checkstack(L, n)
#define incr_top(L) {L->top++; luaD_checkstack(L,0);}
#define savestack(L, p) ((char *)(p) - (char *)L->stack)
#define restorestack(L, n) ((TValue *)((char *)L->stack + (n)))
Typedefs
typedef void(* Pfunc)(lua_State *L, void *ud)
Functions
LUAI_FUNC int luaD_protectedparser (lua_State *L, ZIO *z, const char *name, const char *mode)
LUAI_FUNC void luaD_hook (lua_State *L, int event, int line)
LUAI_FUNC int luaD_precall (lua_State *L, StkId func, int nresults)
LUAI_FUNC void luaD_call (lua_State *L, StkId func, int nResults, int allowyield)
LUAI_FUNC int luaD_pcall (lua_State *L, Pfunc func, void *u, ptrdiff_t oldtop, ptrdiff_t ef)
LUAI_FUNC int luaD_poscall (lua_State *L, StkId firstResult)
LUAI_FUNC void luaD_reallocstack (lua_State *L, int newsize)
LUAI_FUNC void luaD_growstack (lua_State *L, int n)
LUAI_FUNC void luaD_shrinkstack (lua_State *L)
LUAI_FUNC l_noret luaD_throw (lua_State *L, int errcode)
LUAI_FUNC int luaD_rawrunprotected (lua_State *L, Pfunc f, void *ud)
Macro Definition Documentation
#define incr_top (L) {L->top++; luaD_checkstack(L,0);}
Definition at line 20 of file ldo.h.
Referenced by luaU_undump(), luaY_parser(), open_func(), and tryfuncTM().
#define luaD_checkstack (L, n)
Value:
if (L->stack_last - L->top <= (n)) \
                    luaD_growstack(L, n); else condmovestack(L);
Definition at line 16 of file ldo.h.
Referenced by adjust_varargs(), luaD_hook(), luaD_precall(), luaO_pushvfstring(), and luaV_execute().
#define restorestack (L, n) ((TValue *)((char *)L->stack + (n)))
Definition at line 23 of file ldo.h.
Referenced by callTM(), luaD_hook(), luaD_pcall(), luaD_poscall(), luaD_precall(), luaG_errormsg(), recover(), resume(), and tryfuncTM().
#define savestack (L, p) ((char *)(p) - (char *)L->stack)
Definition at line 22 of file ldo.h.
Referenced by callTM(), GCTM(), lua_pcallk(), lua_yieldk(), luaD_hook(), luaD_poscall(), luaD_precall(), luaD_protectedparser(), and tryfuncTM().
Typedef Documentation
typedef void(* Pfunc)(lua_State *L, void *ud)
Definition at line 27 of file ldo.h.
Function Documentation
LUAI_FUNC void luaD_call (lua_State * L, StkId func, int nResults, int allowyield)
Definition at line 393 of file ldo.c.
References LUA_ERRERR, luaD_precall(), luaD_throw(), luaG_runerror(), LUAI_MAXCCALLS, luaV_execute(), lua_State::nCcalls, and lua_State::nny.
Referenced by callTM(), dothecall(), f_call(), lua_callk(), lua_pcallk(), luaG_errormsg(), and luaV_execute().
LUAI_FUNC void luaD_growstack (lua_State * L, int n)
Definition at line 175 of file ldo.c.
References cast_int, ERRORSTACKSIZE, EXTRA_STACK, LUA_ERRERR, luaD_reallocstack(), luaD_throw(), luaG_runerror(), LUAI_MAXSTACK, lua_State::stack, lua_State::stacksize, and lua_State::top.
Referenced by growstack().
LUAI_FUNC void luaD_hook (lua_State * L, int event, int line)
Definition at line 217 of file ldo.c.
References lua_State::allowhook, CallInfo::callstatus, lua_State::ci, CIST_HOOKED, lua_Debug::currentline, lua_Debug::event, lua_State::hook, lua_Debug::i_ci, lua_assert, lua_lock, LUA_MINSTACK, lua_unlock, luaD_checkstack, restorestack, savestack, lua_State::stack_last, CallInfo::top, and lua_State::top.
Referenced by callhook(), luaD_poscall(), luaD_precall(), and traceexec().
LUAI_FUNC int luaD_pcall (lua_State * L, Pfunc func, void * u, ptrdiff_t oldtop, ptrdiff_t ef)
Definition at line 595 of file ldo.c.
References lua_State::allowhook, lua_State::ci, lua_State::errfunc, LUA_OK, luaD_rawrunprotected(), luaD_shrinkstack(), luaF_close(), lua_State::nny, restorestack, seterrorobj(), and lua_longjmp::status.
Referenced by GCTM(), lua_pcallk(), and luaD_protectedparser().
LUAI_FUNC int luaD_poscall (lua_State * L, StkId firstResult)
Definition at line 362 of file ldo.c.
References lua_State::ci, CallInfo::func, lua_State::hookmask, CallInfo::l, LUA_HOOKRET, LUA_MASKLINE, LUA_MASKRET, LUA_MULTRET, luaD_hook(), CallInfo::nresults, lua_State::oldpc, CallInfo::previous, restorestack, savestack, setnilvalue, setobjs2s, lua_State::top, and CallInfo::u.
Referenced by finishCcall(), luaD_precall(), luaV_execute(), and resume().
LUAI_FUNC int luaD_precall (lua_State * L, StkId func, int nresults)
Definition at line 296 of file ldo.c.
References adjust_varargs(), api_checknelems, callhook(), CallInfo::callstatus, cast_int, CIST_LUA, clCvalue, clLvalue, Proto::code, CallInfo::func, fvalue, lua_State::hookmask, Proto::is_vararg, CallInfo::l, lua_assert, LUA_HOOKCALL, lua_lock, LUA_MASKCALL, LUA_MINSTACK, LUA_TCCL, LUA_TLCF, LUA_TLCL, lua_unlock, luaC_checkGC, luaD_checkstack, luaD_hook(), luaD_poscall(), luaD_precall(), Proto::maxstacksize, next_ci, CallInfo::nresults, Proto::numparams, restorestack, savestack, setnilvalue, lua_State::stack_last, CallInfo::top, lua_State::top, tryfuncTM(), ttype, and CallInfo::u.
Referenced by luaD_call(), luaD_precall(), luaV_execute(), and resume().
LUAI_FUNC int luaD_protectedparser (lua_State * L, ZIO * z, const char * name, const char * mode)
Definition at line 662 of file ldo.c.
References Dyndata::actvar, Labellist::arr, Dyndata::arr, SParser::buff, SParser::dyd, lua_State::errfunc, f_parser(), Dyndata::gt, Dyndata::label, luaD_pcall(), luaM_freearray, luaZ_freebuffer, luaZ_initbuffer, SParser::mode, SParser::name, lua_State::nny, savestack, Labellist::size, Dyndata::size, lua_State::top, and SParser::z.
Referenced by lua_load().
LUAI_FUNC int luaD_rawrunprotected (lua_State * L, Pfunc f, void * ud)
Definition at line 125 of file ldo.c.
References lua_State::errorJmp, LUA_OK, LUAI_TRY, lua_State::nCcalls, lua_longjmp::previous, and lua_longjmp::status.
Referenced by lua_checkstack(), lua_newstate(), lua_resume(), and luaD_pcall().
LUAI_FUNC void luaD_reallocstack (lua_State * L, int newsize)
Definition at line 161 of file ldo.c.
References correctstack(), ERRORSTACKSIZE, EXTRA_STACK, lua_assert, LUAI_MAXSTACK, luaM_reallocvector, setnilvalue, lua_State::stack, lua_State::stack_last, and lua_State::stacksize.
Referenced by luaD_growstack(), and luaD_shrinkstack().
LUAI_FUNC void luaD_shrinkstack (lua_State * L)
Definition at line 205 of file ldo.c.
References condmovestack, EXTRA_STACK, luaD_reallocstack(), LUAI_MAXSTACK, stackinuse(), and lua_State::stacksize.
Referenced by luaD_pcall(), recover(), and sweepthread().
LUAI_FUNC l_noret luaD_throw (lua_State * L, int errcode)
Definition at line 103 of file ldo.c.
References cast_byte, lua_State::errorJmp, G, lua_unlock, luaD_throw(), LUAI_THROW, panic(), setobjs2s, lua_longjmp::status, lua_State::status, and lua_State::top.
Referenced by checkmode(), error(), GCTM(), lexerror(), lua_yieldk(), luaD_call(), luaD_growstack(), luaD_throw(), luaG_errormsg(), luaM_realloc_(), resume_error(), and traceexec().