Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/linit.c File Reference
linit.c File Reference
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
Macros
#define linit_c
#define LUA_LIB
Functions
LUALIB_API void luaL_openlibs (lua_State *L)
Variables
static const luaL_Reg loadedlibs []
static const luaL_Reg preloadedlibs []
Macro Definition Documentation
#define linit_c
Definition at line 16 of file linit.c.
#define LUA_LIB
Definition at line 17 of file linit.c.
Function Documentation
LUALIB_API void luaL_openlibs (lua_State * L)
Definition at line 52 of file linit.c.
References luaL_Reg::func, lua_pop, lua_pushcfunction, LUA_REGISTRYINDEX, lua_setfield(), luaL_getsubtable(), luaL_requiref(), and luaL_Reg::name.
Referenced by KenshoLuaWrapper::evaluate.
Variable Documentation
const luaL_Reg loadedlibs[] static
Initial value:
= {
  {"_G", luaopen_base},
  {LUA_LOADLIBNAME, luaopen_package},
  {LUA_COLIBNAME, luaopen_coroutine},
  {LUA_TABLIBNAME, luaopen_table},
  {LUA_IOLIBNAME, luaopen_io},
  {LUA_OSLIBNAME, luaopen_os},
  {LUA_STRLIBNAME, luaopen_string},
  {LUA_BITLIBNAME, luaopen_bit32},
  {LUA_MATHLIBNAME, luaopen_math},
  {LUA_DBLIBNAME, luaopen_debug},
  {NULL, NULL}
}
Definition at line 29 of file linit.c.
const luaL_Reg preloadedlibs[] static
Initial value:
= {
  {NULL, NULL}
}
Definition at line 47 of file linit.c.