Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lmathlib.c File Reference
lmathlib.c File Reference
#include <stdlib.h>
#include <math.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lmathlib_c
#define LUA_LIB
#define PI ((lua_Number)(3.1415926535897932384626433832795))
#define RADIANS_PER_DEGREE ((lua_Number)(PI/180.0))
Functions
static int math_abs (lua_State *L)
static int math_sin (lua_State *L)
static int math_sinh (lua_State *L)
static int math_cos (lua_State *L)
static int math_cosh (lua_State *L)
static int math_tan (lua_State *L)
static int math_tanh (lua_State *L)
static int math_asin (lua_State *L)
static int math_acos (lua_State *L)
static int math_atan (lua_State *L)
static int math_atan2 (lua_State *L)
static int math_ceil (lua_State *L)
static int math_floor (lua_State *L)
static int math_fmod (lua_State *L)
static int math_modf (lua_State *L)
static int math_sqrt (lua_State *L)
static int math_pow (lua_State *L)
static int math_log (lua_State *L)
static int math_exp (lua_State *L)
static int math_deg (lua_State *L)
static int math_rad (lua_State *L)
static int math_frexp (lua_State *L)
static int math_ldexp (lua_State *L)
static int math_min (lua_State *L)
static int math_max (lua_State *L)
static int math_random (lua_State *L)
static int math_randomseed (lua_State *L)
LUAMOD_API int luaopen_math (lua_State *L)
Variables
static const luaL_Reg mathlib []
Macro Definition Documentation
#define lmathlib_c
Definition at line 11 of file lmathlib.c.
#define LUA_LIB
Definition at line 12 of file lmathlib.c.
#define PI ((lua_Number)(3.1415926535897932384626433832795))
Definition at line 21 of file lmathlib.c.
Referenced by luaopen_math().
#define RADIANS_PER_DEGREE ((lua_Number)(PI/180.0))
Definition at line 22 of file lmathlib.c.
Referenced by math_deg(), and math_rad().
Function Documentation
LUAMOD_API int luaopen_math (lua_State * L)
Definition at line 271 of file lmathlib.c.
References lua_pushnumber(), lua_setfield(), luaL_newlib, and PI.
static int math_abs (lua_State * L) static
Definition at line 26 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_acos (lua_State * L) static
Definition at line 66 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_asin (lua_State * L) static
Definition at line 61 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_atan (lua_State * L) static
Definition at line 71 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_atan2 (lua_State * L) static
Definition at line 76 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_ceil (lua_State * L) static
Definition at line 82 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_cos (lua_State * L) static
Definition at line 41 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_cosh (lua_State * L) static
Definition at line 46 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_deg (lua_State * L) static
Definition at line 144 of file lmathlib.c.
References lua_pushnumber(), luaL_checknumber(), and RADIANS_PER_DEGREE.
static int math_exp (lua_State * L) static
Definition at line 139 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_floor (lua_State * L) static
Definition at line 87 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_fmod (lua_State * L) static
Definition at line 92 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_frexp (lua_State * L) static
Definition at line 154 of file lmathlib.c.
References l_mathop, lua_pushinteger(), lua_pushnumber(), and luaL_checknumber().
static int math_ldexp (lua_State * L) static
Definition at line 161 of file lmathlib.c.
References l_mathop, lua_pushnumber(), luaL_checkint, and luaL_checknumber().
static int math_log (lua_State * L) static
Definition at line 118 of file lmathlib.c.
References l_mathop, lua_isnoneornil, lua_pushnumber(), and luaL_checknumber().
static int math_max (lua_State * L) static
Definition at line 184 of file lmathlib.c.
References lua_gettop(), lua_pushnumber(), and luaL_checknumber().
static int math_min (lua_State * L) static
Definition at line 170 of file lmathlib.c.
References lua_gettop(), lua_pushnumber(), and luaL_checknumber().
static int math_modf (lua_State * L) static
Definition at line 98 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_pow (lua_State * L) static
Definition at line 111 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_rad (lua_State * L) static
Definition at line 149 of file lmathlib.c.
References lua_pushnumber(), luaL_checknumber(), and RADIANS_PER_DEGREE.
static int math_random (lua_State * L) static
Definition at line 198 of file lmathlib.c.
References l_mathop, lua_gettop(), lua_pushnumber(), luaL_argcheck, luaL_checknumber(), and luaL_error().
static int math_randomseed (lua_State * L) static
Definition at line 226 of file lmathlib.c.
References luaL_checkunsigned().
static int math_sin (lua_State * L) static
Definition at line 31 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_sinh (lua_State * L) static
Definition at line 36 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_sqrt (lua_State * L) static
Definition at line 106 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_tan (lua_State * L) static
Definition at line 51 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
static int math_tanh (lua_State * L) static
Definition at line 56 of file lmathlib.c.
References l_mathop, lua_pushnumber(), and luaL_checknumber().
Variable Documentation
const luaL_Reg mathlib[] static
Definition at line 233 of file lmathlib.c.