Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/ldebug.c File Reference
ldebug.c File Reference
#include <stdarg.h>
#include <stddef.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "lcode.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lvm.h"
Macros
#define ldebug_c
#define LUA_CORE
#define noLuaClosure(f) ((f) == NULL || (f)->c.tt == LUA_TCCL)
Functions
static const char * getfuncname (lua_State *L, CallInfo *ci, const char **name)
static int currentpc (CallInfo *ci)
static int currentline (CallInfo *ci)
LUA_API int lua_sethook (lua_State *L, lua_Hook func, int mask, int count)
LUA_API lua_Hook lua_gethook (lua_State *L)
LUA_API int lua_gethookmask (lua_State *L)
LUA_API int lua_gethookcount (lua_State *L)
LUA_API int lua_getstack (lua_State *L, int level, lua_Debug *ar)
static const char * upvalname (Proto *p, int uv)
static const char * findvararg (CallInfo *ci, int n, StkId *pos)
static const char * findlocal (lua_State *L, CallInfo *ci, int n, StkId *pos)
LUA_API const char * lua_getlocal (lua_State *L, const lua_Debug *ar, int n)
LUA_API const char * lua_setlocal (lua_State *L, const lua_Debug *ar, int n)
static void funcinfo (lua_Debug *ar, Closure *cl)
static void collectvalidlines (lua_State *L, Closure *f)
static int auxgetinfo (lua_State *L, const char *what, lua_Debug *ar, Closure *f, CallInfo *ci)
LUA_API int lua_getinfo (lua_State *L, const char *what, lua_Debug *ar)
static const char * getobjname (Proto *p, int lastpc, int reg, const char **name)
static void kname (Proto *p, int pc, int c, const char **name)
static int filterpc (int pc, int jmptarget)
static int findsetreg (Proto *p, int lastpc, int reg)
static int isinstack (CallInfo *ci, const TValue *o)
static const char * getupvalname (CallInfo *ci, const TValue *o, const char **name)
l_noret luaG_typeerror (lua_State *L, const TValue *o, const char *op)
l_noret luaG_concaterror (lua_State *L, StkId p1, StkId p2)
l_noret luaG_aritherror (lua_State *L, const TValue *p1, const TValue *p2)
l_noret luaG_ordererror (lua_State *L, const TValue *p1, const TValue *p2)
static void addinfo (lua_State *L, const char *msg)
l_noret luaG_errormsg (lua_State *L)
l_noret luaG_runerror (lua_State *L, const char *fmt,...)
Macro Definition Documentation
#define ldebug_c
Definition at line 13 of file ldebug.c.
#define LUA_CORE
Definition at line 14 of file ldebug.c.
#define noLuaClosure (f) ((f) == NULL || (f)->c.tt == LUA_TCCL)
Definition at line 33 of file ldebug.c.
Referenced by auxgetinfo(), collectvalidlines(), and funcinfo().
Function Documentation
static void addinfo (lua_State * L, const char * msg) static
Definition at line 557 of file ldebug.c.
References lua_State::ci, ci_func, currentline(), getstr, isLua, LUA_IDSIZE, luaO_chunkid(), and luaO_pushfstring().
Referenced by luaG_runerror().
static int auxgetinfo (lua_State * L, const char * what, lua_Debug * ar, Closure * f, CallInfo * ci) static
Definition at line 215 of file ldebug.c.
References Closure::c, CallInfo::callstatus, CIST_TAIL, currentline(), lua_Debug::currentline, funcinfo(), getfuncname(), Proto::is_vararg, isLua, lua_Debug::istailcall, lua_Debug::isvararg, Closure::l, lua_Debug::name, lua_Debug::namewhat, noLuaClosure, lua_Debug::nparams, Proto::numparams, lua_Debug::nups, LClosure::p, and CallInfo::previous.
Referenced by lua_getinfo().
static void collectvalidlines (lua_State * L, Closure * f) static
Definition at line 196 of file ldebug.c.
References api_incr_top, Closure::l, Proto::lineinfo, luaH_new(), luaH_setint(), noLuaClosure, LClosure::p, setbvalue, sethvalue, setnilvalue, Proto::sizelineinfo, and lua_State::top.
Referenced by lua_getinfo().
static int currentline (CallInfo * ci) static
Definition at line 45 of file ldebug.c.
References ci_func, currentpc(), and getfuncline.
Referenced by addinfo(), and auxgetinfo().
static int currentpc (CallInfo * ci) static
Definition at line 39 of file ldebug.c.
References ci_func, isLua, CallInfo::l, lua_assert, pcRel, and CallInfo::u.
Referenced by currentline(), findlocal(), getfuncname(), and luaG_typeerror().
static int filterpc (int pc, int jmptarget) static
Definition at line 330 of file ldebug.c.
Referenced by findsetreg().
static const char* findlocal (lua_State * L, CallInfo * ci, int n, StkId * pos) static
Definition at line 118 of file ldebug.c.
References lua_State::ci, ci_func, currentpc(), findvararg(), CallInfo::func, isLua, CallInfo::l, luaF_getlocalname(), CallInfo::next, lua_State::top, and CallInfo::u.
Referenced by lua_getlocal(), and lua_setlocal().
static int findsetreg (Proto * p, int lastpc, int reg) static
Definition at line 340 of file ldebug.c.
References Proto::code, filterpc(), GET_OPCODE, GETARG_A, GETARG_B, GETARG_sBx, OP_CALL, OP_JMP, OP_LOADNIL, OP_TAILCALL, OP_TEST, OP_TFORCALL, and testAMode.
Referenced by getobjname().
static const char* findvararg (CallInfo * ci, int n, StkId * pos) static
Definition at line 107 of file ldebug.c.
References clLvalue, CallInfo::func, CallInfo::l, and CallInfo::u.
Referenced by findlocal().
static void funcinfo (lua_Debug * ar, Closure * cl) static
Definition at line 178 of file ldebug.c.
References getstr, Closure::l, lua_Debug::lastlinedefined, Proto::lastlinedefined, lua_Debug::linedefined, Proto::linedefined, LUA_IDSIZE, luaO_chunkid(), noLuaClosure, LClosure::p, lua_Debug::short_src, lua_Debug::source, Proto::source, and lua_Debug::what.
Referenced by auxgetinfo().
static const char * getfuncname (lua_State * L, CallInfo * ci, const char ** name) static
Definition at line 445 of file ldebug.c.
References ci_func, Proto::code, currentpc(), G, GET_OPCODE, GETARG_A, getobjname(), getstr, OP_ADD, OP_CALL, OP_CONCAT, OP_DIV, OP_EQ, OP_GETTABLE, OP_GETTABUP, OP_LE, OP_LEN, OP_LT, OP_MOD, OP_MUL, OP_POW, OP_SELF, OP_SETTABLE, OP_SETTABUP, OP_SUB, OP_TAILCALL, OP_TFORCALL, OP_UNM, TM_ADD, TM_CONCAT, TM_DIV, TM_EQ, TM_INDEX, TM_LE, TM_LEN, TM_LT, TM_MOD, TM_MUL, TM_NEWINDEX, TM_POW, TM_SUB, and TM_UNM.
Referenced by auxgetinfo().
static const char * getobjname (Proto * p, int lastpc, int reg, const char ** name) static
Definition at line 391 of file ldebug.c.
References Proto::code, findsetreg(), GET_OPCODE, GETARG_A, GETARG_Ax, GETARG_B, GETARG_Bx, GETARG_C, Proto::k, kname(), LUA_ENV, luaF_getlocalname(), OP_GETTABLE, OP_GETTABUP, OP_GETUPVAL, OP_LOADK, OP_LOADKX, OP_MOVE, OP_SELF, svalue, ttisstring, and upvalname().
Referenced by getfuncname(), kname(), and luaG_typeerror().
static const char* getupvalname (CallInfo * ci, const TValue * o, const char ** name) static
Definition at line 499 of file ldebug.c.
References ci_func, LClosure::p, upvalname(), LClosure::upvals, and UpVal::v.
Referenced by luaG_typeerror().
static int isinstack (CallInfo * ci, const TValue * o) static
Definition at line 491 of file ldebug.c.
References CallInfo::l, and CallInfo::u.
Referenced by luaG_typeerror().
static void kname (Proto * p, int pc, int c, const char ** name) static
Definition at line 310 of file ldebug.c.
References getobjname(), INDEXK, ISK, Proto::k, svalue, and ttisstring.
Referenced by getobjname().
LUA_API lua_Hook lua_gethook (lua_State * L)
Definition at line 68 of file ldebug.c.
References lua_State::hook.
Referenced by db_gethook().
LUA_API int lua_gethookcount (lua_State * L)
Definition at line 78 of file ldebug.c.
References lua_State::basehookcount.
Referenced by db_gethook().
LUA_API int lua_gethookmask (lua_State * L)
Definition at line 73 of file ldebug.c.
References lua_State::hookmask.
Referenced by db_gethook().
LUA_API int lua_getinfo (lua_State * L, const char * what, lua_Debug * ar)
Definition at line 266 of file ldebug.c.
References api_check, api_incr_top, auxgetinfo(), clvalue, collectvalidlines(), CallInfo::func, lua_Debug::i_ci, lua_assert, lua_lock, lua_unlock, setobjs2s, lua_State::top, ttisclosure, and ttisfunction.
Referenced by checkupval(), db_getinfo(), hookf(), luaL_argerror(), luaL_traceback(), luaL_where(), and pushglobalfuncname().
LUA_API const char* lua_getlocal (lua_State * L, const lua_Debug * ar, int n)
Definition at line 144 of file ldebug.c.
References api_incr_top, clLvalue, findlocal(), lua_Debug::i_ci, isLfunction, lua_lock, lua_unlock, luaF_getlocalname(), setobj2s, and lua_State::top.
Referenced by db_getlocal().
LUA_API int lua_getstack (lua_State * L, int level, lua_Debug * ar)
Definition at line 83 of file ldebug.c.
References lua_State::base_ci, lua_State::ci, lua_Debug::i_ci, lua_lock, lua_unlock, and CallInfo::previous.
Referenced by countlevels(), db_getinfo(), db_getlocal(), db_setlocal(), luaB_costatus(), luaL_argerror(), luaL_traceback(), and luaL_where().
LUA_API int lua_sethook (lua_State * L, lua_Hook func, int mask, int count)
Definition at line 53 of file ldebug.c.
References lua_State::basehookcount, cast_byte, lua_State::ci, lua_State::hook, lua_State::hookmask, isLua, CallInfo::l, lua_State::oldpc, resethookcount, and CallInfo::u.
Referenced by db_sethook().
LUA_API const char* lua_setlocal (lua_State * L, const lua_Debug * ar, int n)
Definition at line 166 of file ldebug.c.
References findlocal(), lua_Debug::i_ci, lua_lock, lua_unlock, setobjs2s, and lua_State::top.
Referenced by db_setlocal().
l_noret luaG_aritherror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 539 of file ldebug.c.
References luaG_typeerror(), and luaV_tonumber().
Referenced by luaV_arith().
l_noret luaG_concaterror (lua_State * L, StkId p1, StkId p2)
Definition at line 532 of file ldebug.c.
References lua_assert, luaG_typeerror(), ttisnumber, and ttisstring.
Referenced by luaV_concat().
l_noret luaG_errormsg (lua_State * L)
Definition at line 573 of file ldebug.c.
References lua_State::errfunc, LUA_ERRERR, LUA_ERRRUN, luaD_call(), luaD_throw(), restorestack, setobjs2s, lua_State::top, and ttisfunction.
Referenced by lua_error(), and luaG_runerror().
l_noret luaG_ordererror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 547 of file ldebug.c.
References luaG_runerror(), and objtypename.
Referenced by luaV_lessequal(), and luaV_lessthan().
l_noret luaG_runerror (lua_State * L, const char * fmt, ...)
Definition at line 586 of file ldebug.c.
References addinfo(), luaG_errormsg(), and luaO_pushvfstring().
Referenced by findindex(), lua_pushnumber(), lua_yieldk(), luaD_call(), luaD_growstack(), luaG_ordererror(), luaG_typeerror(), luaH_newkey(), luaM_growaux_(), luaM_toobig(), luaO_pushvfstring(), luaV_concat(), luaV_execute(), luaV_gettable(), luaV_settable(), and setnodevector().
l_noret luaG_typeerror (lua_State * L, const TValue * o, const char * op)
Definition at line 513 of file ldebug.c.
References cast_int, lua_State::ci, ci_func, currentpc(), getobjname(), getupvalname(), isinstack(), isLua, CallInfo::l, LUA_QS, luaG_runerror(), objtypename, and CallInfo::u.
Referenced by luaG_aritherror(), luaG_concaterror(), luaV_gettable(), luaV_objlen(), luaV_settable(), and tryfuncTM().
static const char* upvalname (Proto * p, int uv) static
Definition at line 100 of file ldebug.c.
References check_exp, getstr, Upvaldesc::name, and Proto::upvalues.
Referenced by getobjname(), and getupvalname().