Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lstrlib.c File Reference
lstrlib.c File Reference
#include <ctype.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Classes
struct MatchState
Macros
#define lstrlib_c
#define LUA_LIB
#define LUA_MAXCAPTURES 32
#define uchar(c) ((unsigned char)(c))
#define MAXSIZE ((~(size_t)0) >> 1)
#define CAP_UNFINISHED (-1)
#define CAP_POSITION (-2)
#define MAXCCALLS 200
#define L_ESC '%'
#define SPECIALS "^$*+?.([%-"
#define LUA_INTFRMLEN "l"
#define LUA_INTFRM_T long
#define LUA_FLTFRMLEN ""
#define LUA_FLTFRM_T double
#define MAX_ITEM 512
#define FLAGS "-+ #0"
#define MAX_FORMAT (sizeof(FLAGS) + sizeof(LUA_INTFRMLEN) + 10)
Typedefs
typedef struct MatchState MatchState
Functions
static int str_len (lua_State *L)
static size_t posrelat (ptrdiff_t pos, size_t len)
static int str_sub (lua_State *L)
static int str_reverse (lua_State *L)
static int str_lower (lua_State *L)
static int str_upper (lua_State *L)
static int str_rep (lua_State *L)
static int str_byte (lua_State *L)
static int str_char (lua_State *L)
static int writer (lua_State *L, const void *b, size_t size, void *B)
static int str_dump (lua_State *L)
static const char * match (MatchState *ms, const char *s, const char *p)
static int check_capture (MatchState *ms, int l)
static int capture_to_close (MatchState *ms)
static const char * classend (MatchState *ms, const char *p)
static int match_class (int c, int cl)
static int matchbracketclass (int c, const char *p, const char *ec)
static int singlematch (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * matchbalance (MatchState *ms, const char *s, const char *p)
static const char * max_expand (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * min_expand (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * start_capture (MatchState *ms, const char *s, const char *p, int what)
static const char * end_capture (MatchState *ms, const char *s, const char *p)
static const char * match_capture (MatchState *ms, const char *s, int l)
static const char * lmemfind (const char *s1, size_t l1, const char *s2, size_t l2)
static void push_onecapture (MatchState *ms, int i, const char *s, const char *e)
static int push_captures (MatchState *ms, const char *s, const char *e)
static int nospecials (const char *p, size_t l)
static int str_find_aux (lua_State *L, int find)
static int str_find (lua_State *L)
static int str_match (lua_State *L)
static int gmatch_aux (lua_State *L)
static int gmatch (lua_State *L)
static void add_s (MatchState *ms, luaL_Buffer *b, const char *s, const char *e)
static void add_value (MatchState *ms, luaL_Buffer *b, const char *s, const char *e, int tr)
static int str_gsub (lua_State *L)
static void addquoted (lua_State *L, luaL_Buffer *b, int arg)
static const char * scanformat (lua_State *L, const char *strfrmt, char *form)
static void addlenmod (char *form, const char *lenmod)
static int str_format (lua_State *L)
static void createmetatable (lua_State *L)
LUAMOD_API int luaopen_string (lua_State *L)
Variables
static const luaL_Reg strlib []
Macro Definition Documentation
#define CAP_POSITION (-2)
Definition at line 195 of file lstrlib.c.
Referenced by match(), and push_onecapture().
#define CAP_UNFINISHED (-1)
Definition at line 194 of file lstrlib.c.
Referenced by capture_to_close(), check_capture(), end_capture(), match(), and push_onecapture().
#define FLAGS "-+ #0"
Definition at line 825 of file lstrlib.c.
Referenced by scanformat().
#define L_ESC '%'
Definition at line 222 of file lstrlib.c.
Referenced by add_s(), classend(), match(), matchbracketclass(), singlematch(), and str_format().
#define lstrlib_c
Definition at line 14 of file lstrlib.c.
#define LUA_FLTFRM_T double
Definition at line 817 of file lstrlib.c.
Referenced by str_format().
#define LUA_FLTFRMLEN ""
Definition at line 816 of file lstrlib.c.
Referenced by str_format().
#define LUA_INTFRM_T long
Definition at line 803 of file lstrlib.c.
Referenced by str_format().
#define LUA_INTFRMLEN "l"
Definition at line 802 of file lstrlib.c.
Referenced by str_format().
#define LUA_LIB
Definition at line 15 of file lstrlib.c.
#define LUA_MAXCAPTURES 32
Definition at line 28 of file lstrlib.c.
Referenced by start_capture().
#define MAX_FORMAT (sizeof(FLAGS) + sizeof(LUA_INTFRMLEN) + 10)
Definition at line 830 of file lstrlib.c.
Referenced by str_format().
#define MAX_ITEM 512
Definition at line 823 of file lstrlib.c.
Referenced by str_format().
#define MAXCCALLS 200
Definition at line 218 of file lstrlib.c.
Referenced by gmatch_aux(), str_find_aux(), and str_gsub().
#define MAXSIZE ((~(size_t)0) >> 1)
Definition at line 106 of file lstrlib.c.
Referenced by str_rep().
#define SPECIALS "^$*+?.([%-"
Definition at line 223 of file lstrlib.c.
Referenced by nospecials().
#define uchar (c) ((unsigned char)(c))
Definition at line 33 of file lstrlib.c.
Referenced by add_s(), addquoted(), match(), matchbracketclass(), scanformat(), singlematch(), str_byte(), str_char(), str_lower(), and str_upper().
Typedef Documentation
typedef struct MatchState MatchState
Function Documentation
static void add_s (MatchState * ms, luaL_Buffer * b, const char * s, const char * e) static
Definition at line 678 of file lstrlib.c.
References MatchState::L, L_ESC, LUA_QL, lua_tolstring(), luaL_addchar, luaL_addlstring(), luaL_addvalue(), luaL_error(), push_onecapture(), and uchar.
Referenced by add_value().
static void add_value (MatchState * ms, luaL_Buffer * b, const char * s, const char * e, int tr) static
Definition at line 704 of file lstrlib.c.
References add_s(), MatchState::L, lua_call, lua_gettable(), lua_isstring(), lua_pop, lua_pushlstring(), lua_pushvalue(), LUA_TFUNCTION, lua_toboolean(), LUA_TTABLE, luaL_addvalue(), luaL_error(), luaL_typename, push_captures(), and push_onecapture().
Referenced by str_gsub().
static void addlenmod (char * form, const char * lenmod) static
Definition at line 882 of file lstrlib.c.
Referenced by str_format().
static void addquoted (lua_State * L, luaL_Buffer * b, int arg) static
Definition at line 833 of file lstrlib.c.
References luaL_addchar, luaL_addstring(), luaL_checklstring(), and uchar.
Referenced by str_format().
static int capture_to_close (MatchState * ms) static
Definition at line 234 of file lstrlib.c.
References CAP_UNFINISHED, MatchState::capture, MatchState::L, MatchState::len, MatchState::level, and luaL_error().
Referenced by end_capture().
static int check_capture (MatchState * ms, int l) static
Definition at line 226 of file lstrlib.c.
References CAP_UNFINISHED, MatchState::capture, MatchState::L, MatchState::len, MatchState::level, and luaL_error().
Referenced by match_capture().
static const char* classend (MatchState * ms, const char * p) static
Definition at line 242 of file lstrlib.c.
References MatchState::L, L_ESC, LUA_QL, luaL_error(), and MatchState::p_end.
Referenced by match().
static void createmetatable (lua_State * L) static
Definition at line 999 of file lstrlib.c.
References lua_createtable(), lua_pop, lua_pushliteral, lua_pushvalue(), lua_setfield(), and lua_setmetatable().
Referenced by luaopen_string().
static const char* end_capture (MatchState * ms, const char * s, const char * p) static
Definition at line 388 of file lstrlib.c.
References CAP_UNFINISHED, MatchState::capture, capture_to_close(), MatchState::init, MatchState::len, and match().
Referenced by match().
static int gmatch (lua_State * L) static
Definition at line 668 of file lstrlib.c.
References gmatch_aux(), lua_pushcclosure(), lua_pushinteger(), lua_settop(), and luaL_checkstring.
static int gmatch_aux (lua_State * L) static
Definition at line 639 of file lstrlib.c.
References MatchState::L, MatchState::level, lua_assert, lua_pushinteger(), lua_replace(), lua_tointeger, lua_tolstring(), lua_upvalueindex, match(), MatchState::matchdepth, MAXCCALLS, MatchState::p_end, push_captures(), MatchState::src_end, and MatchState::src_init.
Referenced by gmatch().
static const char* lmemfind (const char * s1, size_t l1, const char * s2, size_t l2) static
Definition at line 514 of file lstrlib.c.
Referenced by str_find_aux().
LUAMOD_API int luaopen_string (lua_State * L)
Definition at line 1014 of file lstrlib.c.
References createmetatable(), and luaL_newlib.
static const char * match (MatchState * ms, const char * s, const char * p) static
Definition at line 410 of file lstrlib.c.
References CAP_POSITION, CAP_UNFINISHED, classend(), end_capture(), MatchState::L, L_ESC, LUA_QL, luaL_error(), match_capture(), matchbalance(), matchbracketclass(), MatchState::matchdepth, max_expand(), min_expand(), MatchState::p_end, singlematch(), MatchState::src_end, MatchState::src_init, start_capture(), and uchar.
Referenced by end_capture(), gmatch_aux(), max_expand(), min_expand(), start_capture(), str_find_aux(), and str_gsub().
static const char* match_capture (MatchState * ms, const char * s, int l) static
Definition at line 399 of file lstrlib.c.
References MatchState::capture, check_capture(), MatchState::init, MatchState::len, and MatchState::src_end.
Referenced by match().
static int match_class (int c, int cl) static
Definition at line 266 of file lstrlib.c.
Referenced by matchbracketclass(), and singlematch().
static const char* matchbalance (MatchState * ms, const char * s, const char * p) static
Definition at line 325 of file lstrlib.c.
References MatchState::L, LUA_QL, luaL_error(), and MatchState::p_end.
Referenced by match().
static int matchbracketclass (int c, const char * p, const char * ec) static
Definition at line 286 of file lstrlib.c.
References L_ESC, match_class(), and uchar.
Referenced by match(), and singlematch().
static const char* max_expand (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 346 of file lstrlib.c.
References match(), and singlematch().
Referenced by match().
static const char* min_expand (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 361 of file lstrlib.c.
References match(), and singlematch().
Referenced by match().
static int nospecials (const char * p, size_t l) static
Definition at line 566 of file lstrlib.c.
References SPECIALS.
Referenced by str_find_aux().
static size_t posrelat (ptrdiff_t pos, size_t len) static
Definition at line 46 of file lstrlib.c.
Referenced by str_byte(), str_find_aux(), and str_sub().
static int push_captures (MatchState * ms, const char * s, const char * e) static
Definition at line 555 of file lstrlib.c.
References MatchState::L, MatchState::level, luaL_checkstack(), and push_onecapture().
Referenced by add_value(), gmatch_aux(), and str_find_aux().
static void push_onecapture (MatchState * ms, int i, const char * s, const char * e) static
Definition at line 536 of file lstrlib.c.
References CAP_POSITION, CAP_UNFINISHED, MatchState::capture, MatchState::init, MatchState::L, MatchState::len, MatchState::level, lua_pushinteger(), lua_pushlstring(), luaL_error(), and MatchState::src_init.
Referenced by add_s(), add_value(), and push_captures().
static const char* scanformat (lua_State * L, const char * strfrmt, char * form) static
Definition at line 857 of file lstrlib.c.
References FLAGS, luaL_error(), and uchar.
Referenced by str_format().
static int singlematch (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 309 of file lstrlib.c.
References L_ESC, match_class(), matchbracketclass(), MatchState::src_end, and uchar.
Referenced by match(), max_expand(), and min_expand().
static const char* start_capture (MatchState * ms, const char * s, const char * p, int what) static
Definition at line 374 of file lstrlib.c.
References MatchState::capture, MatchState::init, MatchState::L, MatchState::len, MatchState::level, LUA_MAXCAPTURES, luaL_error(), and match().
Referenced by match().
static int str_byte (lua_State * L) static
Definition at line 133 of file lstrlib.c.
References lua_pushinteger(), luaL_checklstring(), luaL_checkstack(), luaL_error(), luaL_optinteger(), posrelat(), and uchar.
static int str_char (lua_State * L) static
Definition at line 152 of file lstrlib.c.
References lua_gettop(), luaL_argcheck, luaL_buffinitsize(), luaL_checkint, luaL_pushresultsize(), and uchar.
static int str_dump (lua_State * L) static
Definition at line 174 of file lstrlib.c.
References lua_dump(), lua_settop(), LUA_TFUNCTION, luaL_buffinit(), luaL_checktype(), luaL_error(), luaL_pushresult(), and writer().
static int str_find (lua_State * L) static
Definition at line 629 of file lstrlib.c.
References str_find_aux().
static int str_find_aux (lua_State * L, int find) static
Definition at line 577 of file lstrlib.c.
References MatchState::L, MatchState::level, lmemfind(), lua_assert, lua_pushinteger(), lua_pushnil(), lua_toboolean(), luaL_checklstring(), luaL_optinteger(), match(), MatchState::matchdepth, MAXCCALLS, nospecials(), MatchState::p_end, posrelat(), push_captures(), MatchState::src_end, and MatchState::src_init.
Referenced by str_find(), and str_match().
static int str_format (lua_State * L) static
Definition at line 892 of file lstrlib.c.
References addlenmod(), addquoted(), L_ESC, LUA_FLTFRM_T, LUA_FLTFRMLEN, lua_gettop(), LUA_INTFRM_T, LUA_INTFRMLEN, lua_pop, LUA_QL, luaL_addchar, luaL_addsize, luaL_addvalue(), luaL_argcheck, luaL_argerror(), luaL_buffinit(), luaL_checkint, luaL_checklstring(), luaL_checknumber(), luaL_error(), luaL_prepbuffsize(), luaL_pushresult(), luaL_tolstring(), MAX_FORMAT, MAX_ITEM, and scanformat().
static int str_gsub (lua_State * L) static
Definition at line 735 of file lstrlib.c.
References add_value(), MatchState::L, MatchState::level, lua_assert, lua_pushinteger(), LUA_TFUNCTION, LUA_TNUMBER, LUA_TSTRING, LUA_TTABLE, lua_type(), luaL_addchar, luaL_addlstring(), luaL_argcheck, luaL_buffinit(), luaL_checklstring(), luaL_optinteger(), luaL_pushresult(), match(), MatchState::matchdepth, MAXCCALLS, MatchState::p_end, MatchState::src_end, and MatchState::src_init.
static int str_len (lua_State * L) static
Definition at line 37 of file lstrlib.c.
References lua_pushinteger(), and luaL_checklstring().
static int str_lower (lua_State * L) static
Definition at line 79 of file lstrlib.c.
References luaL_buffinitsize(), luaL_checklstring(), luaL_pushresultsize(), and uchar.
static int str_match (lua_State * L) static
Definition at line 634 of file lstrlib.c.
References str_find_aux().
static int str_rep (lua_State * L) static
Definition at line 108 of file lstrlib.c.
References lua_pushliteral, luaL_buffinitsize(), luaL_checkint, luaL_checklstring(), luaL_error(), luaL_optlstring(), luaL_pushresultsize(), and MAXSIZE.
static int str_reverse (lua_State * L) static
Definition at line 67 of file lstrlib.c.
References luaL_buffinitsize(), luaL_checklstring(), and luaL_pushresultsize().
static int str_sub (lua_State * L) static
Definition at line 53 of file lstrlib.c.
References lua_pushliteral, lua_pushlstring(), luaL_checkinteger(), luaL_checklstring(), luaL_optinteger(), and posrelat().
static int str_upper (lua_State * L) static
Definition at line 92 of file lstrlib.c.
References luaL_buffinitsize(), luaL_checklstring(), luaL_pushresultsize(), and uchar.
static int writer (lua_State * L, const void * b, size_t size, void * B) static
Definition at line 167 of file lstrlib.c.
References luaL_addlstring().
Referenced by str_dump().
Variable Documentation
const luaL_Reg strlib[] static
Initial value:
= {
  {"byte", str_byte},
  {"char", str_char},
  {"dump", str_dump},
  {"find", str_find},
  {"format", str_format},
  {"gmatch", gmatch},
  {"gsub", str_gsub},
  {"len", str_len},
  {"lower", str_lower},
  {"match", str_match},
  {"rep", str_rep},
  {"reverse", str_reverse},
  {"sub", str_sub},
  {"upper", str_upper},
  {NULL, NULL}
}
Definition at line 980 of file lstrlib.c.