Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lundump.c File Reference
lundump.c File Reference
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstring.h"
#include "lundump.h"
#include "lzio.h"
Classes
struct LoadState
Macros
#define lundump_c
#define LUA_CORE
#define LoadMem(S, b, n, size) LoadBlock(S,b,(n)*(size))
#define LoadByte(S) (lu_byte)LoadChar(S)
#define LoadVar(S, x) LoadMem(S,&x,1,sizeof(x))
#define LoadVector(S, b, n, size) LoadMem(S,b,n,size)
#define luai_verifycode(L, b, f) /* empty */
#define N0 LUAC_HEADERSIZE
#define N1 (sizeof(LUA_SIGNATURE)-sizeof(char))
#define N2 N1+2
#define N3 N2+6
#define MYINT(s) (s[0]-'0')
#define VERSION MYINT(LUA_VERSION_MAJOR)*16+MYINT(LUA_VERSION_MINOR)
#define FORMAT 0 /* this is the official format */
Functions
static l_noret error (LoadState *S, const char *why)
static void LoadBlock (LoadState *S, void *b, size_t size)
static int LoadChar (LoadState *S)
static int LoadInt (LoadState *S)
static lua_Number LoadNumber (LoadState *S)
static TString * LoadString (LoadState *S)
static void LoadCode (LoadState *S, Proto *f)
static void LoadFunction (LoadState *S, Proto *f)
static void LoadConstants (LoadState *S, Proto *f)
static void LoadUpvalues (LoadState *S, Proto *f)
static void LoadDebug (LoadState *S, Proto *f)
static void LoadHeader (LoadState *S)
Closure * luaU_undump (lua_State *L, ZIO *Z, Mbuffer *buff, const char *name)
void luaU_header (lu_byte *h)
Macro Definition Documentation
#define FORMAT 0 /* this is the official format */
Definition at line 237 of file lundump.c.
Referenced by luaU_header().
#define LoadByte (S) (lu_byte)LoadChar(S)
Definition at line 37 of file lundump.c.
Referenced by LoadFunction(), and LoadUpvalues().
#define LoadMem (S, b, n, size) LoadBlock(S,b,(n)*(size))
Definition at line 36 of file lundump.c.
#define LoadVar (S, x) LoadMem(S,&x,1,sizeof(x))
Definition at line 38 of file lundump.c.
Referenced by LoadChar(), LoadInt(), LoadNumber(), and LoadString().
#define LoadVector (S, b, n, size) LoadMem(S,b,n,size)
Definition at line 39 of file lundump.c.
Referenced by LoadCode(), and LoadDebug().
#define LUA_CORE
Definition at line 10 of file lundump.c.
#define luai_verifycode (L, b, f) /* empty */
Definition at line 42 of file lundump.c.
Referenced by luaU_undump().
#define lundump_c
Definition at line 9 of file lundump.c.
#define MYINT (s) (s[0]-'0')
Definition at line 235 of file lundump.c.
#define N0 LUAC_HEADERSIZE
Definition at line 185 of file lundump.c.
Referenced by LoadHeader().
#define N1 (sizeof(LUA_SIGNATURE)-sizeof(char))
Definition at line 186 of file lundump.c.
Referenced by LoadHeader().
#define N2 N1+2
Definition at line 187 of file lundump.c.
Referenced by LoadHeader().
#define N3 N2+6
Definition at line 188 of file lundump.c.
Referenced by LoadHeader().
#define VERSION MYINT(LUA_VERSION_MAJOR)*16+MYINT(LUA_VERSION_MINOR)
Definition at line 236 of file lundump.c.
Referenced by luaU_header().
Function Documentation
static l_noret error (LoadState * S, const char * why) static
Definition at line 30 of file lundump.c.
References LoadState::L, LUA_ERRSYNTAX, luaD_throw(), luaO_pushfstring(), and LoadState::name.
Referenced by LoadBlock(), LoadHeader(), and LoadInt().
static void LoadBlock (LoadState * S, void * b, size_t size) static
Definition at line 45 of file lundump.c.
References error(), luaZ_read(), and LoadState::Z.
Referenced by LoadHeader(), and LoadString().
static int LoadChar (LoadState * S) static
Definition at line 50 of file lundump.c.
References LoadVar.
Referenced by LoadConstants().
static void LoadCode (LoadState * S, Proto * f) static
Definition at line 86 of file lundump.c.
References Proto::code, LoadState::L, LoadInt(), LoadVector, luaM_newvector, and Proto::sizecode.
Referenced by LoadFunction().
static void LoadConstants (LoadState * S, Proto * f) static
Definition at line 96 of file lundump.c.
References Proto::k, LoadState::L, LoadChar(), LoadFunction(), LoadInt(), LoadNumber(), LoadString(), lua_assert, LUA_TBOOLEAN, LUA_TNIL, LUA_TNUMBER, LUA_TSTRING, luaF_newproto(), luaM_newvector, Proto::p, setbvalue, setnilvalue, setnvalue, setsvalue2n, Proto::sizek, and Proto::sizep.
Referenced by LoadFunction().
static void LoadDebug (LoadState * S, Proto * f) static
Definition at line 149 of file lundump.c.
References LocVar::endpc, LoadState::L, Proto::lineinfo, LoadInt(), LoadString(), LoadVector, Proto::locvars, luaM_newvector, Upvaldesc::name, Proto::sizelineinfo, Proto::sizelocvars, Proto::source, LocVar::startpc, Proto::upvalues, and LocVar::varname.
Referenced by LoadFunction().
static void LoadFunction (LoadState * S, Proto * f) static
Definition at line 171 of file lundump.c.
References Proto::is_vararg, Proto::lastlinedefined, Proto::linedefined, LoadByte, LoadCode(), LoadConstants(), LoadDebug(), LoadInt(), LoadUpvalues(), Proto::maxstacksize, and Proto::numparams.
Referenced by LoadConstants(), and luaU_undump().
static void LoadHeader (LoadState * S) static
Definition at line 190 of file lundump.c.
References error(), LoadBlock(), LUAC_HEADERSIZE, luaU_header(), N0, N1, N2, and N3.
Referenced by luaU_undump().
static int LoadInt (LoadState * S) static
Definition at line 57 of file lundump.c.
References error(), and LoadVar.
Referenced by LoadCode(), LoadConstants(), LoadDebug(), LoadFunction(), and LoadUpvalues().
static lua_Number LoadNumber (LoadState * S) static
Definition at line 65 of file lundump.c.
References LoadVar.
Referenced by LoadConstants().
static TString* LoadString (LoadState * S) static
Definition at line 72 of file lundump.c.
References LoadState::b, LoadState::L, LoadBlock(), LoadVar, luaS_newlstr(), and luaZ_openspace().
Referenced by LoadConstants(), and LoadDebug().
static void LoadUpvalues (LoadState * S, Proto * f) static
Definition at line 135 of file lundump.c.
References Upvaldesc::idx, Upvaldesc::instack, LoadState::L, LoadByte, LoadInt(), luaM_newvector, Upvaldesc::name, Proto::sizeupvalues, and Proto::upvalues.
Referenced by LoadFunction().
void luaU_header (lu_byte * h)
Definition at line 244 of file lundump.c.
References cast_byte, FORMAT, LUA_SIGNATURE, LUAC_TAIL, and VERSION.
Referenced by DumpHeader(), and LoadHeader().
Closure* luaU_undump (lua_State * L, ZIO * Z, Mbuffer * buff, const char * name)
Definition at line 206 of file lundump.c.
References LoadState::b, incr_top, LoadState::L, Closure::l, LoadFunction(), LoadHeader(), LUA_SIGNATURE, luaF_newLclosure(), luaF_newproto(), luai_verifycode, LoadState::name, LClosure::p, setclLvalue, Proto::sizeupvalues, lua_State::top, and LoadState::Z.
Referenced by f_parser().