Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/ltable.c File Reference
ltable.c File Reference
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "lvm.h"
Macros
#define ltable_c
#define LUA_CORE
#define MAXBITS (LUAI_BITSINT-2)
#define MAXASIZE (1 << MAXBITS)
#define hashpow2(t, n) (gnode(t, lmod((n), sizenode(t))))
#define hashstr(t, str) hashpow2(t, (str)->tsv.hash)
#define hashboolean(t, p) hashpow2(t, p)
#define hashmod(t, n) (gnode(t, ((n) % ((sizenode(t)-1)|1))))
#define hashpointer(t, p) hashmod(t, IntPoint(p))
#define dummynode (&dummynode_)
#define isdummy(n) ((n) == dummynode)
Functions
static Node * hashnum (const Table *t, lua_Number n)
static Node * mainposition (const Table *t, const TValue *key)
static int arrayindex (const TValue *key)
static int findindex (lua_State *L, Table *t, StkId key)
int luaH_next (lua_State *L, Table *t, StkId key)
static int computesizes (int nums[], int *narray)
static int countint (const TValue *key, int *nums)
static int numusearray (const Table *t, int *nums)
static int numusehash (const Table *t, int *nums, int *pnasize)
static void setarrayvector (lua_State *L, Table *t, int size)
static void setnodevector (lua_State *L, Table *t, int size)
void luaH_resize (lua_State *L, Table *t, int nasize, int nhsize)
void luaH_resizearray (lua_State *L, Table *t, int nasize)
static void rehash (lua_State *L, Table *t, const TValue *ek)
Table * luaH_new (lua_State *L)
void luaH_free (lua_State *L, Table *t)
static Node * getfreepos (Table *t)
TValue * luaH_newkey (lua_State *L, Table *t, const TValue *key)
const TValue * luaH_getint (Table *t, int key)
const TValue * luaH_getstr (Table *t, TString *key)
const TValue * luaH_get (Table *t, const TValue *key)
TValue * luaH_set (lua_State *L, Table *t, const TValue *key)
void luaH_setint (lua_State *L, Table *t, int key, TValue *value)
static int unbound_search (Table *t, unsigned int j)
int luaH_getn (Table *t)
Variables
static const Node dummynode_
Macro Definition Documentation
#define dummynode (&dummynode_)
Definition at line 67 of file ltable.c.
Referenced by setnodevector().
#define hashboolean (t, p) hashpow2(t, p)
Definition at line 54 of file ltable.c.
Referenced by mainposition().
#define hashmod (t, n) (gnode(t, ((n) % ((sizenode(t)-1)|1))))
Definition at line 61 of file ltable.c.
Referenced by hashnum().
#define hashpointer (t, p) hashmod(t, IntPoint(p))
Definition at line 64 of file ltable.c.
Referenced by mainposition().
#define hashpow2 (t, n) (gnode(t, lmod((n), sizenode(t))))
Definition at line 51 of file ltable.c.
#define hashstr (t, str) hashpow2(t, (str)->tsv.hash)
Definition at line 53 of file ltable.c.
Referenced by luaH_getstr(), and mainposition().
#define isdummy (n) ((n) == dummynode)
Definition at line 69 of file ltable.c.
Referenced by luaH_free(), luaH_getn(), luaH_newkey(), luaH_resize(), and luaH_resizearray().
#define ltable_c
Definition at line 23 of file ltable.c.
#define LUA_CORE
Definition at line 24 of file ltable.c.
#define MAXASIZE (1 << MAXBITS)
Definition at line 48 of file ltable.c.
Referenced by countint().
#define MAXBITS (LUAI_BITSINT-2)
Definition at line 45 of file ltable.c.
Referenced by numusearray(), rehash(), and setnodevector().
Function Documentation
static int arrayindex (const TValue * key) static
Definition at line 127 of file ltable.c.
References cast_num, lua_number2int, nvalue, and ttisnumber.
Referenced by countint(), and findindex().
static int computesizes (int nums[], int * narray) static
Definition at line 196 of file ltable.c.
References lua_assert.
Referenced by rehash().
static int countint (const TValue * key, int * nums) static
Definition at line 218 of file ltable.c.
References arrayindex(), luaO_ceillog2(), and MAXASIZE.
Referenced by numusehash(), and rehash().
static int findindex (lua_State * L, Table * t, StkId key) static
Definition at line 144 of file ltable.c.
References arrayindex(), cast_int, deadvalue, gcvalue, gkey, gnext, gnode, iscollectable, LUA_QL, luaG_runerror(), luaV_rawequalobj, mainposition(), Table::sizearray, ttisdeadkey, and ttisnil.
Referenced by luaH_next().
static Node* getfreepos (Table * t) static
Definition at line 387 of file ltable.c.
References gkey, Table::lastfree, Table::node, and ttisnil.
Referenced by luaH_newkey().
static Node* hashnum (const Table * t, lua_Number n) static
Definition at line 80 of file ltable.c.
References cast, hashmod, and luai_hashnum.
Referenced by luaH_getint(), and mainposition().
void luaH_free (lua_State * L, Table * t)
Definition at line 379 of file ltable.c.
References Table::array, cast, isdummy, luaM_free, luaM_freearray, Table::node, Table::sizearray, and sizenode.
Referenced by freeobj().
const TValue* luaH_get (Table * t, const TValue * key)
Definition at line 481 of file ltable.c.
References cast_num, gkey, gnext, gval, lua_number2int, LUA_TNIL, LUA_TNUMBER, LUA_TSHRSTR, luaH_getint(), luaH_getstr(), luaO_nilobject, luaV_rawequalobj, mainposition(), nvalue, rawtsvalue, and ttype.
Referenced by lua_rawget(), lua_rawgetp(), luaH_set(), luaV_gettable(), and luaV_settable().
const TValue* luaH_getint (Table * t, int key)
Definition at line 446 of file ltable.c.
References Table::array, cast, cast_num, gkey, gnext, gval, hashnum(), luaO_nilobject, nvalue, Table::sizearray, and ttisnumber.
Referenced by lua_getglobal(), lua_load(), lua_rawgeti(), lua_setglobal(), luaH_get(), luaH_setint(), and unbound_search().
int luaH_getn (Table * t)
Definition at line 560 of file ltable.c.
References Table::array, isdummy, Table::node, Table::sizearray, ttisnil, and unbound_search().
Referenced by lua_rawlen(), and luaV_objlen().
const TValue* luaH_getstr (Table * t, TString * key)
Definition at line 466 of file ltable.c.
References eqshrstr, gkey, gnext, gval, hashstr, lua_assert, LUA_TSHRSTR, luaO_nilobject, rawtsvalue, TString::tsv, and ttisshrstring.
Referenced by luaH_get(), luaT_gettm(), and luaT_gettmbyobj().
Table* luaH_new (lua_State * L)
Definition at line 368 of file ltable.c.
References Table::array, cast_byte, Table::flags, GCObject::h, LUA_TTABLE, luaC_newobj(), Table::metatable, setnodevector(), and Table::sizearray.
Referenced by collectvalidlines(), init_registry(), lua_createtable(), luaV_execute(), and open_func().
TValue* luaH_newkey (lua_State * L, Table * t, const TValue * key)
Definition at line 405 of file ltable.c.
References getfreepos(), gkey, gnext, gval, isdummy, lua_assert, luaC_barrierback, luaG_runerror(), luaH_set(), mainposition(), nvalue, obj2gco, rehash(), setnilvalue, setobj2t, ttisnil, and ttisnumber.
Referenced by luaH_set(), luaH_setint(), and luaV_settable().
int luaH_next (lua_State * L, Table * t, StkId key)
Definition at line 169 of file ltable.c.
References Table::array, cast_num, findindex(), gkey, gnode, gval, setnvalue, setobj2s, Table::sizearray, sizenode, and ttisnil.
Referenced by lua_next().
void luaH_resize (lua_State * L, Table * t, int nasize, int nhsize)
Definition at line 304 of file ltable.c.
References Table::array, cast, gkey, gval, isdummy, Table::lsizenode, luaH_set(), luaH_setint(), luaM_freearray, luaM_reallocvector, Table::node, setarrayvector(), setnodevector(), setobjt2t, Table::sizearray, ttisnil, and twoto.
Referenced by init_registry(), lua_createtable(), luaH_resizearray(), luaV_execute(), and rehash().
void luaH_resizearray (lua_State * L, Table * t, int nasize)
Definition at line 337 of file ltable.c.
References isdummy, luaH_resize(), Table::node, and sizenode.
Referenced by luaV_execute().
TValue* luaH_set (lua_State * L, Table * t, const TValue * key)
Definition at line 510 of file ltable.c.
References cast, luaH_get(), luaH_newkey(), and luaO_nilobject.
Referenced by addk(), lua_rawset(), lua_rawsetp(), luaH_newkey(), luaH_resize(), and luaX_newstring().
void luaH_setint (lua_State * L, Table * t, int key, TValue * value)
Definition at line 518 of file ltable.c.
References cast, cast_num, luaH_getint(), luaH_newkey(), luaO_nilobject, setnvalue, and setobj2t.
Referenced by collectvalidlines(), init_registry(), lua_rawseti(), luaH_resize(), and luaV_execute().
static Node* mainposition (const Table * t, const TValue * key) static
Definition at line 97 of file ltable.c.
References bvalue, TString::extra, fvalue, gcvalue, getstr, TString::hash, hashboolean, hashnum(), hashpointer, hashstr, TString::len, LUA_TBOOLEAN, LUA_TLCF, LUA_TLIGHTUSERDATA, LUA_TLNGSTR, LUA_TNUMBER, LUA_TSHRSTR, luaS_hash(), nvalue, pvalue, rawtsvalue, TString::tsv, and ttype.
Referenced by findindex(), luaH_get(), and luaH_newkey().
static int numusearray (const Table * t, int * nums) static
Definition at line 229 of file ltable.c.
References Table::array, MAXBITS, Table::sizearray, and ttisnil.
Referenced by rehash().
static int numusehash (const Table * t, int * nums, int * pnasize) static
Definition at line 254 of file ltable.c.
References countint(), gkey, gval, Table::node, sizenode, and ttisnil.
Referenced by rehash().
static void rehash (lua_State * L, Table * t, const TValue * ek) static
Definition at line 343 of file ltable.c.
References computesizes(), countint(), luaH_resize(), MAXBITS, numusearray(), and numusehash().
Referenced by luaH_newkey().
static void setarrayvector (lua_State * L, Table * t, int size) static
Definition at line 270 of file ltable.c.
References Table::array, luaM_reallocvector, setnilvalue, and Table::sizearray.
Referenced by luaH_resize().
static void setnodevector (lua_State * L, Table * t, int size) static
Definition at line 279 of file ltable.c.
References cast, cast_byte, dummynode, gkey, gnext, gnode, gval, Table::lastfree, Table::lsizenode, luaG_runerror(), luaM_newvector, luaO_ceillog2(), MAXBITS, Table::node, setnilvalue, and twoto.
Referenced by luaH_new(), and luaH_resize().
static int unbound_search (Table * t, unsigned int j) static
Definition at line 532 of file ltable.c.
References cast, luaH_getint(), MAX_INT, and ttisnil.
Referenced by luaH_getn().
Variable Documentation
const Node dummynode_ static
Initial value:
= {
  {NILCONSTANT},
  {{NILCONSTANT, NULL}}
}
Definition at line 71 of file ltable.c.