Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lauxlib.h File Reference
lauxlib.h File Reference
#include <stddef.h>
#include <stdio.h>
#include "lua.h"
Classes
struct luaL_Reg
struct luaL_Buffer
struct luaL_Stream
Macros
#define LUA_ERRFILE (LUA_ERRERR+1)
#define luaL_checkversion(L) luaL_checkversion_(L, LUA_VERSION_NUM)
#define LUA_NOREF (-2)
#define LUA_REFNIL (-1)
#define luaL_loadfile(L, f) luaL_loadfilex(L,f,NULL)
#define luaL_newlibtable(L, l) lua_createtable(L, 0, sizeof(l)/sizeof((l)[0]) - 1)
#define luaL_newlib(L, l) (luaL_newlibtable(L,l), luaL_setfuncs(L,l,0))
#define luaL_argcheck(L, cond, numarg, extramsg) ((void)((cond) || luaL_argerror(L, (numarg), (extramsg))))
#define luaL_checkstring(L, n) (luaL_checklstring(L, (n), NULL))
#define luaL_optstring(L, n, d) (luaL_optlstring(L, (n), (d), NULL))
#define luaL_checkint(L, n) ((int)luaL_checkinteger(L, (n)))
#define luaL_optint(L, n, d) ((int)luaL_optinteger(L, (n), (d)))
#define luaL_checklong(L, n) ((long)luaL_checkinteger(L, (n)))
#define luaL_optlong(L, n, d) ((long)luaL_optinteger(L, (n), (d)))
#define luaL_typename(L, i) lua_typename(L, lua_type(L,(i)))
#define luaL_dofile(L, fn) (luaL_loadfile(L, fn) || lua_pcall(L, 0, LUA_MULTRET, 0))
#define luaL_dostring(L, s) (luaL_loadstring(L, s) || lua_pcall(L, 0, LUA_MULTRET, 0))
#define luaL_getmetatable(L, n) (lua_getfield(L, LUA_REGISTRYINDEX, (n)))
#define luaL_opt(L, f, n, d) (lua_isnoneornil(L,(n)) ? (d) : f(L,(n)))
#define luaL_loadbuffer(L, s, sz, n) luaL_loadbufferx(L,s,sz,n,NULL)
#define luaL_addchar(B, c)
#define luaL_addsize(B, s) ((B)->n += (s))
#define luaL_prepbuffer(B) luaL_prepbuffsize(B, LUAL_BUFFERSIZE)
#define LUA_FILEHANDLE "FILE*"
Typedefs
typedef struct luaL_Reg luaL_Reg
typedef struct luaL_Buffer luaL_Buffer
typedef struct luaL_Stream luaL_Stream
Functions
LUALIB_API void() luaL_checkversion_ (lua_State *L, lua_Number ver)
LUALIB_API int() luaL_getmetafield (lua_State *L, int obj, const char *e)
LUALIB_API int() luaL_callmeta (lua_State *L, int obj, const char *e)
LUALIB_API const char *() luaL_tolstring (lua_State *L, int idx, size_t *len)
LUALIB_API int() luaL_argerror (lua_State *L, int numarg, const char *extramsg)
LUALIB_API const char *() luaL_checklstring (lua_State *L, int numArg, size_t *l)
LUALIB_API const char *() luaL_optlstring (lua_State *L, int numArg, const char *def, size_t *l)
LUALIB_API lua_Number() luaL_checknumber (lua_State *L, int numArg)
LUALIB_API lua_Number() luaL_optnumber (lua_State *L, int nArg, lua_Number def)
LUALIB_API lua_Integer() luaL_checkinteger (lua_State *L, int numArg)
LUALIB_API lua_Integer() luaL_optinteger (lua_State *L, int nArg, lua_Integer def)
LUALIB_API lua_Unsigned() luaL_checkunsigned (lua_State *L, int numArg)
LUALIB_API lua_Unsigned() luaL_optunsigned (lua_State *L, int numArg, lua_Unsigned def)
LUALIB_API void() luaL_checkstack (lua_State *L, int sz, const char *msg)
LUALIB_API void() luaL_checktype (lua_State *L, int narg, int t)
LUALIB_API void() luaL_checkany (lua_State *L, int narg)
LUALIB_API int() luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void() luaL_setmetatable (lua_State *L, const char *tname)
LUALIB_API void *() luaL_testudata (lua_State *L, int ud, const char *tname)
LUALIB_API void *() luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API void() luaL_where (lua_State *L, int lvl)
LUALIB_API int() luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int() luaL_checkoption (lua_State *L, int narg, const char *def, const char *const lst[])
LUALIB_API int() luaL_fileresult (lua_State *L, int stat, const char *fname)
LUALIB_API int() luaL_execresult (lua_State *L, int stat)
LUALIB_API int() luaL_ref (lua_State *L, int t)
LUALIB_API void() luaL_unref (lua_State *L, int t, int ref)
LUALIB_API int() luaL_loadfilex (lua_State *L, const char *filename, const char *mode)
LUALIB_API int() luaL_loadbufferx (lua_State *L, const char *buff, size_t sz, const char *name, const char *mode)
LUALIB_API int() luaL_loadstring (lua_State *L, const char *s)
LUALIB_API lua_State *() luaL_newstate (void)
LUALIB_API int() luaL_len (lua_State *L, int idx)
LUALIB_API const char *() luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
LUALIB_API void() luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup)
LUALIB_API int() luaL_getsubtable (lua_State *L, int idx, const char *fname)
LUALIB_API void() luaL_traceback (lua_State *L, lua_State *L1, const char *msg, int level)
LUALIB_API void() luaL_requiref (lua_State *L, const char *modname, lua_CFunction openf, int glb)
LUALIB_API void() luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API char *() luaL_prepbuffsize (luaL_Buffer *B, size_t sz)
LUALIB_API void() luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void() luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void() luaL_addvalue (luaL_Buffer *B)
LUALIB_API void() luaL_pushresult (luaL_Buffer *B)
LUALIB_API void() luaL_pushresultsize (luaL_Buffer *B, size_t sz)
LUALIB_API char *() luaL_buffinitsize (lua_State *L, luaL_Buffer *B, size_t sz)
Macro Definition Documentation
#define LUA_ERRFILE (LUA_ERRERR+1)
Definition at line 20 of file lauxlib.h.
Referenced by errfile().
#define LUA_FILEHANDLE "FILE*"
Definition at line 185 of file lauxlib.h.
Referenced by createmeta(), io_type(), and newprefile().
#define LUA_NOREF (-2)
Definition at line 69 of file lauxlib.h.
#define LUA_REFNIL (-1)
Definition at line 70 of file lauxlib.h.
Referenced by luaL_ref().
#define luaL_addchar (B, c)
Value:
((void)((B)->n < (B)->size || luaL_prepbuffsize((B), 1)), \
   ((B)->b[(B)->n++] = (c)))
Definition at line 152 of file lauxlib.h.
Referenced by add_s(), addquoted(), os_date(), str_format(), and str_gsub().
#define luaL_addsize (B, s) ((B)->n += (s))
Definition at line 156 of file lauxlib.h.
Referenced by luaL_addlstring(), luaL_pushresultsize(), read_all(), read_chars(), read_line(), and str_format().
#define luaL_argcheck (L, cond, numarg, extramsg) ((void)((cond) || luaL_argerror(L, (numarg), (extramsg))))
Definition at line 113 of file lauxlib.h.
Referenced by aux_lines(), checkupval(), db_setmetatable(), db_upvaluejoin(), f_seek(), fieldargs(), g_read(), io_open(), luaB_coresume(), luaB_costatus(), luaB_rawlen(), luaB_select(), luaB_setmetatable(), luaB_tonumber(), luaB_xpcall(), math_random(), str_char(), str_format(), str_gsub(), tinsert(), and tremove().
#define luaL_checkint (L, n) ((int)luaL_checkinteger(L, (n)))
Definition at line 117 of file lauxlib.h.
Referenced by auxupvalue(), b_arshift(), b_lrot(), b_lshift(), b_rrot(), b_rshift(), checkupval(), db_getlocal(), db_setlocal(), fieldargs(), ipairsaux(), luaB_select(), luaB_tonumber(), math_ldexp(), str_char(), str_format(), str_rep(), tconcat(), tinsert(), and unpack().
#define luaL_checklong (L, n) ((long)luaL_checkinteger(L, (n)))
Definition at line 119 of file lauxlib.h.
#define luaL_checkstring (L, n) (luaL_checklstring(L, (n), NULL))
Definition at line 115 of file lauxlib.h.
Referenced by db_sethook(), gmatch(), io_lines(), io_open(), io_popen(), ll_loadlib(), ll_require(), ll_searchpath(), luaL_checkoption(), os_getenv(), os_remove(), os_rename(), searcher_C(), searcher_Croot(), searcher_Lua(), and searcher_preload().
#define luaL_checkversion (L) luaL_checkversion_(L, LUA_VERSION_NUM)
Definition at line 30 of file lauxlib.h.
Referenced by luaL_setfuncs().
#define luaL_dofile (L, fn) (luaL_loadfile(L, fn) || lua_pcall(L, 0, LUA_MULTRET, 0))
Definition at line 124 of file lauxlib.h.
#define luaL_dostring (L, s) (luaL_loadstring(L, s) || lua_pcall(L, 0, LUA_MULTRET, 0))
Definition at line 127 of file lauxlib.h.
#define luaL_getmetatable (L, n) (lua_getfield(L, LUA_REGISTRYINDEX, (n)))
Definition at line 130 of file lauxlib.h.
Referenced by luaL_newmetatable(), luaL_setmetatable(), and luaL_testudata().
#define luaL_loadbuffer (L, s, sz, n) luaL_loadbufferx(L,s,sz,n,NULL)
Definition at line 134 of file lauxlib.h.
Referenced by db_debug(), and luaL_loadstring().
#define luaL_loadfile (L, f) luaL_loadfilex(L,f,NULL)
Definition at line 78 of file lauxlib.h.
Referenced by luaB_dofile(), and searcher_Lua().
#define luaL_newlib (L, l) (luaL_newlibtable(L,l), luaL_setfuncs(L,l,0))
Definition at line 111 of file lauxlib.h.
Referenced by luaopen_bit32(), luaopen_coroutine(), luaopen_debug(), luaopen_io(), luaopen_math(), luaopen_os(), luaopen_package(), luaopen_string(), and luaopen_table().
#define luaL_newlibtable (L, l) lua_createtable(L, 0, sizeof(l)/sizeof((l)[0]) - 1)
Definition at line 108 of file lauxlib.h.
#define luaL_opt (L, f, n, d) (lua_isnoneornil(L,(n)) ? (d) : f(L,(n)))
Definition at line 132 of file lauxlib.h.
Referenced by luaL_optinteger(), luaL_optnumber(), luaL_optunsigned(), os_date(), tconcat(), and unpack().
#define luaL_optint (L, n, d) ((int)luaL_optinteger(L, (n), (d)))
Definition at line 118 of file lauxlib.h.
Referenced by db_sethook(), db_traceback(), fieldargs(), luaB_collectgarbage(), luaB_error(), os_exit(), tconcat(), tremove(), and unpack().
#define luaL_optlong (L, n, d) ((long)luaL_optinteger(L, (n), (d)))
Definition at line 120 of file lauxlib.h.
#define luaL_optstring (L, n, d) (luaL_optlstring(L, (n), (d), NULL))
Definition at line 116 of file lauxlib.h.
Referenced by db_getinfo(), io_open(), io_popen(), ll_searchpath(), luaB_assert(), luaB_dofile(), luaB_load(), luaB_loadfile(), luaL_checkoption(), os_date(), os_execute(), and os_setlocale().
#define luaL_prepbuffer (B) luaL_prepbuffsize(B, LUAL_BUFFERSIZE)
Definition at line 167 of file lauxlib.h.
Referenced by read_line().
#define luaL_typename (L, i) lua_typename(L, lua_type(L,(i)))
Definition at line 122 of file lauxlib.h.
Referenced by add_value(), addfield(), luaB_type(), luaL_tolstring(), and typeerror().
Typedef Documentation
typedef struct luaL_Buffer luaL_Buffer
typedef struct luaL_Reg luaL_Reg
typedef struct luaL_Stream luaL_Stream
Function Documentation
LUALIB_API void() luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 459 of file lauxlib.c.
References luaL_addsize, and luaL_prepbuffsize().
Referenced by add_s(), luaL_addstring(), luaL_addvalue(), luaL_gsub(), os_date(), str_gsub(), tconcat(), and writer().
LUALIB_API void() luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 466 of file lauxlib.c.
References luaL_addlstring().
Referenced by addquoted(), and luaL_gsub().
LUALIB_API void() luaL_addvalue (luaL_Buffer * B)
Definition at line 485 of file lauxlib.c.
References buffonstack, luaL_Buffer::L, lua_insert(), lua_remove(), lua_tolstring(), and luaL_addlstring().
Referenced by add_s(), add_value(), addfield(), findloader(), searchpath(), and str_format().
LUALIB_API int() luaL_argerror (lua_State * L, int numarg, const char * extramsg)
Definition at line 153 of file lauxlib.c.
References lua_getinfo(), lua_getstack(), LUA_QS, lua_tostring, luaL_error(), lua_Debug::name, lua_Debug::namewhat, and pushglobalfuncname().
Referenced by checkoption(), db_getinfo(), db_getlocal(), db_setlocal(), db_setuservalue(), g_read(), luaL_checkany(), luaL_checkoption(), str_format(), and typeerror().
LUALIB_API void() luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 496 of file lauxlib.c.
References luaL_Buffer::b, luaL_Buffer::initb, luaL_Buffer::L, LUAL_BUFFERSIZE, luaL_Buffer::n, and luaL_Buffer::size.
Referenced by findloader(), luaL_buffinitsize(), luaL_gsub(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), and tconcat().
LUALIB_API char*() luaL_buffinitsize (lua_State * L, luaL_Buffer * B, size_t sz)
Definition at line 504 of file lauxlib.c.
References luaL_buffinit(), and luaL_prepbuffsize().
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
LUALIB_API int() luaL_callmeta (lua_State * L, int obj, const char * e)
Definition at line 715 of file lauxlib.c.
References lua_absindex(), lua_call, lua_pushvalue(), and luaL_getmetafield().
Referenced by luaL_tolstring().
LUALIB_API void() luaL_checkany (lua_State * L, int narg)
Definition at line 351 of file lauxlib.c.
References LUA_TNONE, lua_type(), and luaL_argerror().
Referenced by db_getmetatable(), db_setlocal(), db_setupvalue(), io_type(), luaB_getmetatable(), luaB_pcall(), luaB_rawequal(), luaB_rawget(), luaB_rawset(), luaB_tonumber(), luaB_tostring(), and luaB_type().
LUALIB_API lua_Integer() luaL_checkinteger (lua_State * L, int numArg)
Definition at line 389 of file lauxlib.c.
References LUA_TNUMBER, lua_tointegerx(), and tag_error().
Referenced by luaL_optinteger(), and str_sub().
LUALIB_API const char*() luaL_checklstring (lua_State * L, int numArg, size_t * l)
Definition at line 357 of file lauxlib.c.
References lua_tolstring(), LUA_TSTRING, and tag_error().
Referenced by addquoted(), g_write(), luaB_tonumber(), luaL_optlstring(), str_byte(), str_find_aux(), str_format(), str_gsub(), str_len(), str_lower(), str_rep(), str_reverse(), str_sub(), and str_upper().
LUALIB_API lua_Number() luaL_checknumber (lua_State * L, int numArg)
Definition at line 375 of file lauxlib.c.
References LUA_TNUMBER, lua_tonumberx(), and tag_error().
Referenced by luaL_optnumber(), math_abs(), math_acos(), math_asin(), math_atan(), math_atan2(), math_ceil(), math_cos(), math_cosh(), math_deg(), math_exp(), math_floor(), math_fmod(), math_frexp(), math_ldexp(), math_log(), math_max(), math_min(), math_modf(), math_pow(), math_rad(), math_random(), math_sin(), math_sinh(), math_sqrt(), math_tan(), math_tanh(), os_date(), os_difftime(), and str_format().
LUALIB_API int() luaL_checkoption (lua_State * L, int narg, const char * def, const char *const lst[])
Definition at line 320 of file lauxlib.c.
References lua_pushfstring(), LUA_QS, luaL_argerror(), luaL_checkstring, and luaL_optstring.
Referenced by f_seek(), f_setvbuf(), luaB_collectgarbage(), and os_setlocale().
LUALIB_API void() luaL_checkstack (lua_State * L, int sz, const char * msg)
Definition at line 333 of file lauxlib.c.
References lua_checkstack(), LUA_MINSTACK, and luaL_error().
Referenced by g_read(), generic_reader(), luaL_setfuncs(), push_captures(), sort(), and str_byte().
LUALIB_API void() luaL_checktype (lua_State * L, int narg, int t)
Definition at line 345 of file lauxlib.c.
References lua_type(), and tag_error().
Referenced by auxupvalue(), checkupval(), db_sethook(), db_setuservalue(), ipairsaux(), luaB_cocreate(), luaB_load(), luaB_next(), luaB_rawget(), luaB_rawset(), luaB_setmetatable(), os_time(), pairsmeta(), sort(), str_dump(), tconcat(), and unpack().
LUALIB_API void*() luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 305 of file lauxlib.c.
References luaL_testudata(), and typeerror().
LUALIB_API lua_Unsigned() luaL_checkunsigned (lua_State * L, int numArg)
Definition at line 398 of file lauxlib.c.
References LUA_TNUMBER, lua_tounsignedx(), and tag_error().
Referenced by andaux(), b_arshift(), b_extract(), b_lshift(), b_not(), b_or(), b_replace(), b_rot(), b_rshift(), b_xor(), luaL_optunsigned(), and math_randomseed().
LUALIB_API void() luaL_checkversion_ (lua_State * L, lua_Number ver)
Definition at line 944 of file lauxlib.c.
References lua_pop, lua_pushnumber(), lua_tointeger, lua_tounsigned, lua_version(), and luaL_error().
LUALIB_API int() luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 196 of file lauxlib.c.
References lua_concat(), lua_error(), lua_pushvfstring(), and luaL_where().
Referenced by add_s(), add_value(), addfield(), auxsort(), capture_to_close(), check_capture(), checkload(), classend(), fieldargs(), findfile(), findloader(), generic_reader(), getfield(), getiofile(), io_readline(), luaB_assert(), luaB_print(), luaB_setmetatable(), luaL_argerror(), luaL_checkstack(), luaL_checkversion_(), luaL_len(), luaL_prepbuffsize(), match(), matchbalance(), math_random(), opencheck(), os_tmpname(), push_onecapture(), scanformat(), start_capture(), str_byte(), str_dump(), str_format(), str_rep(), tinsert(), tofile(), and unpack().
LUALIB_API int() luaL_execresult (lua_State * L, int stat)
Definition at line 247 of file lauxlib.c.
References inspectstat, lua_pushboolean(), lua_pushinteger(), lua_pushnil(), lua_pushstring(), and luaL_fileresult().
Referenced by io_pclose(), and os_execute().
LUALIB_API int() luaL_fileresult (lua_State * L, int stat, const char * fname)
Definition at line 207 of file lauxlib.c.
References lua_pushboolean(), lua_pushfstring(), lua_pushinteger(), lua_pushnil(), and lua_pushstring().
Referenced by f_flush(), f_seek(), f_setvbuf(), g_read(), g_write(), io_fclose(), io_flush(), io_open(), io_popen(), io_tmpfile(), luaL_execresult(), os_remove(), and os_rename().
LUALIB_API int() luaL_getmetafield (lua_State * L, int obj, const char * e)
Definition at line 699 of file lauxlib.c.
References lua_getmetatable(), lua_isnil, lua_pop, lua_pushstring(), lua_rawget(), and lua_remove().
Referenced by luaB_getmetatable(), luaB_setmetatable(), luaL_callmeta(), and pairsmeta().
LUALIB_API int() luaL_getsubtable (lua_State * L, int idx, const char * fname)
Definition at line 866 of file lauxlib.c.
References lua_absindex(), lua_getfield(), lua_istable, lua_newtable, lua_pop, lua_pushvalue(), and lua_setfield().
Referenced by luaL_openlibs(), luaL_requiref(), and luaopen_package().
LUALIB_API const char*() luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 902 of file lauxlib.c.
References lua_tostring, luaL_addlstring(), luaL_addstring(), luaL_buffinit(), and luaL_pushresult().
Referenced by loadfunc(), searchpath(), and setpath().
LUALIB_API int() luaL_len (lua_State * L, int idx)
Definition at line 725 of file lauxlib.c.
References lua_len(), lua_pop, lua_tointegerx(), and luaL_error().
Referenced by gctm(), ll_addtoclib(), tconcat(), and unpack().
LUALIB_API int() luaL_loadbufferx (lua_State * L, const char * buff, size_t sz, const char * name, const char * mode)
Definition at line 682 of file lauxlib.c.
References getS(), lua_load(), LoadS::s, and LoadS::size.
Referenced by luaB_load().
LUALIB_API int() luaL_loadfilex (lua_State * L, const char * filename, const char * mode)
Definition at line 630 of file lauxlib.c.
References LoadF::buff, errfile(), LoadF::f, getF(), lua_gettop(), lua_load(), lua_pushfstring(), lua_pushliteral, lua_remove(), lua_settop(), LUA_SIGNATURE, lua_tostring, LoadF::n, and skipcomment().
Referenced by luaB_loadfile().
LUALIB_API int() luaL_loadstring (lua_State * L, const char * s)
Definition at line 691 of file lauxlib.c.
References luaL_loadbuffer.
Referenced by KenshoLuaWrapper::evaluate.
LUALIB_API int() luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 272 of file lauxlib.c.
References lua_isnil, lua_newtable, lua_pop, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), and luaL_getmetatable.
Referenced by createmeta().
LUALIB_API lua_State*() luaL_newstate (void)
Definition at line 937 of file lauxlib.c.
References l_alloc(), lua_atpanic(), lua_newstate(), and panic().
Referenced by KenshoLuaWrapper::evaluate.
LUALIB_API lua_Integer() luaL_optinteger (lua_State * L, int nArg, lua_Integer def)
Definition at line 407 of file lauxlib.c.
References luaL_checkinteger(), and luaL_opt.
Referenced by f_setvbuf(), str_byte(), str_find_aux(), str_gsub(), and str_sub().
LUALIB_API const char*() luaL_optlstring (lua_State * L, int numArg, const char * def, size_t * l)
Definition at line 364 of file lauxlib.c.
References lua_isnoneornil, and luaL_checklstring().
Referenced by str_rep(), and tconcat().
LUALIB_API lua_Number() luaL_optnumber (lua_State * L, int nArg, lua_Number def)
Definition at line 384 of file lauxlib.c.
References luaL_checknumber(), and luaL_opt.
Referenced by f_seek(), and os_difftime().
LUALIB_API lua_Unsigned() luaL_optunsigned (lua_State * L, int numArg, lua_Unsigned def)
Definition at line 413 of file lauxlib.c.
References luaL_checkunsigned(), and luaL_opt.
LUALIB_API char*() luaL_prepbuffsize (luaL_Buffer * B, size_t sz)
Definition at line 437 of file lauxlib.c.
References luaL_Buffer::b, buffonstack, luaL_Buffer::L, lua_newuserdata(), lua_remove(), luaL_error(), luaL_Buffer::n, and luaL_Buffer::size.
Referenced by luaL_addlstring(), luaL_buffinitsize(), read_all(), read_chars(), and str_format().
LUALIB_API void() luaL_pushresult (luaL_Buffer * B)
Definition at line 471 of file lauxlib.c.
References luaL_Buffer::b, buffonstack, luaL_Buffer::L, lua_pushlstring(), lua_remove(), and luaL_Buffer::n.
Referenced by findloader(), luaL_gsub(), luaL_pushresultsize(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), and tconcat().
LUALIB_API void() luaL_pushresultsize (luaL_Buffer * B, size_t sz)
Definition at line 479 of file lauxlib.c.
References luaL_addsize, and luaL_pushresult().
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
LUALIB_API int() luaL_ref (lua_State * L, int t)
Definition at line 522 of file lauxlib.c.
References freelist, lua_absindex(), lua_isnil, lua_pop, lua_rawgeti(), lua_rawlen(), lua_rawseti(), LUA_REFNIL, and lua_tointeger.
LUALIB_API void() luaL_requiref (lua_State * L, const char * modname, lua_CFunction openf, int glb)
Definition at line 886 of file lauxlib.c.
References lua_call, lua_pop, lua_pushcfunction, lua_pushstring(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_setglobal(), and luaL_getsubtable().
Referenced by luaL_openlibs().
LUALIB_API void() luaL_setfuncs (lua_State * L, const luaL_Reg * l, int nup)
Definition at line 848 of file lauxlib.c.
References luaL_Reg::func, lua_pop, lua_pushcclosure(), lua_pushvalue(), lua_setfield(), luaL_checkstack(), luaL_checkversion, and luaL_Reg::name.
Referenced by createmeta(), luaopen_base(), and luaopen_package().
LUALIB_API void() luaL_setmetatable (lua_State * L, const char * tname)
Definition at line 284 of file lauxlib.c.
References lua_setmetatable(), and luaL_getmetatable.
Referenced by newprefile().
LUALIB_API void*() luaL_testudata (lua_State * L, int ud, const char * tname)
Definition at line 290 of file lauxlib.c.
References lua_getmetatable(), lua_pop, lua_rawequal(), lua_touserdata(), and luaL_getmetatable.
Referenced by io_type(), and luaL_checkudata().
LUALIB_API const char*() luaL_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 737 of file lauxlib.c.
References lua_pushfstring(), lua_pushliteral, lua_pushstring(), lua_pushvalue(), LUA_TBOOLEAN, LUA_TNIL, LUA_TNUMBER, lua_toboolean(), lua_tolstring(), lua_topointer(), LUA_TSTRING, lua_type(), luaL_callmeta(), and luaL_typename.
Referenced by luaB_tostring(), and str_format().
LUALIB_API void() luaL_traceback (lua_State * L, lua_State * L1, const char * msg, int level)
Definition at line 116 of file lauxlib.c.
References countlevels(), lua_Debug::currentline, lua_Debug::istailcall, LEVELS1, LEVELS2, lua_concat(), lua_getinfo(), lua_getstack(), lua_gettop(), lua_pushfstring(), lua_pushliteral, pushfuncname(), and lua_Debug::short_src.
Referenced by db_traceback().
LUALIB_API void() luaL_unref (lua_State * L, int t, int ref)
Definition at line 543 of file lauxlib.c.
References freelist, lua_absindex(), lua_pushinteger(), lua_rawgeti(), and lua_rawseti().
LUALIB_API void() luaL_where (lua_State * L, int lvl)
Definition at line 183 of file lauxlib.c.
References lua_Debug::currentline, lua_getinfo(), lua_getstack(), lua_pushfstring(), lua_pushliteral, and lua_Debug::short_src.
Referenced by luaB_auxwrap(), luaB_error(), and luaL_error().