Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/ltable.h File Reference
ltable.h File Reference
#include "lobject.h"
Macros
#define gnode(t, i) (&(t)->node[i])
#define gkey(n) (&(n)->i_key.tvk)
#define gval(n) (&(n)->i_val)
#define gnext(n) ((n)->i_key.nk.next)
#define invalidateTMcache(t) ((t)->flags = 0)
#define keyfromval(v) (gkey(cast(Node *, cast(char *, (v)) - offsetof(Node, i_val))))
Functions
LUAI_FUNC const TValue * luaH_getint (Table *t, int key)
LUAI_FUNC void luaH_setint (lua_State *L, Table *t, int key, TValue *value)
LUAI_FUNC const TValue * luaH_getstr (Table *t, TString *key)
LUAI_FUNC const TValue * luaH_get (Table *t, const TValue *key)
LUAI_FUNC TValue * luaH_newkey (lua_State *L, Table *t, const TValue *key)
LUAI_FUNC TValue * luaH_set (lua_State *L, Table *t, const TValue *key)
LUAI_FUNC Table * luaH_new (lua_State *L)
LUAI_FUNC void luaH_resize (lua_State *L, Table *t, int nasize, int nhsize)
LUAI_FUNC void luaH_resizearray (lua_State *L, Table *t, int nasize)
LUAI_FUNC void luaH_free (lua_State *L, Table *t)
LUAI_FUNC int luaH_next (lua_State *L, Table *t, StkId key)
LUAI_FUNC int luaH_getn (Table *t)
Macro Definition Documentation
#define gkey (n) (&(n)->i_key.tvk)
Definition at line 14 of file ltable.h.
Referenced by clearkeys(), findindex(), getfreepos(), luaH_get(), luaH_getint(), luaH_getstr(), luaH_newkey(), luaH_next(), luaH_resize(), numusehash(), removeentry(), setnodevector(), traverseephemeron(), traversestrongtable(), and traverseweakvalue().
#define gnext (n) ((n)->i_key.nk.next)
Definition at line 16 of file ltable.h.
Referenced by findindex(), luaH_get(), luaH_getint(), luaH_getstr(), luaH_newkey(), and setnodevector().
#define gnode (t, i) (&(t)->node[i])
Definition at line 13 of file ltable.h.
Referenced by clearkeys(), clearvalues(), findindex(), luaH_next(), setnodevector(), traverseephemeron(), traversestrongtable(), and traverseweakvalue().
#define gval (n) (&(n)->i_val)
Definition at line 15 of file ltable.h.
Referenced by clearkeys(), clearvalues(), luaH_get(), luaH_getint(), luaH_getstr(), luaH_newkey(), luaH_next(), luaH_resize(), numusehash(), removeentry(), setnodevector(), traverseephemeron(), traversestrongtable(), and traverseweakvalue().
#define invalidateTMcache (t) ((t)->flags = 0)
Definition at line 18 of file ltable.h.
Referenced by lua_rawset(), and luaV_settable().
#define keyfromval (v) (gkey(cast(Node *, cast(char *, (v)) - offsetof(Node, i_val))))
Definition at line 21 of file ltable.h.
Referenced by luaX_newstring().
Function Documentation
LUAI_FUNC void luaH_free (lua_State * L, Table * t)
Definition at line 379 of file ltable.c.
References Table::array, cast, isdummy, luaM_free, luaM_freearray, Table::node, Table::sizearray, and sizenode.
Referenced by freeobj().
LUAI_FUNC const TValue* luaH_get (Table * t, const TValue * key)
Definition at line 481 of file ltable.c.
References cast_num, gkey, gnext, gval, lua_number2int, LUA_TNIL, LUA_TNUMBER, LUA_TSHRSTR, luaH_getint(), luaH_getstr(), luaO_nilobject, luaV_rawequalobj, mainposition(), nvalue, rawtsvalue, and ttype.
Referenced by lua_rawget(), lua_rawgetp(), luaH_set(), luaV_gettable(), and luaV_settable().
LUAI_FUNC const TValue* luaH_getint (Table * t, int key)
Definition at line 446 of file ltable.c.
References Table::array, cast, cast_num, gkey, gnext, gval, hashnum(), luaO_nilobject, nvalue, Table::sizearray, and ttisnumber.
Referenced by lua_getglobal(), lua_load(), lua_rawgeti(), lua_setglobal(), luaH_get(), luaH_setint(), and unbound_search().
LUAI_FUNC int luaH_getn (Table * t)
Definition at line 560 of file ltable.c.
References Table::array, isdummy, Table::node, Table::sizearray, ttisnil, and unbound_search().
Referenced by lua_rawlen(), and luaV_objlen().
LUAI_FUNC const TValue* luaH_getstr (Table * t, TString * key)
Definition at line 466 of file ltable.c.
References eqshrstr, gkey, gnext, gval, hashstr, lua_assert, LUA_TSHRSTR, luaO_nilobject, rawtsvalue, TString::tsv, and ttisshrstring.
Referenced by luaH_get(), luaT_gettm(), and luaT_gettmbyobj().
LUAI_FUNC Table* luaH_new (lua_State * L)
Definition at line 368 of file ltable.c.
References Table::array, cast_byte, Table::flags, GCObject::h, LUA_TTABLE, luaC_newobj(), Table::metatable, setnodevector(), and Table::sizearray.
Referenced by collectvalidlines(), init_registry(), lua_createtable(), luaV_execute(), and open_func().
LUAI_FUNC TValue* luaH_newkey (lua_State * L, Table * t, const TValue * key)
Definition at line 405 of file ltable.c.
References getfreepos(), gkey, gnext, gval, isdummy, lua_assert, luaC_barrierback, luaG_runerror(), luaH_set(), mainposition(), nvalue, obj2gco, rehash(), setnilvalue, setobj2t, ttisnil, and ttisnumber.
Referenced by luaH_set(), luaH_setint(), and luaV_settable().
LUAI_FUNC int luaH_next (lua_State * L, Table * t, StkId key)
Definition at line 169 of file ltable.c.
References Table::array, cast_num, findindex(), gkey, gnode, gval, setnvalue, setobj2s, Table::sizearray, sizenode, and ttisnil.
Referenced by lua_next().
LUAI_FUNC void luaH_resize (lua_State * L, Table * t, int nasize, int nhsize)
Definition at line 304 of file ltable.c.
References Table::array, cast, gkey, gval, isdummy, Table::lsizenode, luaH_set(), luaH_setint(), luaM_freearray, luaM_reallocvector, Table::node, setarrayvector(), setnodevector(), setobjt2t, Table::sizearray, ttisnil, and twoto.
Referenced by init_registry(), lua_createtable(), luaH_resizearray(), luaV_execute(), and rehash().
LUAI_FUNC void luaH_resizearray (lua_State * L, Table * t, int nasize)
Definition at line 337 of file ltable.c.
References isdummy, luaH_resize(), Table::node, and sizenode.
Referenced by luaV_execute().
LUAI_FUNC TValue* luaH_set (lua_State * L, Table * t, const TValue * key)
Definition at line 510 of file ltable.c.
References cast, luaH_get(), luaH_newkey(), and luaO_nilobject.
Referenced by addk(), lua_rawset(), lua_rawsetp(), luaH_newkey(), luaH_resize(), and luaX_newstring().
LUAI_FUNC void luaH_setint (lua_State * L, Table * t, int key, TValue * value)
Definition at line 518 of file ltable.c.
References cast, cast_num, luaH_getint(), luaH_newkey(), luaO_nilobject, setnvalue, and setobj2t.
Referenced by collectvalidlines(), init_registry(), lua_rawseti(), luaH_resize(), and luaV_execute().