Kensho: /Users/nelliott/Documents/Projects/Kensho/lua-5.2.3/lualib.h File Reference
lualib.h File Reference
#include "lua.h"
Macros
#define LUA_COLIBNAME "coroutine"
#define LUA_TABLIBNAME "table"
#define LUA_IOLIBNAME "io"
#define LUA_OSLIBNAME "os"
#define LUA_STRLIBNAME "string"
#define LUA_BITLIBNAME "bit32"
#define LUA_MATHLIBNAME "math"
#define LUA_DBLIBNAME "debug"
#define LUA_LOADLIBNAME "package"
#define lua_assert(x) ((void)0)
Functions
LUAMOD_API int() luaopen_base (lua_State *L)
LUAMOD_API int() luaopen_coroutine (lua_State *L)
LUAMOD_API int() luaopen_table (lua_State *L)
LUAMOD_API int() luaopen_io (lua_State *L)
LUAMOD_API int() luaopen_os (lua_State *L)
LUAMOD_API int() luaopen_string (lua_State *L)
LUAMOD_API int() luaopen_bit32 (lua_State *L)
LUAMOD_API int() luaopen_math (lua_State *L)
LUAMOD_API int() luaopen_debug (lua_State *L)
LUAMOD_API int() luaopen_package (lua_State *L)
LUALIB_API void() luaL_openlibs (lua_State *L)
Macro Definition Documentation
#define lua_assert (x) ((void)0)
Definition at line 51 of file lualib.h.
#define LUA_BITLIBNAME "bit32"
Definition at line 32 of file lualib.h.
#define LUA_COLIBNAME "coroutine"
Definition at line 17 of file lualib.h.
#define LUA_DBLIBNAME "debug"
Definition at line 38 of file lualib.h.
#define LUA_IOLIBNAME "io"
Definition at line 23 of file lualib.h.
#define LUA_LOADLIBNAME "package"
Definition at line 41 of file lualib.h.
#define LUA_MATHLIBNAME "math"
Definition at line 35 of file lualib.h.
#define LUA_OSLIBNAME "os"
Definition at line 26 of file lualib.h.
#define LUA_STRLIBNAME "string"
Definition at line 29 of file lualib.h.
#define LUA_TABLIBNAME "table"
Definition at line 20 of file lualib.h.
Function Documentation
LUALIB_API void() luaL_openlibs (lua_State * L)
Definition at line 52 of file linit.c.
References luaL_Reg::func, lua_pop, lua_pushcfunction, LUA_REGISTRYINDEX, lua_setfield(), luaL_getsubtable(), luaL_requiref(), and luaL_Reg::name.
Referenced by KenshoLuaWrapper::evaluate.
LUAMOD_API int() luaopen_base (lua_State * L)
Definition at line 447 of file lbaselib.c.
References lua_pushglobaltable, lua_pushliteral, lua_setfield(), LUA_VERSION, and luaL_setfuncs().
LUAMOD_API int() luaopen_bit32 (lua_State * L)
Definition at line 208 of file lbitlib.c.
References luaL_newlib.
LUAMOD_API int() luaopen_coroutine (lua_State * L)
Definition at line 151 of file lcorolib.c.
References luaL_newlib.
LUAMOD_API int() luaopen_debug (lua_State * L)
Definition at line 394 of file ldblib.c.
References luaL_newlib.
LUAMOD_API int() luaopen_io (lua_State * L)
Definition at line 657 of file liolib.c.
References createmeta(), createstdfile(), IO_INPUT, IO_OUTPUT, and luaL_newlib.
LUAMOD_API int() luaopen_math (lua_State * L)
Definition at line 271 of file lmathlib.c.
References lua_pushnumber(), lua_setfield(), luaL_newlib, and PI.
LUAMOD_API int() luaopen_os (lua_State * L)
Definition at line 319 of file loslib.c.
References luaL_newlib.
LUAMOD_API int() luaopen_package (lua_State * L)
Definition at line 690 of file loadlib.c.
References CLIBS, createsearcherstable(), gctm(), LUA_CPATH, LUA_CPATH_DEFAULT, LUA_CPATHVERSION, lua_createtable(), LUA_DIRSEP, LUA_EXEC_DIR, LUA_IGMARK, LUA_PATH, LUA_PATH_DEFAULT, LUA_PATH_MARK, LUA_PATH_SEP, LUA_PATHVERSION, lua_pop, lua_pushcfunction, lua_pushglobaltable, lua_pushliteral, lua_pushvalue(), LUA_REGISTRYINDEX, lua_setfield(), lua_setmetatable(), luaL_getsubtable(), luaL_newlib, luaL_setfuncs(), and setpath().
LUAMOD_API int() luaopen_string (lua_State * L)
Definition at line 1014 of file lstrlib.c.
References createmetatable(), and luaL_newlib.
LUAMOD_API int() luaopen_table (lua_State * L)
Definition at line 274 of file ltablib.c.
References lua_getfield(), lua_setglobal(), and luaL_newlib.